### ISSUE TITLE
Migrate gh checks to github pages

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#100]
**Reason**
Render out the static page after running it in a github action only and than hosting it as a github static page.

**AC**
-  Nightly
-  Manually per Button
-  Make sure its using some form of caching?

**Additional information / links**

**Comment by Siegfriedk** [comment]
@SebastianBezold pls verify and close / or adjust

**Comment by SebastianBezold** [comment]
Jup this is done. The dashboard is generated statically and served via GitHub pages. 
The nightly build is missing though, since we do not have a proper auth. token, that we can use in the workflow for API authentication. This is most likely needed to overcome rate limiting
