### ISSUE TITLE
Create the maintenance dashboard

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#102]
**Reason**
A dashboard page should be created to display the data. 

**AC**
3 columns:

- name of the app
- latest version
- currently installed version on the cluster

**Additional information / links**

**Comment by FaGru3n** [comment]
@almadigabor  i would suggest that this already done or?

**Comment by Siegfriedk** [comment]
@almadigabor pls check and delete or update
