### ISSUE TITLE
Add App- & Chart-Version to apps dashboard

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#103]
**Reason**
With our new app dashboard (for example on stable: https://app.stable.demo.catena-x.net/), there is a feature missing which was skipped due to effort for the initial build:

We do not pull out the real/life appversion of the installed helm chart.

**AC**

- Pull the helm chart from github and display it on the dashboard
- github repo needs to be cached
- Github repo pull/sync needs to be running in parallel to the normal api sync (not being dependend on each other)
- please inform our test and release mgmt team about this feature when its done

**Additional information / links**
Pull recursivly max. 2 levels of helm chart and only if they are from eclipse-tractusx OR catenax-ng

**Comment by Siegfriedk** [comment]
we probably don't have time for it
