### ISSUE TITLE
Don't allow :latest images on our envs

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#107]
**Reason**

**AC**

- Implement the rule
- Limiteren auf namespaces (product only)
- Needs to be documented?!
- Needs to be configurable per cluster as we don't care what they do on dev
- We might start at one cluster like pre prod and enable it on others one by one

**Additional information / links**

**Comment by carslen** [comment]
please review PR 59

**Comment by hzierer** [comment]
LGTM as it is based on the official solution.

**Comment by FaGru3n** [comment]
approved

**Comment by FaGru3n** [comment]
just closed it
