### ISSUE TITLE
GitHub: Offboarding member on 01.07.2023 

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-infra#118]
Who should be offboarded to [Catena-X ng](https://github.com/catenax-ng)

Offboarding on 01.07.2023 

Remove Access to 
- Veracode 
- Invicti 

GitHub User:
(https://github.com/ds-ext-dskrzypczak)

Vouching person:  Steffen Duering BMW 

https://github.com/mkanal

**Comment by SebastianBezold** [comment]
Hi @mkanal,

to make sure: Do you also want yourself to be offboarded, since you are mentioned at the end?

@the-tatanka FYI for the security tooling offboarding

**Comment by the-tatanka** [comment]
thanks @SebastianBezold 
Who is [@ds-ext-dskrzypczak](https://www.youtube.com/shorts/FlqU0nVtUgs)?

**Comment by mkanal** [comment]
Darek Skrzypczak
darek.skrzypczak@partner.doubleslash.de
He is not working for C-X any more.

**Comment by mkanal** [comment]
No I do not want to be unboarded. (Sadly this is not JIRA :-) )

Vouching person: 
- Steffen Duering BMW
- https://github.com/mkanal
