### ISSUE TITLE
Create infra overview dashboard

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#119]
**Reason**
Our current monitoring stack provides us with default dashboards from the kube-prometheus-stack project.

To have a better overview for us on our clusters, we want to create a default 'infra' dashboard which provides us with all critical information about the cluster state.

**AC**

- This dashboard should answer questions like:
  - How many nodes are running
  - How much CPU is requested and how much CPU is available
  - How much memory is requested and how much Memory is available
  - Overview table off all namespaces
     - Including how much cpu and memory they consume (to be able to sort by it to see if one customer namespace uses much more than others)
   - . . . Feel free to add other helpful metrics
- Dashboard should be IaC (can be done through some config map, Grafana helm chart supports this)
- It is added to all environments (currently we do not federate all grafanas into one to be able to have an overview of all clusters, for now, we will add this dashboard to all envs)
- Bonus: When logging into Grafana, the new infra dashboard should be a favorite or easy to be seen
- 

**Additional information / links**

**Comment by Siegfriedk** [comment]
would have been great a year ago
