### ISSUE TITLE
Add one more assignee to the security issue template

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#12]
**Is your support request related to a problem? Please describe.**  
Request from @BANANAS1337
We want to have two assignees in the security issue template

**Additional context**  
Link: [https://github.com/eclipse-tractusx/sig-infra/issues/new?assignees=the-tatanka&labels=security&template=security-support-request.md&title=](https://github.com/eclipse-tractusx/sig-infra/issues/new?assignees=the-tatanka&labels=security&template=security-support-request.md&title=)

**Comment by FaGru3n** [comment]
Hi @BANANAS1337,

should be possible, could you tell me the assignee UserID?

**Comment by BANANAS1337** [comment]
Please take myself

**Comment by FaGru3n** [comment]
#17 @BANANAS1337  will removed form issue templates
