### ISSUE TITLE
introduce ServiceMonitor CRD

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#120]
**Reason**

**Additional information / links**
https://github.com/prometheus-operator/prometheus-operator/blob/main/Documentation/design.md#servicemonitor

**Comment by SebastianBezold** [comment]
ServiceMonitor is included automatically with `kube-prometheus-stack`. We do even use it already for some service discovery. 
So in my opinion, we can close this issue
