### ISSUE TITLE
Setup Grafana Tempo

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#121]
**Reason**
As the DevOps Tooling Team, we want to setup Grafana Tempo to enable product teams to get deeper insight into their code across services.

**AC**

- Use the Grafana setup from kube-prometheus-stack
  - Requires to configure Grafana tempo datasource
- Provide Grafana Tempo dashboard
- Provide Grafana Agent for tempo
- Make grafana tempo auth data available to teams
  - Providing it as a secret per namespace
- Make it part of our default stack
- Document how to use it
- Unclarified: We should create/use our k8s-helm-example to show how tracing works. Either in this story for benchmarking or in a second story in combination with this.
  - Potential example apps
  - nginx on k8s-helm-example
  - java on test-data-generator

**Additional information / links**

**Comment by Siegfriedk** [comment]
would have been a great idea a year ago
