### ISSUE TITLE
Removal, Renaming and Deprecation of Unused Sonar Projects

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/sig-infra#125]
Please report **undisclosed** or **confidential** vulnerabilities here: [Eclipse Security](https://www.eclipse.org/security/)

**Topics (Please mark an [x] to your Topic):**
- [ ] KICS
- [ ] Invicti
- [ ] GitGuardian
- [ ] Pentesting
- [ ] Security assessment (threat modeling, code reviews)
- [ ] Trivy
- [ ] Veracode (initial setup, GitHub integration)
- [x] Other

**Please describe your request:**

Since the fork were created this projects are or deprecated or with the wrong name confusing when validation is need.

**Projects to remove:**
1. [catenax-ng_product-value-added-service](https://sonarcloud.io/project/overview?id=catenax-ng_product-value-added-service)
2. [catenax-ng_product-vas-country-risk-frontend](https://sonarcloud.io/project/overview?id=catenax-ng_product-vas-country-risk-frontend)

**Project to rename:**
1. [catenax-ng_tx-vas-country-risk-backend](https://sonarcloud.io/project/overview?id=catenax-ng_tx-vas-country-risk-backend) - Rename from `value-added-service` to `tx-vas-country-risk-backend`

 If there are any issues or further information needed, feel free to reach out. Thank you.

**Comment by the-tatanka** [comment]
Hi @fabiodmota , the security team is not responsible for SonarQube or SonarCloud.
@FaGru3n can you help please?

**Comment by SebastianBezold** [comment]
Hi @fabiodmota, 
I deleted both of the mentioned sonarcloud projects.

You should be able to rename the project yourself with the `sonar.projectName` setting.
I cannot find that in either your [pom.xml](https://github.com/catenax-ng/tx-vas-country-risk-backend/blob/main/pom.xml) or the [sonar-project.properties](https://github.com/catenax-ng/tx-vas-country-risk-backend/blob/main/sonar-project.properties), so I think it is defaulting to the name [defined in your pom](https://github.com/catenax-ng/tx-vas-country-risk-backend/blob/main/pom.xml#L34).

The change should then take effect automatically with the next analysis. Could you try that please and also double check, if the right projects are deleted?

**Comment by fabiodmota** [comment]
Also changed added the project name to my pom and changed the name on sonar , we can close on my side this ticket
