### ISSUE TITLE
Implement Stable Helm Repository

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#126]
**Reason**
As Catena-X Rel 2.0/2.1 is available since mid of december 2022, stable helm repo should be implemented.

Things to clarify/design:

- Which source of available Charts for stable Helm Repository should be used?
- How to build the index.yaml for stable Helm Repository (using excerpt of DEV, or reading it from the product git repos)?
- ...

**Additional information / links**

**Comment by Siegfriedk** [comment]
We have one aligned helm chart version; next move will be to nexus
