### ISSUE TITLE
Veracode Password reset.

### ISSUE THREAD

**Issue by Ruskyy** [eclipse-tractusx/sig-infra#130]
**Topics (Please mark an [x] to your Topic):**
- [ ] KICS
- [ ] Invicti
- [ ] GitGuardian
- [ ] Pentesting
- [ ] Security assessment (threat modeling, code reviews)
- [ ] Trivy
- [X] Veracode (initial setup, GitHub integration)
- [ ] Other

Request Veracode password reset.

**Comment by the-tatanka** [comment]
Please write me your mail address so I can find you in Veracode.
_Generally helpful if you would add your real name to your GitHub profile, so that it is clear that you are not an NPC._

**Comment by Ruskyy** [comment]
My email would be : sergio.figueiredo@cgi.com

**Comment by the-tatanka** [comment]
Change password email sent
