### ISSUE TITLE
WIP: Clarify how to run sonarcloud analysis on PRs to tractus-x

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#134]
In the office hour, a colleague described a problem regarding static code analysis in tractus-x on PR level.

In this case, the workflow model of sonarcloud is used. PRs from inside the repository are running fine, but PRs from external forks do not work unfortunately. 

It seems like the workflow running for PRs from external forks do not have access to repository secrets, that are needed (sonarcould API Key)

**Comment by Siegfriedk** [comment]
yeah and now most are working in tractus-x and no clue if anyone is using sonar
