### ISSUE TITLE
Create workflow to automatically create IP issues 

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#145]
Input (manual via UI):

Dependency list
API token

constraint:

manually run
API token must not be visible in any log output

Discussion:

How to provide the dependency list (file, filename pointing to the repo, textarea, ...)
Do we add the workflow to every existing repo, or just a single one?

**Comment by Siegfriedk** [comment]
We have an example action; We also don't want auto ip issue creation. We keep what we have for now
