### ISSUE TITLE
Check for restricted + rejected dependencies

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#146]
Manually run workflow, that should be used when checking the release.

This is helpful, because at the time of a release, a project must not contain any restricted or rejected dependencies.

We can combine this with a previous check, if the DEPENDENCIES are up to date

Also possible:

If teams have automated release pipelines, we can add that as check as well

**Comment by tomaszbarwicki** [comment]
@FaGru3n I think it is already included in the workflow dash-licence-check.yaml, it does some checks for that:
![obraz](https://github.com/eclipse-tractusx/sig-infra/assets/7613143/3207c07f-43fd-4b0a-8854-ba5414b67348)

shall we close it?
