### ISSUE TITLE
Create GitHub action to check for license header presence

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#148]
We want to have a GitHub action, that can be run on any of our repositories and checks the source files for proper license + copyright headers.

Potential problems:

- Some files cannot be checked (no comment option)
- Some file should be ignored (autogenerated ones)
- Different commenting character per file type
- Potentially slight differences in year for example
- Different "taste" regarding leading and closing comment line

**Comment by Siegfriedk** [comment]
Sounds like to bridle/too much effort for just checking it
