### ISSUE TITLE
Verify/Migrate ghc TRG2.03 Repo Structure

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#151]

**Comment by tomaszbarwicki** [comment]
https://github.com/catenax-ng/tx-tractusx-quality-checks/tree/feat/add_repo_structure_check

**Comment by tomaszbarwicki** [comment]
https://github.com/eclipse-tractusx/tractusx-quality-checks/pull/19

**Comment by SebastianBezold** [comment]
Hi @tomaszbarwicki,
the PR is already merged, so I think this issue can be closed. What do you think?
