### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by shijinrajbosch** [eclipse-tractusx/sig-infra#152]
Hi All,

I work as developer in the sldt-team and need access to the product-semantics repository: https://github.com/catenax-ng/product-semantics.

 GitHub User: shijinrajbosch

Vouching person:
@LuLeRoemer , @bs-jokri , @tunacicek and the Product Owner is Thomas Henn can verify, that I am member of Catena-X NG Github Organisation.

Best regards
Shijin Raj

**Comment by FaGru3n** [comment]
Hi @LuLeRoemer , @bs-jokri , @tunacicek 

could you verify that @shijinrajbosch is part of the Catena-X NG? 

Thanks in advance.

**Comment by tunacicek** [comment]
Hi @FaGru3n ,

thanks for your support. 
Shijin (@shijinrajbosch ) is a part of our sldt-team as developer and needs access to the catenaX NG. 

Best Regards
Tuna

**Comment by FaGru3n** [comment]
Hi @shijinrajbosch , 
invitation was sent.
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/14e4e5a4-a19f-464e-9fca-5b285ea99cb2)

After the successfull invitation the maintainer of the gh-team could invite you to the desired team for getting permissions on the repositories were you can work. 😉 

Best Regards

**Comment by FaGru3n** [comment]
invite complete issue will be closed
