### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by agg3fe** [eclipse-tractusx/sig-infra#153]
Hi All,

I work as developer in the sldt-team and need access to the product-semantics repository: https://github.com/catenax-ng/product-semantics.

GitHub User: agg3fe

Vouching person:
@LuLeRoemer , @bs-jokri , @tunacicek and the Product Owner is Thomas Henn can verify, that I am member of Catena-X NG Github Organisation.

Best regards
Sahil

**Comment by tunacicek** [comment]
Hi Together, 

@agg3fe  is a part of our sldt-team and needs the access to the repository (product-semantics). 

Thanks for your support.

**Comment by tomaszbarwicki** [comment]
Hi @agg3fe,

Invitation has been sent. Please contact your maintainer in order to add you to proper GitHub teams.

BR
TB

**Comment by tomaszbarwicki** [comment]
@agg3fe please verify and close the issue
