### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/sig-infra#159]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User:
- @agg3fe
- @bs-sili
- @shijinrajbosch

Vouching person: @tunacicek 

@tunacicek, please use our issue templates instead of direct mails. This is the only way we can ensure, that requests are not forgotten or wait ages due to vacation or similar.
We also updated the [Things to request](https://catenax-ng.github.io/docs/resources) page with links and info regarding the process

**Comment by SebastianBezold** [comment]
@tunacicek, I just saw, that your colleagues are all already members of the catenax-ng organization. 
Access to repositories is always granted to teams. Membership to the teams is completely up to the teams maintainers.
In your case, you can invite them yourself, since you are maintainer of the [product-semantics](https://github.com/orgs/catenax-ng/teams/product-semantics) team.

**Comment by tunacicek** [comment]
@SebastianBezold  Thanks for your support. 
I couldn't find the right page to add new members. But now I have it and add the colleagues.
Thank you :) I will close the issue.
