### ISSUE TITLE
GitHub: New repository 

### ISSUE THREAD

**Issue by ChristopherWinterZF** [eclipse-tractusx/sig-infra#161]
Required information:
I would like to have to Repositories in catena x ng. Both are for the Business Domain sustainability. Ther first KIt should be something like BD-SUS-KITs. Here we want to work on KIT related content. The second one should be BD-SUS-Standardization-Candidates. As we need work together on the Standardization documents it would be could to have a Repo. Both should be private 

 Details to GitHub team to grant access: Not yet defined

validation / approved by: ChristopherWinterZF

**Comment by hzierer** [comment]
Hi @ChristopherWinterZF,

since you did not provide an team name: I assume this is a completely new team. Can you please tell us the name of this new team?

**Comment by ChristopherWinterZF** [comment]
Hi, 

it the Architecture Team covering the topics of the Business Domain Sustainability

**Comment by hzierer** [comment]
Hi,

I would propose the following names:
- product-sustainability-kits
- product-sustainability-standardization

Are these ok for you?

(I know these are no "real" products, but currently all repos with content of the Catena-X teams are prefixed this name)

**Comment by almadigabor** [comment]
Hi @ChristopherWinterZF, any updates on this ticket?

**Comment by FaGru3n** [comment]
> Hi @ChristopherWinterZF, any updates on this ticket?

Hi @ChristopherWinterZF  is there a changed requirement?

**Comment by FaGru3n** [comment]
Hi @ChristopherWinterZF,

we waited for your feedback so repositories are still not present in the catenax ng org...

so suggested names are approved?

`product-sustainability-kits`
`product-sustainability-standardization`

and the team-name is still a question to us or should we create a new gh-team with you as a maintainer?

Team name is required: something like `product-sustainability-team`

**Comment by ChristopherWinterZF** [comment]
Names are fine. I could be ``architects-sustainability-team``

**Comment by FaGru3n** [comment]
created PR https://github.com/catenax-ng/product-onboarding/pull/46 so need a aprove from our System Team members that could verify our changed and inform you when repositories are available.

**Comment by FaGru3n** [comment]
private repos are now available:
https://github.com/catenax-ng/product-sustainability-standardization
https://github.com/catenax-ng/product-sustainability-kits

access granted for gh-team:
https://github.com/orgs/catenax-ng/teams/product-architects-sustainability-team

invited you @ChristopherWinterZF as maintainer

Please verfiy and close the issue if your fine with the result.

**Comment by FaGru3n** [comment]
Hi @ChristopherWinterZF any feedback or should i just close the issue?

**Comment by ChristopherWinterZF** [comment]
Its fine you can close the ticket thank you
