### ISSUE TITLE
Veracode access

### ISSUE THREAD

**Issue by Bailonis** [eclipse-tractusx/sig-infra#165]
Please report **undisclosed** or **confidential** vulnerabilities here: https://www.eclipse.org/security/

**Topics (Please mark an [x] to your Topic):**
- [ ] KICS
- [ ] Invicti
- [ ] GitGuardian
- [ ] Pentesting
- [ ] Security assessment (threat modeling, code reviews)
- [ ] Trivy
- [X] Veracode (initial setup, GitHub integration)
- [ ] Other

Would like to request acess, to the configuration of Veracode, for the following repo:
tx-demand-capacity-mgmt-frontend

Followup: https://github.com/eclipse-tractusx/sig-infra/issues/36

**Comment by FaGru3n** [comment]
FYI: @Essenbreis

**Comment by Essenbreis** [comment]
The Application demand-capacity-mgmt-frontend was created live in Consultation Hour :-)

**Comment by Essenbreis** [comment]
The Application demand-capacity-mgmt-frontend was created live in Consultation Hour :-)
