### ISSUE TITLE
Resource Management - Dev Cluster

### ISSUE THREAD

**Issue by ds-mwesener** [eclipse-tractusx/sig-infra#166]
**Is your support request related to a problem? Please describe.**  
Dev Cluster Environment - All Containers in Pending state. Cannot be deployed anymore.
[Trace-X Dev Cluster](https://argo.dev.demo.catena-x.net/applications?proj=&sync=&autoSync=&health=&namespace=&cluster=&labels=)

**Describe the solution you'd like**  
Suggestions how to setup the resource request / limits to be able to deploy. We currently following the TRGs.

**Comment by hzierer** [comment]
Yes, currently most of the CPU resources of the Dev-Cluster are in use (actually most are only reserved but not in use)

**Comment by hzierer** [comment]
Hi @ds-mwesener,
is everything working again? can we close this?
