### ISSUE TITLE
GitHub: New fork of w3id.org

### ISSUE THREAD

**Issue by drcgjung** [eclipse-tractusx/sig-infra#169]
This has been discussed/decided with @danielmiehle and @HFocken in order to request and maintain a "catenax" namespace under w3id.org

See https://w3id.org/#new

repository name: 
https://github.com/perma-id/w3id.org

repository name within Catena-X NG Organisation: 
pid-w3id.org

GitHub team to grant access: 
product-knowledge, product-semantics

**Comment by almadigabor** [comment]
Hi @drcgjung. As far as I understand you need this fork to create a single Pull Request to the upstream https://github.com/perma-id/w3id.org repository. Can you create the fork to your own personal GitHub profile? Or is there a reason (like long term work) you want this in the catenax-ng organization?

**Comment by drcgjung** [comment]
Hey Gabor,

we need the fork also to maintain the w3id-namespace -> catenax-ng source files rules.

This should happen from within the Catena-X association (various people from the Semantics working group will care I guess)

CGJ

**Comment by almadigabor** [comment]
Hi @drcgjung ,

[Fork](https://github.com/catenax-ng/pid-w3id.org) is created and maintain role added to the requested teams. Please confirm it works.
