### ISSUE TITLE
Document TRG Create and Change process in TRG 0 section

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/sig-infra#173]
We discussed about the create and change process for TRG but we did not document them.

**Comment by SebastianBezold** [comment]
@carslen I actually think we have that documented.
Are you missing specifics, that are not yet defined in [the release guideline intro](https://eclipse-tractusx.github.io/docs/release)?

**Comment by carslen** [comment]
You're right. I wasn't aware of this page anymore.
