### ISSUE TITLE
Docusaurus upgrade

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sig-infra#175]
Current [eclipse-tractusx.github.io](https://github.com/eclipse-tractusx/eclipse-tractusx.github.io) website Docusaurus version is outdated. Requirement of this issue is to upgrade Docusaurus version to latest.

**Comment by tomaszbarwicki** [comment]
Since Feb'23 the upgrade isn't possible due to underlying dependencies.
Topic refreshed in Jul'23, still open-api plugin is blocking point for the upgrade. Decision to postpone until stable open-api version is released supporting new Docusaurus.

More info: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/130

**Comment by Siegfriedk** [comment]
Also new trg: https://github.com/eclipse-tractusx/sig-infra/issues/376
