### ISSUE TITLE
New GitHub Secrets

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/sig-infra#176]
Could you please add two new GitHub secrets for the project https://github.com/catenax-ng/tx-item-relationship-service

secret name: `ORG_IRS_OAUTH2_CLIENT_ID_INT`
secret value: please take the value from https://vault.demo.catena-x.net/ui/vault/secrets/traceability-irs/show/int/keycloak/oauth2#clientId

secret name: `ORG_IRS_OAUTH2_CLIENT_SECRET_INT`
secret value: please take the value from https://vault.demo.catena-x.net/ui/vault/secrets/traceability-irs/show/int/keycloak/oauth2#clientSecret

**Comment by FaGru3n** [comment]
Hi @ds-jhartmann,

secrets were added to your fork repository `tx-item-relationship-service`
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/bae8f996-bb5c-4623-be7d-ed7afc28be71)

Please review and close the issue if your fine with it.

**Comment by ds-jhartmann** [comment]
Our workflow was able to access the secrets. Thank you!

**Comment by FaGru3n** [comment]
a pleasure
