### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#178]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User:
@johannsvarela

Vouching person: Patrick Strauß

Asking for access to following catena-ng organizations (GitHub): 

Catenax-ng team: https://github.com/orgs/catenax-ng/teams/traceability-spec
Catenax-ng fork: https://github.com/catenax-ng/eclipse-tractusx.github.io

first created in A1ODT-1404

**Comment by FaGru3n** [comment]
Hi @johannsvarela could you provide us the vouching persons GitHub UserID?

**Comment by FaGru3n** [comment]
For assignment to the dedicated gh-team [traceability-spec](https://github.com/orgs/catenax-ng/teams/traceability-spec), you can ask the maintainer of the team

![Image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/adc56b77-c7ac-450d-b2c7-bf179d2b9742)

this gh-team have also access to Catenax-ng fork: https://github.com/catenax-ng/eclipse-tractusx.github.io

but this invite to the gh-team works after your invitation to the [Catena-X ng](https://github.com/catenax-ng) was succcessfull

**Comment by FaGru3n** [comment]
After successfull vouching from Patrick Strauß in the jira-ticket invitation was sent:


![Image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/862b3e0c-543c-4914-90ee-37d77a123bc2)

**Comment by FaGru3n** [comment]
@johannsvarela

Please verify the invitaion and close the issue afterwards.

Thanks in advance.

**Comment by johannsvarela** [comment]
Hi @FaGru3n  thanks a lot for adding me as member to this repository! :)
I've verified the invitation yet and configured a security key for the authentication.

I closed the issue in Jira, but I can't close this GitHub issue myself.

**Comment by FaGru3n** [comment]
Side Info: to get more permission on ETX https://github.com/eclipse-tractusx here are the getting started infos
https://eclipse-tractusx.github.io/docs/oss/getting-started
