### ISSUE TITLE
Configure apps to be scanned

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#181]
**Description**
probably need to patch the k8s resource files in the k8s-cluster stack repo to include all the necessary labels and annotations. For more info see the readme configuration section: https://github.com/catenax-ng/maintenance-dashboard/blob/main/README.md

**Visualisation**
PR: https://github.com/catenax-ng/k8s-cluster-stack/pull/396

**Comment by almadigabor** [comment]
Won't do it, probably too late in the consortia phase, other tasks need more focus.
