### ISSUE TITLE
Separate stack configuration from k8s-cluster-stack repo

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#182]
Separate the stack configuration from k8s-cluster-stack repo.

Stuff to separate:

deployment of default stack apps

Maybe another repository is required here (e.g. k8s-stack-config).

Info:
There has been done some brainstorming with @SebastianBezold @carslen @hzierer  and @FaGru3n  . Current state has not been pushed to any repository but exists in a local folder structure on Sebastians Notebook

I've started once again, based on kustomize. Maybe we're going to use chart and kustomize.

**Comment by FaGru3n** [comment]
Hi is this not allready done?

**Comment by Siegfriedk** [comment]
we will close the ticket for now and start recreating this ticket when we have time or feel the pressure again
