### ISSUE TITLE
Azure: Action recommended: Update your AKS pricing tier API parameters to avoid a breaking change

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#183]
Update AKS pricing tier API parameters when you begin using Azure API 2023-02-01 or newer to avoid a breaking change  You're receiving this notice because you use Azure Kubernetes Service (AKS).As part of our efforts to improve AKS cluster and workload reliability, we're updating AKS pricing tiers. This includes removing the "Basic" parameter in ManagedClusterSKUName and the "Paid" parameter in ManagedClusterSKUTier in Azure API version 2023-02-01, which is a breaking change.The "Basic" parameter in ManagedClusterSKUName was replaced by "Base". The "Paid" parameter in ManagedClusterSKUTier was replaced by "Standard", which has the uptime SLA enabled by default, plus:   Support for up to 5,000 nodes per cluster. Improved cluster reliability and resources.

</div>
<h2>Recommended action</h2>
<p>To avoid disrupting your AKS workloads, update any automated scripts, CD pipelines, ARM templates, Terraform, or other third-party tooling that relies on the <em>ManagedClusterSKUName</em> and <em>ManagedClusterSKUTier</em> parameters that use "Basic" or "Paid" to use "Base" or "Standard" when you adopt Azure API version 2023-02-01 or newer.</p>Update AKS pricing tier API parameters when you begin using Azure API 2023-02-01 or newer to avoid a breaking change

You're receiving this notice because you use Azure Kubernetes Service (AKS).
As part of our efforts to improve AKS cluster and workload reliability, we're [updating AKS pricing tiers](https://learn.microsoft.com/azure/aks/free-standard-pricing-tiers). This includes removing the "Basic" parameter in ManagedClusterSKUName and the "Paid" parameter in ManagedClusterSKUTier in Azure API version 2023-02-01, which is a breaking change.
The "Basic" parameter in ManagedClusterSKUName was replaced by "Base". The "Paid" parameter in ManagedClusterSKUTier was replaced by "Standard", which has the uptime SLA enabled by default, plus:

Support for up to 5,000 nodes per cluster.
Improved cluster reliability and resources.
ManagedClusterSKU parameter changes in Azure API versions

	2023-01-01 API or earlier	Starting with 2023-02-01 API
ManagedClusterSKUName	"Basic"	"Base"
ManagedClusterSKUTier	"Free"
"Paid"	"Free"
"Standard"
Recommended action

To avoid disrupting your AKS workloads, update any automated scripts, CD pipelines, ARM templates, Terraform, or other third-party tooling that relies on the ManagedClusterSKUName and ManagedClusterSKUTier parameters that use "Basic" or "Paid" to use "Base" or "Standard" when you adopt Azure API version 2023-02-01 or newer.

**Comment by carslen** [comment]
Would be great if one could verify my research and review this ticket.

**Comment by FaGru3n** [comment]
helpfull command for me: 
`az aks list --output table`

taken your command and checked it on every cluster example: 
``` bash
$az aks show --name cx-beta-aks --resource-group cx-beta-rg | jq .sku
{
  "name": "Base",
  "tier": "Free"
}
$az aks show --name cx-core-aks --resource-group cx-core-rg | jq .sku
{
  "name": "Base",
  "tier": "Free"
}
$az aks show --name cx-dev-aks --resource-group cx-dev-rg | jq .sku
{
  "name": "Base",
  "tier": "Free"
}
$az aks show --name cx-devsecops-testing-aks --resource-group cx-devsecops-testing-rg | jq .sku
{
  "name": "Base",
  "tier": "Free"
}
$az aks show --name cx-stable-aks --resource-group cx-stable-rg | jq .sku
{
  "name": "Base",
  "tier": "Free"
}
$az aks show --name cx-vault-aks-services --resource-group cx-vault-rg | jq .sku
{
  "name": "Base",
  "tier": "Free"
}
```
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/259d421a-a120-462a-acd1-fd6fb8e35d44)

after description 
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/796783aa-bcf9-42d7-86ec-1594e2e8671d)

i would suggest it is only a cost question
@Siegfriedk shall we stay on standard tier for the INT cluster?

- found command to update an existing cluster to the Free tier if needed:
`az aks update --name cxtsi-hotel-budapest-aks-services --resource-group cxtsi-hotel-budapest-rg --tier free
`

but found out that our default is sku=standard so for now i would also suggest nothing to do here:
https://github.com/catenax-ng/cloud-infra/blob/947a3688f6848725f2df347f1cfcd18307c38224/modules/consortium_cluster/main.tf#L12

**Comment by FaGru3n** [comment]
also found yesterday a azure portal option to change the tiers if we want to:
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/2ddfdf0c-6947-4c5d-bb05-91ea5cf207e3)

**Comment by carslen** [comment]
Of course there is a possibility to change ;)
