### ISSUE TITLE
GitHub: New fork 

### ISSUE THREAD

**Issue by drcgjung** [eclipse-tractusx/sig-infra#189]
repository name within Tractus-X Organisation: 
[knowledge-agents](https://github.com/eclipse-tractusx/knowledge-agents)

repository name within Catena-X NG Organisation: 
tx-knowledge-agents

GitHub team to grant access: 
[product-knowledge](https://github.com/orgs/catenax-ng/teams/product-knowledge)

tx-knowledge-agents will supersede product-agents (when the initial PR has been made).
I could not not that with my private repo due to restrictions in github lfs (https://github.com/git-lfs/git-lfs/issues/1906).

**Comment by almadigabor** [comment]
Hi @drcgjung ,

[Repository ](https://github.com/catenax-ng/tx-knowledge-agents) has been created. Please check if everything works.
