### ISSUE TITLE
GitHub: New fork 

### ISSUE THREAD

**Issue by drcgjung** [eclipse-tractusx/sig-infra#190]
repository name within Tractus-X Organisation: 
[knowledge-agents-edc](https://github.com/eclipse-tractusx/knowledge-agents-edc)

repository name within Catena-X NG Organisation: 
tx-knowledge-agents-edc

GitHub team to grant access: 
[product-knowledge](https://github.com/orgs/catenax-ng/teams/product-knowledge)

tx-knowledge-agents-edc will supersede product-agents-edc (when the initial PR has been made).
I could not not that with my private repo due to restrictions in github lfs (https://github.com/git-lfs/git-lfs/issues/1906).

**Comment by almadigabor** [comment]
Hi @drcgjung ,

The repository in Tractus-X need to be initialized first before creating the fork. Let me know when the first commit is made.

**Comment by drcgjung** [comment]
Hi @almadigabor , @Siegfriedk 

since we have yet no eclipse commiter, could someone from your team please just commit a dummy README.md to the [knowledge-agents-edc](https://github.com/eclipse-tractusx/knowledge-agents-edc)

Thx,
CGJ

**Comment by FaGru3n** [comment]
@drcgjung  done.
https://github.com/eclipse-tractusx/knowledge-agents-edc/tree/main

FYI to become a committer some "getting started"-information can be found here: 😉 
https://eclipse-tractusx.github.io/docs/oss/getting-started

**Comment by FaGru3n** [comment]
Fork was created
https://github.com/catenax-ng/tx-knowledge-agents-edc

Please verify and close the issue.
