### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by zfdevzfdev** [eclipse-tractusx/sig-infra#193]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User:
[TobiasKampsZF](https://github.com/TobiasKampsZF)
[JulianSchererZF](https://github.com/JulianSchererZF)
[AdamPolakZF](https://github.com/AdamPolakZF)
[NorbertNagyFIIW43](https://github.com/NorbertNagyFIIW43)

Vouching person: [JulianSchererZF](https://github.com/JulianSchererZF)
Maintainer: [zfdevdev](https://github.com/zfdevdev)

**Comment by FaGru3n** [comment]
Hi @zfdevzfdev little hint you can directly mention the github profile via `@github-user-id`

**Comment by tomaszbarwicki** [comment]
Hi @evgenyvinokurov,

Can you please confirm the list of new users who should be added to organisation.
Thanks in advance.

**Comment by evgenyvinokurov** [comment]
@tomaszbarwicki yes, I confirm

**Comment by tomaszbarwicki** [comment]
@evgenyvinokurov thanks!

@zfdevzfdev:

This is to confirm that requested people got invited to Catena-X organisation. Once accepted they can be added by GitHub team maintainer to a team(s).

**Comment by FaGru3n** [comment]
Hi @zfdevzfdev,

any updates on the invitation and could you verify and close the issue?

Thanks in advance.

**Comment by zfdevzfdev** [comment]
I still can't add the members: 
![image](https://github.com/eclipse-tractusx/sig-infra/assets/39905251/627a0071-498e-4d4f-b5e1-66d8b6dd08e9)

**Comment by FaGru3n** [comment]
please try again, works for those member that are actually in the GitHub Organisation like @JulianSchererZF
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/280db64d-04a6-40a8-9ebd-dd16452c041b)
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/484adf8d-8f98-41dd-bd52-30f1f3c0a10c)


the other ones missed the inivitation.
> Invitation expired. User did not accept this invite for 7 days

retry invitation:
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/3b18c349-083e-4e6d-bb7a-1c159d8307cd)
