### ISSUE TITLE
GitHub: Invite member "SMaierTSI"

### ISSUE THREAD

**Issue by evgenyvinokurov** [eclipse-tractusx/sig-infra#196]
Please invite the following person to Catena -X NG Organisation:

GitHub User:
@SMaierTSI

Vouching person: 
@evgenyvinokurov

**Comment by FaGru3n** [comment]
Hi @evgenyvinokurov could you verify @SMaierTSI as a new user from catena-x?

**Comment by evgenyvinokurov** [comment]
> Hi @evgenyvinokurov could you verify @SMaierTSI as a new user from catena-x?

Hello @FaGru3n Steffen is a team member who takes care of the standard documents

**Comment by FaGru3n** [comment]
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/36ea60c5-6190-42d8-b479-c74a3e0ba386)

invitation is done.

Please review and close the issue after invitation was successfull

**Comment by SMaierTSI** [comment]
Thank you for the prompt invitation.

**Comment by evgenyvinokurov** [comment]
Steffen is in the Standardisation Repository
