### ISSUE TITLE
Please add exclusion in sonar cloud scr/assets/locales/* for false alert duplication.

### ISSUE THREAD

**Issue by adityagajbhiye9** [eclipse-tractusx/sig-infra#197]
In our Simple data exchanger frontend, we have internationalisation for German and English languages.  So we have locale files for both the languages. Its ideally a object structure, whereas object keys will be the same but the values changes with translation. I think sonarcloud not considering the values of the object but only the keys. So its failing in main branch. Please add the respective person to this thread so that they can look into the project configuration.
 
You can check those two files here - https://sonarcloud.io/component_measures?id=catenax-ng_tx-dft-frontend&metric=new_duplicated_lines_density&view=list

**Comment by FaGru3n** [comment]
Hi @adityagajbhiye9,

please on of our support template then our workflows will match "blank" issue are four out internen system team things 😉 
modified sonar settings to 

`sonar.cpd.exclusions=src/assets/locales/**/main.json` 

info wildcard with only one * will Match zero or more characters ** Match zero or more directories

**Comment by adityagajbhiye9** [comment]
Closing this issue as it is blank issue
