### ISSUE TITLE
modified sonar settings to  sonar.cpd.exclusions=src/assets/locales/**/main.json

### ISSUE THREAD

**Issue by adityagajbhiye9** [eclipse-tractusx/sig-infra#198]
**Topics (Please mark an [x] to your Topic):**
- [x] Sonarcloud

**Please describe your request:**

In our Simple data exchanger frontend, we have internationalisation for German and English languages. So we have locale files for both the languages. Its ideally a object structure, whereas object keys will be the same but the values changes with translation. I think sonarcloud not considering the values of the object but only the keys. So its failing in main branch. Please add the respective person to this thread so that they can look into the project configuration.
You can check those two files here - https://sonarcloud.io/component_measures?id=catenax-ng_tx-dft-frontend&metric=new_duplicated_lines_density&view=list

modified sonar settings to:
sonar.cpd.exclusions=src/assets/locales/**/main.json

**Comment by adityagajbhiye9** [comment]
Sure checking.

**Comment by adityagajbhiye9** [comment]
Exclusion worked, didn't find duplicate code.
thanks @FaGru3n

**Comment by FaGru3n** [comment]
@adityagajbhiye9  great 😍 thx for feedback
