### ISSUE TITLE
Extend resources for traceability-foss int cluster

### ISSUE THREAD

**Issue by ds-ext-sceronik** [eclipse-tractusx/sig-infra#199]
Hello there ! 

Recently we had to extend our deployment architecture related to a decentralized approach and for our application functionality to work we had to deploy additional applications. 
during startup of our application we noticed some database is not starting up since there was not enough resources for it to start up. ( as far as we noticed only one database for EDC was blocked with insufficient resources other pods were starting up with no problem ) 

We would like to kindly ask You to extend resources for us so we our deployments start up without issues. 

Best regards !

**Comment by hzierer** [comment]
Hi @ds-ext-sceronik,

we are currently not very committed to increase the resources again. Especially as your team/product is already blocking so many resources and not using them. As we told already in the office hours, please adjust your CPU/Mem limits to a reasonable amount.
Tracability-foss is currently requesting (= blocking exclusively) 19% of the whole INT cluster, while actually using only 0,2% of the cluster: [please check our grafana board for reference](https://grafana.int.demo.catena-x.net/d/85a562078cdf77779eaa1add43ccec1e/kubernetes-compute-resources-namespace-pods?var-datasource=default&var-cluster=&var-namespace=product-traceability-foss&orgId=1&refresh=10s&from=now-7d&to=now)

These unnecessarily blocked resources not only block additional containers from your team but also every other team.

Regarding the limits, you can set these with a granularity of 1/1000 of a CPU. E.g. "125m" = 1/8 CPU

**Comment by carslen** [comment]
No additional feedback since july 27., I'm going to close this issue end of this week (july 25.).
