### ISSUE TITLE
changing Billing Email for catenax ng

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#202]
Hi @Siegfriedk,

at the moment we are not getting notified when github action minutes are hit the limit.

> You've used 100% of included services for GitHub Actions.
> To continue using Actions & Packages uninterrupted, update your spending limit

should we change it to [devsecops@catena-x.net](mailto:devsecops@catena-x.net)?

![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/a34a8e70-4e38-4614-af9d-ded78f2689b7)

**Comment by Siegfriedk** [comment]
The billing address is not ours to have. On catena-x it should be daniel miehle on tractus-x it should be eclipse foundation
