### ISSUE TITLE
Extend seetings in the sustainability repos

### ISSUE THREAD

**Issue by ChristopherWinterZF** [eclipse-tractusx/sig-infra#206]
**Is your support request related to a problem? Please describe.**  
  Hi, currently we have two private repos for our BD Sustainability: 
       1. https://github.com/catenax-ng/product-sustainability-kits
       2. https://github.com/catenax-ng/product-sustainability-standardization

currently I´m not able do create issues and add assignees to these issues. As well as I can not add reviewer for a pull request. As the team members should work on the kits and standards we need this functioanlities that the BDA (me) can coordinate the work and can review the work before merge into the main branch. 

**Describe the solution you'd like**  
See above in the problem statement. 

**Additional context**  

see added repos in the problem statement

**Comment by FaGru3n** [comment]
Hi @ChristopherWinterZF,

_Info:_ for multible PR-reviewers, here in catenax ng on free-tier, <br> only usable with a paid GitHub Organisation like `Eclipse Tractus-X` also for multible assignees to issues
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/3bfbfe25-9f68-49e0-ade1-73c3e2627d31)

we could adapt a PR-Rule that someone in your team have to approve the PR before merging.
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/f8c41a7d-bf07-4b65-89a6-06918d160c89)

but issues in general are possible

**Comment by FaGru3n** [comment]
@ChristopherWinterZF issue were enabled for desired repos
> 1. https://github.com/catenax-ng/product-sustainability-kits
> 2. https://github.com/catenax-ng/product-sustainability-standardization
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/800636b0-632b-4b2a-9710-00ace326b482)

**Comment by FaGru3n** [comment]
@ChristopherWinterZF 

Please review 😉

**Comment by ChristopherWinterZF** [comment]
can be closed thx
