### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/sig-infra#207]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User:
https://github.com/santiagoejm

Vouching person: 
https://github.com/mkanal

Please also grant him access to this Catena-X Jira project: https://jira.catena-x.net/secure/RapidBoard.jspa?rapidView=379&projectKey=IRSDV

**Comment by SebastianBezold** [comment]
Hi @ds-jhartmann,
invitation sent. As always, team invites are handled by the teams maintainers. 
As soon as the invitation is accepted and Santiago could be added to the team, feel free to close this issue

**Comment by ds-jhartmann** [comment]
Thank you very much!
