### ISSUE TITLE
Request access to VeraCode

### ISSUE THREAD

**Issue by ds-lcapellino** [eclipse-tractusx/sig-infra#208]
Please report **undisclosed** or **confidential** vulnerabilities here: https://www.eclipse.org/security/

**Topics (Please mark an [x] to your Topic):**
- [ ] KICS
- [ ] Invicti
- [ ] GitGuardian
- [ ] Pentesting
- [ ] Security assessment (threat modeling, code reviews)
- [ ] Trivy
- [x] Veracode (initial setup, GitHub integration)
- [ ] Other

Hello Team, 

please enable my email lucas.capellino@doubleslash.de to use veracode. 
This is needed to work on the [tx-traceability-foss](https://github.com/catenax-ng/tx-traceability-foss) project. 

Thank you and best regards, 
Lucas

**Comment by the-tatanka** [comment]
Created user in Veracode. 
You will receive an email with a registration link.
