### ISSUE TITLE
Initialize `eclipse-tractusx.github.io.largefiles` for Git LFS 

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/sig-infra#215]
## Description

As described in #214, we are planning to create a new repository to host videos and other large files using [Git LFS](https://docs.github.com/en/repositories/working-with-files/managing-large-files/about-git-large-file-storage).

To use Git LFS, one needs to install it locally and [configure](https://docs.github.com/en/repositories/working-with-files/managing-large-files/configuring-git-large-file-storage) the repository to automatically track certain file types (by ending) for Git LFS.
An important part seems to be to include the ´.gitattributes` file with these settings, so contributions via fork are possible.

A documentation on how to work with Git LFS for our contributors is also necessary

**Comment by FaGru3n** [comment]
created and merged @SebastianBezold if you have some additions feel free :)
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io.largefiles/pull/7
