### ISSUE TITLE
Update Loki and fix retention policy

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/sig-infra#216]
The Log dashboards in our Grafana instances do not show anything anymore. 
They are indicating, that Loki ran out of space to write logs to.
A similar issue in the past was solved by just [increasing the Disk space](https://github.com/catenax-ng/k8s-cluster-stack/commit/684c01a2295f936da58f2a55ecd4d3aa0a524aef)
This could solve the issue in short term again, but further investigations on why Disk space isn't cleaned of old logs before running out of space should be done

**Comment by hzierer** [comment]
converted to regular task - will be done after QG checks

**Comment by hzierer** [comment]
retention policy will be fixed during next regular update of loki

**Comment by Siegfriedk** [comment]
won't do
