### ISSUE TITLE
Cannot sign in to Veracode

### ISSUE THREAD

**Issue by ds-mmaul** [eclipse-tractusx/sig-infra#217]
Please report **undisclosed** or **confidential** vulnerabilities here: https://www.eclipse.org/security/

**Topics (Please mark an [x] to your Topic):**
- [ ] KICS
- [ ] Invicti
- [ ] GitGuardian
- [ ] Pentesting
- [ ] Security assessment (threat modeling, code reviews)
- [ ] Trivy
- [x] Veracode (initial setup, GitHub integration)
- [ ] Other

Hello Team,
I already got access to Veracode about 4 months ago. With it, I logged in for the first time and set a password, which I also saved. Now I would like to sign in to Veracode again after a longer period of time. I get the error "Login not possible" 401 Unauthorised. Resetting the password or unlocking it didn't help either, because the e-mails from Veracode don't reach me. Could you help me here?

Thank you and best regards,
Martin

**Comment by the-tatanka** [comment]
We deleted inactive users a few weeks ago.
I created your acc.
You will receive an invitation mail.
