### ISSUE TITLE
Delete unused repositories demand-capacity-mgmt-backend/-frontend

### ISSUE THREAD

**Issue by AngelikaWittek** [eclipse-tractusx/sig-infra#223]
Please delete the following two repositories, as they are not used:

- demand-capacity-mgmt-backend
- demand-capacity-mgmt-frontend

Reason: The DMC Team decided to use only one (already existing repo): demand-capacity-mgmt.

Thanks,
Angelika

**Comment by almadigabor** [comment]
The repos got deleted
