### ISSUE TITLE
Quality Check Pipelines doesn't Work for Different Dependencies Filenames

### ISSUE THREAD

**Issue by mhellmeier** [eclipse-tractusx/sig-infra#230]
The Quality Check GitHub Action currently doesn't work for dependency files named differently than `DEPENDENCIES`. Similar to #228, it doesn't work for `DEPENDENCIES_FRONTEND` and `DEPENDENCIES_BACKEND` files.

**Example:**
The following repository has two dependencies files:
https://github.com/eclipse-tractusx/puris

The Quality Check pipeline based on the template fails with the following error:

> Failed! Guideline description: All repositories must follow specified files and folders structure.
> 	The check detected following mandatory files missing: DEPENDENCIES docs charts
> 	More infos: https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3

Source: https://github.com/eclipse-tractusx/puris/actions/runs/5880349374/job/15946439222?pr=18

CC: @SebastianBezold

**Comment by mhellmeier** [comment]
We tested it but even after the update, the Q-Gate workflow still fails, even if both DEPENDENCIES files are present:
https://github.com/eclipse-tractusx/puris

Can you please have a look into it again, @SebastianBezold & @tomaszbarwicki

**Comment by tomaszbarwicki** [comment]
Hi @mhellmeier, thanks for reaching out. Can you please provide the check result? 

I've run the latest version against puris repo and it doesn't complain about DEPENDENCIES any more, that's what I see:

```
7. Testing Quality Guideline: TRG 2.03 - Repo structure
Warning! Guideline description: All repositories must follow specified files and folders structure.
	The check detected following optional files missing: AUTHORS.md
	More infos: https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3
Failed! Guideline description: All repositories must follow specified files and folders structure.
	The check detected following mandatory files missing: docs, charts
	More infos: https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3 
```

**Comment by SebastianBezold** [comment]
Hmm I saw the PR comment first and [replied there](https://github.com/eclipse-tractusx/tractusx-quality-checks/pull/44#issuecomment-1700733425) :).
I think it could be related to the default version of the qualtiy-checks binary being stuck to the old, "non-fixed" version

**Comment by mhellmeier** [comment]
See, for example, this execution:
https://github.com/eclipse-tractusx/puris/actions/runs/6037040940/job/16385000174

It still outputs:
```
Failed! Guideline description: All repositories must follow specified files and folders structure.
	The check detected following mandatory files missing: DEPENDENCIES docs charts
	More infos: https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3
```

**Comment by tomaszbarwicki** [comment]
It seems that quite old version is used in your workflow:

![image](https://github.com/eclipse-tractusx/sig-infra/assets/7613143/ebedfdf9-02a0-4801-992a-ea38100f37d0)


@SebastianBezold:

@mhellmeier workflow is https://github.com/eclipse-tractusx/puris/actions/runs/6037040940/workflow
which uses https://github.com/eclipse-tractusx/sig-infra/blob/main/.github/workflows/reusable-quality-checks.yaml

and there is old 0.4 version eclipse-tractusx/tractusx-quality-checks@v0.4

**Comment by SebastianBezold** [comment]
I just bumped the version in the `reusable-quality-checks` workflow as well. 
After the current quality check phase is done, we really have to structure the process for upgrades of the checks better. Maybe having action and workflow at different places is not a good idea

**Comment by mhellmeier** [comment]
I just rerun the job, but it is still failing:
https://github.com/eclipse-tractusx/puris/actions/runs/6037040940/job/16414887253

It again uses the version `0.4`:
```
Run eclipse-tractusx/tractusx-quality-checks@v0.4
```

But as you can see, we defined to use the latest version on `main` without overwriting the version:
https://github.com/eclipse-tractusx/puris/actions/runs/6037040940/workflow

**Comment by tom-rm-meyer-ISST** [comment]
@SebastianBezold, we now have another issue in the downstream repositories when creating [PRs](https://github.com/eclipse-tractusx/puris/pull/29). We're unable to find version v0.7 that is not specifically specified. Please refer to this [run](https://github.com/eclipse-tractusx/puris/actions/runs/6070570678/job/16466884471?pr=29) for the following error:
"Error: Unable to resolve action `eclipse-tractusx/tractusx-quality-checks@v0.7`, unable to find version `v0.7`"

**Comment by tomaszbarwicki** [comment]
@SebastianBezold, perhaps we need to add a v0.7 tag which is missing I believe.

**Comment by tomaszbarwicki** [comment]
Issue fixed.
