### ISSUE TITLE
Read Access to Argo Beta

### ISSUE THREAD

**Issue by mzohaib-elastica** [eclipse-tractusx/sig-infra#232]
**Is your support request related to a problem? Please describe.**  
Please grant me read access to beta Argo https://argo.beta.demo.catena-x.net

**Describe the solution you'd like**  
Successful login via Github credentials (mzohaib17@gmail.com) to Beta Argo https://argo.beta.demo.catena-x.net/ with read access

**Additional context**  
None

**Comment by carslen** [comment]
Hi mzohaib-elastica,
to get access to the Catena-X Consortia environments you need to be a member of the GH org Catenax-NG and one of our GH teams. Afterwards you'll be able to access the ArgoCD instances and even Beta Argo with read permissions.

To get onboarded to the GH org catenax-ng please use this GH issue: [Invite Member to Catena-X organization](https://github.com/eclipse-tractusx/sig-infra/issues/new?assignees=&labels=support&projects=&template=support-invite-member-to-github-org.md&title=GitHub%3A+Invite+member+)

Please keep in mind, that you cannot invite yourself to the GH org, this needs to be done by a product owner of an existing Catena-X product/component.

**Comment by carslen** [comment]
Update:
with issue #222 an invite to our GH org have been sent. Please check your mailbox for the invite. Invite was sent aug. 14th and is only valid for 7 days, so you have to accept the invite today.

**Comment by carslen** [comment]
Invitation has been resent after it got invalid. You have now again 7 days to accept the invite before it gets invalid again.
