### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by Ruskyy** [eclipse-tractusx/sig-infra#235]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User: [sajaadem@gmail.com](https://github.com/sajaadem)

Vouching person: [Juergen Schuberthan](https://github.com/jschu1)
You should be able to contact him using your internal tooling set.

**Comment by carslen** [comment]
@jschu1 please give a thumbs up to onboard Saja.

**Comment by jschu1** [comment]
done

**Comment by carslen** [comment]
Invitation sent. @sajaadem has to accept the invite within the next 7 days, otherwize the invitation will expire. After the invitation has been accepted you can add Saja to your GH team.
