### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by egekorkan** [eclipse-tractusx/sig-infra#24]
new GitHub user: *GITHUB-USER-ID* @egekorkan

Question from us: *who can verify that the new user is a Member of Catena-X NG GitHub Organisation* - Christian Link - I am part of the Modular Production team under KIT Resiliency.

Vouching person: *Your_Product_Owner* Jan Christoph Wehrstedt is my Product Owner

**Comment by egekorkan** [comment]
This was not necessary actually, closing. Sorry for the confusion.

**Comment by FaGru3n** [comment]
Hi @egekorkan, so you don´t need an invite to https://catenax-ng.github.io/ ?

**Comment by egekorkan** [comment]
> Hi @egekorkan, so you don´t need an invite to https://catenax-ng.github.io/ ?

It seems that it is not needed. We are currently checking if it indeed makes sense. I will reopen this issue or create a new one if needed :)
