### ISSUE TITLE
tractus-x: New Github repository 'knowledge-agents-aas-bridge'

### ISSUE THREAD

**Issue by drcgjung** [eclipse-tractusx/sig-infra#240]
Repo name: knowledge-agents-aas-bridge

Purpose: should host a bridge between the existing 'knowledge-agents' APIs and the protocols provided by the Industrial Digital Twin Association's Asset Administration Shell program. so its not an agent, rather an alternative to DTR, SDE and other products implementing AAS. therefor it needs its own repo

Responsible: Knowledge agent Team Tom Buchert @drcgjung @JaneMcBrain

**Comment by carslen** [comment]
Just to be sure, you want a new repository in eclipse-tractusx, right?

**Comment by drcgjung** [comment]
yep. If that is created/initialised, I will request the tx-fork on catenax-ng ;-)

**Comment by carslen** [comment]
Repo creation process initiated, waiting for implementation of PR.

**Comment by carslen** [comment]
Repo has been created: https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge
I've also created the fork in catenax-ng GH org nd catenax-ng GH team product-knowledge got maintain permissions of the fork

**Comment by drcgjung** [comment]
Oh really great. You've done at once, that speeds things up.

Thx!!!
