### ISSUE TITLE
TGR 5 Helm

### ISSUE THREAD

**Issue by Bailonis** [eclipse-tractusx/sig-infra#242]
To give some context we have a small team, 2 backend and 2 front end developers, 1 Senior and 1 junior, on both cases.
Unfortunately, the backend senior developer leaved the team, and I do not have much experience on helm charts, and we have 2 problems:

1 - kubernetes was not finding the image
2 - With the old images we were not able to gain external access, it gave a timeout in the frontend

I would like someone that could help me in this situation.
Thanks in advance

**Comment by tomaszbarwicki** [comment]
Hey @Bailonis, thank you for reaching out to us. Would you mind provide a link to your repo so we can review the helm charts?

**Comment by Bailonis** [comment]
Hi there @tomaszbarwicki this is the repository link: https://github.com/catenax-ng/tx-demand-capacity-mgmt/tree/feat/DCMFOSS-53

We also received an advice from Sebastian Bezold, that youl be better have the helm charts this way:

<repo>
└───charts
    └───demand-capacity-management
        └───Chart.yaml
        └───templates
            └─── deployment-frontend.yaml
            └─── deployment-backend.yaml
            └─── service-frontend.yaml
            └─── service-backend.yaml

**Comment by tomaszbarwicki** [comment]
Yes, definitely that would be our recommendation to restructure your helm chart into Sebastian's suggestion. 

With regards to your image issues, it seems you are using wrong image references in the deployments:

FRONTEND:

 you have:
`ghcr.io/catenax-ng/demand-capacity-mgmt-frontend:latest`
  
correct one is:
`ghcr.io/catenax-ng/tx-demand-capacity-mgmt/demand-capacity-mgmt-frontend:latest`

BACKEND:

you have:
`ghcr.io/catenax-ng/tx-demand-capacity-mgmt-backend:1.16.0`
  
it seems there is no image with 1.16.0 tag published, I used latest with below link and seems to work:
`ghcr.io/catenax-ng/tx-demand-capacity-mgmt/demand-capacity-mgmt-backend:latest`

Hope that helps.

**Comment by Bailonis** [comment]
Thanks for the help!
I will try to restructure, and resolve the images references

**Comment by Bailonis** [comment]
So now I'm having this error:
![image](https://github.com/eclipse-tractusx/sig-infra/assets/72702458/580eac35-d125-48b5-bb2a-06bb84bb4208)
I went to the helpers.tpl, but is seems correct
I tried to include fullname: on the Values.yaml file on the frontend part, but also did not work

**Comment by Bailonis** [comment]
Frontend is blocked by this error:

![image](https://github.com/eclipse-tractusx/sig-infra/assets/72702458/0ae84f51-c702-4e35-9224-d644b42f7d3b)

Back end is Blocked by this error:

![image](https://github.com/eclipse-tractusx/sig-infra/assets/72702458/2a21eaca-1356-4c28-8f51-0d337eee89ff)

**Comment by tomaszbarwicki** [comment]
Hi @Bailonis, as advised on Teams please update your values.yaml with correct port number for readiness and liveness probes for backend. Try also deploy the chart to one of our environments available for you using ArgoCD. It did work for me, all pods were running.
Moreover as mentioned experiment a bit with memory allocation for frontend seems it uses it quickly. There is Grafana dashboard which can detail metrics of usage.

**Comment by Bailonis** [comment]
Issue resolved, thanks @tomaszbarwicki !
