### ISSUE TITLE
Enable Draft PRs for Repo

### ISSUE THREAD

**Issue by gerlitmcoding** [eclipse-tractusx/sig-infra#243]
Can you please enable Draft PRs for repo: https://github.com/catenax-ng/product-bpdm-documentation

![image](https://github.com/eclipse-tractusx/sig-infra/assets/101115470/2a447c2e-1036-40cb-b6d1-2e07db0e3e94)

**Comment by Siegfriedk** [comment]
Discussed it: If its not a lot of effort, pls add it

**Comment by tomaszbarwicki** [comment]
Hi @gerlitmcoding, according to https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests#draft-pull-requests Draft PRs are only available for public repositories in our org.
