### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by gerlitmcoding** [eclipse-tractusx/sig-infra#244]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User: phirabu

Vouching person: [rybtim ](https://github.com/rybtim) and [HeyHardy](https://github.com/HeyHardy)

**Comment by tomaszbarwicki** [comment]
Hi @gerlitmcoding, invite sent out. User can be added to respective teams after acceptance.

**Comment by gerlitmcoding** [comment]
![image](https://github.com/eclipse-tractusx/sig-infra/assets/101115470/5105ae2e-cebb-47f8-81b3-f4c3ef9e355b)

**Comment by tomaszbarwicki** [comment]
Did the user accept the invite?

**Comment by gerlitmcoding** [comment]
works now, thanks :)
