### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by Ruskyy** [eclipse-tractusx/sig-infra#245]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User: [diogo12246@gmail.com](https://github.com/Diogo12246 )

Vouching person: [Juergen Schuberthan](https://github.com/jschu1)
You should be able to contact him using your internal tooling set.

**Comment by jschu1** [comment]
agree - please welcome Diogo with access as requested - thanks!

**Comment by tomaszbarwicki** [comment]
Hi @Ruskyy, can you please confirm Diogo's email address is the one used with Eclipse Foundation? Normally emails are company related hence asking.

**Comment by Ruskyy** [comment]
@tomaszbarwicki Confirmed and its the same as Github

**Comment by tomaszbarwicki** [comment]
thanks @Ruskyy, Diogo's been invited, once accepted you can add him to respective teams.
