### ISSUE TITLE
New GitHub Secrets

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/sig-infra#248]
Could you please add two new GitHub secrets for the project https://github.com/catenax-ng/tx-item-relationship-service

secret name: ORG_IRS_OAUTH2_CLIENT_ID_DIL
secret value: please take the value from https://vault.demo.catena-x.net/ui/vault/secrets/traceability-irs/show/dil/keycloak/oauth2#clientId

secret name: ORG_IRS_OAUTH2_CLIENT_SECRET_DIL
secret value: please take the value from https://vault.demo.catena-x.net/ui/vault/secrets/traceability-irs/show/dil/keycloak/oauth2#clientSecret

Kind regards

**Comment by tomaszbarwicki** [comment]
hi @ds-jhartmann, secrets added, pls check on your side:



![Image](https://github.com/eclipse-tractusx/sig-infra/assets/7613143/7ad71278-786b-465a-b5b7-3a9079fec6fb)

**Comment by carslen** [comment]
Unfortunately the secret names indicate a org wide secret, but it was configured as repo secret. Are these secrets hard coded into your code? 

I'd prefer to rename the secrets to `IRS_OAUTH2_CLIENT_ID_DIL` and `IRS_OAUTH2_CLIENT_SECRET_DIL` to match the naming schema, @ds-jhartmann

**Comment by ds-jhartmann** [comment]
@carslen Oh, I was not aware of this implication. I used the naming convention for quite a while now, since sometime in the past it was communicated to do it like this. The secrets are already part of a workflow, but if you prefer to rename them, it is not a big effort to change the names

**Comment by carslen** [comment]
It would be great if we could align the secret names.

**Comment by ds-jhartmann** [comment]
@FaGru3n yes, I will update our workflows accordingly. Thank you!

**Comment by FaGru3n** [comment]
new repository secrets were created:
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/5a84e46b-78c0-4dd3-8796-15bac2d8b8f8)

**Comment by FaGru3n** [comment]
Hi @ds-jhartmann any updates and could we delete the "other" repo secrets?
😉

**Comment by ds-jhartmann** [comment]
Hi @FaGru3n, sorry about the silence, I completely forgot to update you. We adjusted our workflow and everything is working with the updated names. The old entries can be deleted. 
Thank you very much!

**Comment by FaGru3n** [comment]
Secrets were deleted issue can be closed
