### ISSUE TITLE
Aplication not passing VeraCode Rules due to Spring

### ISSUE THREAD

**Issue by Bailonis** [eclipse-tractusx/sig-infra#249]
Hi there!

We are having some issues with the VeraCode platform, the problem is that our scans are not passing the rules, this because it has some vulnerabilities  above medium, but all of this came from spring, is there any way to resolve this?
Our application is demand-capacity-mgmt-backend

![image](https://github.com/eclipse-tractusx/sig-infra/assets/72702458/21dd2f05-11dd-49b1-92a1-c031852b5499)

Thanks in advance

**Comment by Siegfriedk** [comment]
Hi @Bailonis ,

you actually need to upgrade your spring boot.

Pls get in touch with security @the-tatanka

**Comment by Bailonis** [comment]
@the-tatanka we are using spring-boot-starter-parent version 2.7.8.
Which version do you recommend?

**Comment by Bailonis** [comment]
I'm also receiving this message on my build whenever I try to do a veracode scan:

![image](https://github.com/eclipse-tractusx/sig-infra/assets/72702458/a705e6e1-da91-4c94-98e8-049d082ded86)

**Comment by the-tatanka** [comment]
I will look into it today

**Comment by the-tatanka** [comment]
we need to takle a few things...
I will create a PR and set you as reviewer.

**Comment by the-tatanka** [comment]
https://github.com/eclipse-tractusx/demand-capacity-mgmt/pull/14
