### ISSUE TITLE
Increased rights for grafana dev instance

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/sig-infra#25]
**Is your support request related to a problem? Please describe.**  
I'd like to add a custom dashboard for the portal team to Grafana and maybe some custom queries as well.

**Describe the solution you'd like**  
Just had a meeting with @Siegfriedk a possible solution would be to receive (temporarily) increased rights in the grafana dev instance to be able to add a custom dashboard.

**Additional context**  
I will setup a local instance of grafana and loki to test the dashboard before than creating a pr against the k8s-cluster-stack repo

**Comment by Siegfriedk** [comment]
Sry i think we are not yet too firm with our own new support process. We will do it next week.

**Comment by Phil91** [comment]
> Sry i think we are not yet too firm with our own new support process. We will do it next week.

No issue, thanks for the update :)

**Comment by hzierer** [comment]
Sry, for the late answer. I takes way longer than expected to change our current RBAC settings unfortunately.

So please open PRs the k8s-cluster-stack repo and we will add them as soon as possible. If you need help with the required ConfigMap, etc. just contact us.

**Comment by almadigabor** [comment]
Hi @Phil91! You can see an example [here ](https://github.com/catenax-ng/k8s-cluster-stack/commit/63fdcf1a9f05d3a0f48a3a008ee70082e945db57) on how to add a dashboard to the catena-x grafana instances. Just add the dashboard json file to the [dashboard](https://github.com/catenax-ng/k8s-cluster-stack/tree/main/apps/kube-prometheus-stack/dashboards) directory and reference it in the [dashboards.yaml](https://github.com/catenax-ng/k8s-cluster-stack/blob/main/apps/kube-prometheus-stack/templates/dashboards.yaml).

**Comment by Phil91** [comment]
@hzierer no issue, thanks for the response. I will do that.

@almadigabor perfect, thanks. I will create a PR for the additional dashboard.

@FaGru3n yes, absolutly fine, thanks a lot and sorry for the late response was off last week

**Comment by Phil91** [comment]
@almadigabor @FaGru3n i just created the [PR](https://github.com/catenax-ng/k8s-cluster-stack/pull/402).

**Comment by almadigabor** [comment]
Hi Phil! Some comments have been added to the PR, please check them.

**Comment by Phil91** [comment]
@almadigabor thanks, i resolved the issues

**Comment by FaGru3n** [comment]
PR was merged succesful https://github.com/catenax-ng/k8s-cluster-stack/pull/402

@Phil91  i would suggest that your ok with the result and close the issue?

**Comment by Phil91** [comment]
@FaGru3n sounds good 👍
