### ISSUE TITLE
Update GitHub Secrets

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/sig-infra#250]
Could you please update two GitHub secrets for the project https://github.com/catenax-ng/tx-item-relationship-service

secret name: KEYCLOAK_OAUTH2_CLIENT_ID
secret value: please take the value from https://vault.demo.catena-x.net/ui/vault/secrets/traceability-irs/show/dev/keycloak/oauth2#clientId

secret name: KEYCLOAK_OAUTH2_CLIENT_SECRET
secret value: please take the value from https://vault.demo.catena-x.net/ui/vault/secrets/traceability-irs/show/dev/keycloak/oauth2#clientSecret

Kind regards

**Comment by tomaszbarwicki** [comment]
hi @ds-jhartmann, secrets have been updated, please check on your end:



![Image](https://github.com/eclipse-tractusx/sig-infra/assets/7613143/5598e462-e9a0-4ccd-9bdd-f6038cc27ca4)

**Comment by ds-jhartmann** [comment]
Thanks, it's working 👍
