### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by drcgjung** [eclipse-tractusx/sig-infra#252]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User:
Martin0815bla

Vouching person(s): https://github.com/drcgjung, https://github.com/TomBuchertTSystems

**Comment by carslen** [comment]
GitHub user Martin0815bla has been invited to Catenax-ng org. The invitation is valid for 7 days as of now. After the invitation has been accepted, a maintainer of a GH Team can add the user to a GH Team.

**Comment by drcgjung** [comment]
worked as a breeze, thx much
