### ISSUE TITLE
GitHub: New Team 

### ISSUE THREAD

**Issue by Ruskyy** [eclipse-tractusx/sig-infra#26]
Product GitHub team name: 
cgi-dcm-foss

GitHub users to invite:
(https://github.com/Ruskyy)
(https://github.com/Bailonis)
(https://github.com/viniciusvieirah)

Maintainer of the new GitHub Team:
(https://github.com/Ruskyy)

**Comment by FaGru3n** [comment]
Hi @Ruskyy 
thanks for raising an issue.

we forgot the mention who can verify your request within Catena-X maybe a Product Owner?

**Comment by Ruskyy** [comment]
That would be 
Juergen Schuberthan
(juergen.schuberthan@bmw.de)

**Comment by FaGru3n** [comment]
> That would be Juergen Schuberthan
modified your comment helps me, but should not beeing known by all public members of github 😉  

will contact him in via our tooling set

**Comment by FaGru3n** [comment]
> will contact him in via our tooling set

or you also can guide him to use github, if he is not already here 👍🏼

**Comment by FaGru3n** [comment]
verification done @Ruskyy to which reository this team should be alligned?

**Comment by Ruskyy** [comment]
We were goin to request a new fork  from Tractus-X, with the name tx-dcm-backend.

**Comment by FaGru3n** [comment]
hi @Ruskyy invited you and the team members to GitHub Organisation Catena-X NG

**Comment by FaGru3n** [comment]
Info: End of consortia phase is comming so for further ways to contribute it is maybe a good way to become a committer within Eclipse Tractus-X  or at least a contributor.
More Info: https://eclipse-tractusx.github.io/docs/oss/getting-started

**Comment by Ruskyy** [comment]
Hi @FaGru3n, me and the rest of the team accepted the invite to the org.

**Comment by FaGru3n** [comment]
after approval from https://github.com/catenax-ng/product-onboarding/pull/31
will add you @Ruskyy as maintainer... for the team

**Comment by FaGru3n** [comment]
@Ruskyy  updated the gh-team for you now you can add all team-members by yourself.

https://github.com/orgs/catenax-ng/teams/product-cgi-dcm-foss

When you have requested an new repository whithin Eclipse Tractus-X with 
https://eclipse-tractusx.github.io/docs/oss/issues#eclipse-foundation-helpdesk

we can create a new fork in catena-x for your with other [issue template](https://github.com/eclipse-tractusx/sig-infra/issues/new?assignees=&labels=support&projects=&template=support-create-a-new-fork.md&title=GitHub%3A+New+fork+)
