### ISSUE TITLE
[TRG Check Dashboard]: Re-generate dashboard nightly

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/sig-infra#263]
Currently, the generation of the static HTML release guideline check dashboard (https://eclipse-tractusx.github.io/sig-release/) has to be triggered manually, to provide the GitHub PAT. The PAT is used, to face rate limiting issues.

A workflow should be added, or the existing one altered, so that the generation is triggered every day. 
We can check, if the rate-limit is no issue and do it without GitHub PAT, or ask the EF, if it would be possible to
get some kind of "org owner read-only" token, that is provided as secret for us to use

**Comment by FaGru3n** [comment]
Tested it with a less permissioned personal api token, and also worked.

raised a GitLab Issue against the Eclipse Foundation.
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3705

**Comment by FaGru3n** [comment]
Nightly Run worked: 
https://github.com/eclipse-tractusx/sig-release/actions/runs/6307042100

**Comment by FaGru3n** [comment]
PR for cleanup workflow https://github.com/eclipse-tractusx/sig-release/pull/54/files

**Comment by FaGru3n** [comment]
merged and deployed @tomaszbarwicki thanks for approval

**Comment by FaGru3n** [comment]
https://github.com/eclipse-tractusx/sig-release/blob/main/.github/workflows/build-and-deploy-dashboard.yaml

**Comment by FaGru3n** [comment]
https://github.com/eclipse-tractusx/sig-release/actions/runs/6451437507/job/17512067231
seems there are still some problems with api rate limiting

**Comment by FaGru3n** [comment]
Reopened https://github.com/eclipse-tractusx/sig-release/pull/57

**Comment by FaGru3n** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3705
reopend with the question for rate limiting

**Comment by FaGru3n** [comment]
Rate Limit problem also solved 
https://github.com/eclipse-tractusx/sig-release/blob/main/.github/workflows/build-and-deploy-dashboard.yaml

* manual run without a provided token
* manual run with a token if we are in rate limit
* and nightly run will also be fine
