### ISSUE TITLE
[TRG Check Dashboard]: Better highlight technical issues during checks

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/sig-infra#264]
There are a view products/repos, that do not show ("unhandled" ), or are showing without name.
There are log messages during the HTML generation run, but no hints are shown on the UI, what makes it difficult for viewers of the dashboard to understand these issues.

We should add general description on what the dashboard is showing and also highlight issues encountered when analyzing the repos

**Comment by tomaszbarwicki** [comment]
Currently dashboard UI doesn't support highlighting issues with the product name. However information is available in the log messages. Example for policy-hub: 

Merging metadata for https://github.com/eclipse-tractusx/policy-hub
No product for leading repo https://github.com/eclipse-tractusx/policy-hub yet. Adding empty one
Adding repository policy-hub (URL: https://github.com/eclipse-tractusx/policy-hub) to product  (Name: https://github.com/eclipse-tractusx/policy-hub)
Repo https://github.com/eclipse-tractusx/policy-hub is leading, addign name () + repo URL (https://github.com/eclipse-tractusx/policy-hub) to product


For policy-hub repository an issue was created to fix tractusx metadata file configuration: https://github.com/eclipse-tractusx/policy-hub/issues/4
