### ISSUE TITLE
[TRG Check Dashboard]: Show check error in a readable way

### ISSUE THREAD

**Issue by SebastianBezold** [eclipse-tractusx/sig-infra#265]
On failing guideline checks, the dashboard shows a tooltip with the error message. The message text is directly taken from our quality-checks library, which are optimized for CLI output.
Problems with the current setup are: 
- Often too long error message, which makes the tooltip hard to read
- line-breaks aren't working in the tooltip

**Comment by tomaszbarwicki** [comment]
Did small investigation and actually there is a way to create line-breaks within a tooltip, with option data-html="true" it is possible to use html tags for new line like <br>

 <a class="tooltipped" data-position="top" data-html="true" data-tooltip="hello <br> world!">

**Comment by SebastianBezold** [comment]
> Did small investigation and actually there is a way to create line-breaks within a tooltip, with option data-html="true" it is possible to use html tags for new line like  "\<br\>"
> 
>  \<a class="tooltipped" data-position="top" data-html="true" data-tooltip="hello \<br\> world!"\>
> 
> 

Oh that would be awesome! If that is working, we should do it right away. We can still check, if we should adapt the output afterwards

**Comment by SebastianBezold** [comment]
Hi @tomaszbarwicki, the two PRs linked to this issue are already merged. It also seems like the nice error messages are already live. From my point of view, we can close this issue. What do you think?
