### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by gerlitmcoding** [eclipse-tractusx/sig-infra#27]
new GitHub user: https://github.com/Sebastian-Wurm

Question from us: 

hardy.heyde@audi.de

Vouching person: 
hardy.heyde@audi.de

**Comment by Siegfriedk** [comment]
He is invited. pls confirm

**Comment by FaGru3n** [comment]
Hi @gerlitmcoding ,

after acepted invitation you can add  https://github.com/Sebastian-Wurm to the desired gh-team and verify and close this issue.

👍
