### ISSUE TITLE
GitHub User Issues

### ISSUE THREAD

**Issue by ds-mwesener** [eclipse-tractusx/sig-infra#273]
**Is your support request related to a problem? Please describe.**  
Hi, today I was logged out in github and due to suspicious activity it asked me to reset my password of github two times. Afterwards I was not able anymore to run github actions. Additionally I still can merge pull requests, but the actions will not run when I click merge.

**Comment by FaGru3n** [comment]
Hi @ds-mwesener  i would suggest problem is resolved after unmarking your GitHub Account right?
