### ISSUE TITLE
Replay Release v1.9.8 on knowledge-agents-edc

### ISSUE THREAD

**Issue by drcgjung** [eclipse-tractusx/sig-infra#274]
**Is your support request related to a problem? Please describe.**  

https://github.com/eclipse-tractusx/knowledge-agents-edc/issues/46 has been in principle solved by https://github.com/eclipse-tractusx/knowledge-agents-edc/pull/48

Unfortunately, the relevant release workflows fixing the binary artifacts only start on "tagging" not "merging". In addition, the 
target maven repo cannot be published to until the old packages have been swiped.

**Describe the solution you'd like**  

Please delete the following packages

https://github.com/eclipse-tractusx/knowledge-agents-edc/packages/1926622
https://github.com/eclipse-tractusx/knowledge-agents-edc/packages/1926623
https://github.com/eclipse-tractusx/knowledge-agents-edc/packages/1928959
https://github.com/eclipse-tractusx/knowledge-agents-edc/packages/1928958
https://github.com/eclipse-tractusx/knowledge-agents-edc/packages/1928960
https://github.com/eclipse-tractusx/knowledge-agents-edc/packages/1928961

Please then
- move the [release v1.9.8](https://github.com/eclipse-tractusx/knowledge-agents-edc/releases/tag/v1.9.8) to a new (temporary) tag not starting with "v", like "temp" and pointing to branch https://github.com/eclipse-tractusx/knowledge-agents-edc/tree/release/1.9.8
- delete the actual v1.9.8 tag (not the release) 
- move the [release v1.9.8](https://github.com/eclipse-tractusx/knowledge-agents-edc/releases/tag/v1.9.8) back to the "new" tag v1.9.8 pointing to branch https://github.com/eclipse-tractusx/knowledge-agents-edc/tree/release/1.9.8
- delete the temporary "temp" tag  

**Additional context**  

After v1.9.8 tag has been reinstalled, the publish workflows (especially: dockerhub) should start.
An alternative to the above retagging approach could be to use a git client to enforce the reset of the tag to c84ebe450f0e2df9950251125ed30b798f4e9dfc

**Comment by carslen** [comment]
FIrst of all, we're not able to remove released packaged in eclipse-tractusx GH org, due to limitations of the Eclipse Foundation. 

Just to get it right, are the mentioned packages part of the release 1.9.8, which is part of the recent Eclipse TractusX stable 3.2/23.09?

In my understanding, if defective packages has been released/published, fix the issue(s) and publish a new versions of these packages and add a note to the CHANGELOG to not use the previous ones. Or are there any other reasons why you want these packages to be deleted?

**Comment by drcgjung** [comment]
Carsten, thanks much for caring.

> FIrst of all, we're not able to remove released packaged in eclipse-tractusx GH org, due to limitations of the Eclipse Foundation.

alright, I did not know that.

> 
> Just to get it right, are the mentioned packages part of the release 1.9.8, which is part of the recent Eclipse TractusX stable 3.2/23.09?

yes.

> In my understanding, if defective packages has been released/published, fix the issue(s) and publish a new versions of these packages and add a note to the CHANGELOG to not use the previous ones. Or are there any other reasons why you want these packages to be deleted?

fortunately it's not that bad. The packages themselves are completely fine, they only did not find their way into the docker images (due to a lacking build-arg and an "empty" COPY which went through without error).

So in the end it's the problem of our current build.yaml workflow that it wants to publish both maven and docker artifacts in one run (and skips the latter if the first runs into permission denied's).

So I'll try to improve the workflow instead such that it can be manually dispatched for that purpose.

CGJ
