### ISSUE TITLE
Update Kube-Prometheus-Stack

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/sig-infra#275]
update Kube-Prometheus-Stack to current version 51.0.2

**Comment by hzierer** [comment]
devsecops-testing done

**Comment by hzierer** [comment]
done on all remaining envs

**Comment by FaGru3n** [comment]
waiting for feedback from the users 😉 

version match on:

- [x] dev
- [x] beta
- [x] core
- [x] int
- [x] stable
- [x] devsecopstesting

**Comment by almadigabor** [comment]
Tested, looks OK.
