### ISSUE TITLE
The HTTP application routing add-on (preview) for Azure Kubernetes Service (AKS) will be retired on 3 March 2025. 

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#278]
The HTTP application routing add-on is only supported up to Kubernetes version 1.22, which has already retired, according to the [Azure Kubernetes Service support policy](https://learn.microsoft.com/azure/aks/supported-kubernetes-versions?tabs=azure-cli). 
Required action 
Transition your ingresses to use the [web application routing add-on](https://aka.ms/aks/docs/app-routing) for a better experience. To avoid service disruptions, please follow our [instructions to migrate](https://aka.ms/migrate-to-app-routing) to a replacement product before 3 March 2025. 
We encourage you to transition your ingresses to the web application routing add-on prior to the retirement date. The web application routing add-on provides monitoring through Prometheus metrics, Azure DNS zone management, and SSL termination through certificates stored in Azure Key Vault.

--> Only found this option in AKS INT/ Hotel-Budapest
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/b15d7d11-17c2-436d-8e80-a2655932cd22)

Just a remarker ticket for the future

**Comment by SebastianBezold** [comment]
We do not use this plugin, since we do our own ingress. Since this issue is quite old, I would close it. 
If it will become relevant again, we can of course re-open it
