### ISSUE TITLE
Fix Lokis more and more often error 500's

### ISSUE THREAD

**Issue by hzierer** [eclipse-tractusx/sig-infra#280]
Loki shows more and more often error 500's in the grafana panels querying it.
`Status: 500. Message: too many outstanding requests`

We should try to optimize its settings, for starters e.g. as suggested [here](https://github.com/grafana/loki/issues/5123)

**Comment by FaGru3n** [comment]
Could be closed... @Siegfriedk little hint if you close directly it will automatically move to done.
