### ISSUE TITLE
Goldilocks for resource settings recommendations

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#284]
Hi,

[Goldilocks](https://github.com/FairwindsOps/goldilocks) could be a quite useful tool to get recommendations about resource settings for all teams, at least when running on the int cluster.

I'd like to test its setup with the following helm chart on dev cluster:
https://github.com/catenax-ng/product-portal-tools/blob/chore/goldilocks/charts/goldilocks/Chart.yaml

And if it works move to int.

Unfortunately my argo project doesn't have sufficient permissions...
Could you please support the test by setting it up with proper permissions on the dev cluster using the following config:
https://github.com/catenax-ng/product-portal-tools/blob/chore/goldilocks/charts/goldilocks/argocd/appsetup-dev.yaml
https://github.com/catenax-ng/product-portal-tools/blob/chore/goldilocks/charts/goldilocks/envs/values-dev.yaml

Thanks!

**Comment by almadigabor** [comment]
Hi @evegufy! Just an idea as I haven't tested it yet. Currently you don't have the permission to create ClusterRole and ClusterRoleBinding objects in your project. Maybe in the helm chart you could set the `controller.rbac` and `dashboard.rbac` to false and then create your own Role and RoleBinding objects for the dashboard and controller. This way you would be able to monitor resources in the product-portal namespace.

**Comment by almadigabor** [comment]
Deployed Goldilocks on dev and int environment for portal with @evegufy. Closing this issue for now. Might revisit later for a wider deployment including all products.
