### ISSUE TITLE
Stable cluster cannot create application from configured project repository

### ISSUE THREAD

**Issue by ds-ext-sceronik** [eclipse-tractusx/sig-infra#286]
**Is your support request related to a problem? Please describe.**  

We cannot create application on stable cluster with provided project configuration. 
https://argo.stable.demo.catena-x.net

<img width="351" alt="image" src="https://github.com/eclipse-tractusx/sig-infra/assets/132563681/60f0192a-130c-4365-8ad6-f1dd5f7b4c29">

**Describe the solution you'd like**  
I would like to be able to create applications from all subfolders inside the charts folder in repositories
https://eclipse-tractusx.github.io
https://github.com/catenax-ng/tx-traceability-foss

we also have required support deployments for providing own data in branch helm-environments on 
https://github.com/catenax-ng/tx-traceability-foss
so we need to be able to create apps from branches for operation purpouses

**Additional context**  
on int environment I noticed there is wildcard "*" used for repositories in project. 
on stable it is specific path: https://eclipse-tractusx.github.io/charts/dev
which is not existent

**Comment by almadigabor** [comment]
Hi @ds-ext-sceronik! On stable environment we only allow teams to deploy apps from the helm repository where the artefacts where pushed during release 3.2. We announced this in the Office Hour, mailing list and also you can read more about it in this [teams channel](https://teams.microsoft.com/l/message/19:9a3c4a05a3514d07b973c13e7b468709@thread.tacv2/1694764464843?tenantId=1ad22c6d-2f08-4f05-a0ba-e17f6ce88380&groupId=17b1a2dc-67fb-4a49-a2ed-dd1344321439&parentMessageId=1694764464843&teamName=Communities%20of%20Practices&channelName=CX%20-%20CoP%20DevSecOps&createdTime=1694764464843&allowXTenantAccess=false), where they describe in detail how the deployment can be achieved.

**Comment by ds-ext-sceronik** [comment]
ok can we atleast change url to be  https://eclipse-tractusx.github.io/charts 
rather than  https://eclipse-tractusx.github.io/charts/dev ?? 
otherways we wont be able to create application from release

**Comment by ds-ext-sceronik** [comment]
Ok seems I have all In described process on provided chat . thank You for pointing me to right direction @almadigabor  :)
