### ISSUE TITLE
GitHub: New repository 

### ISSUE THREAD

**Issue by Ruskyy** [eclipse-tractusx/sig-infra#29]
Required information:
- Details to your GitHub repository: tx-dcm-backend
- Details to GitHub team to grant access: product-cgi-dcm-foss

**Comment by Siegfriedk** [comment]
As mentioned in the other ticket: we will need to wait for the final name

**Comment by carslen** [comment]
Open EF Helpdesk Ticket: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3167

**Comment by carslen** [comment]
Repositories have been created by EF Helpdesk:
- https://github.com/eclipse-tractusx/demand-capacity-mgmt
- https://github.com/eclipse-tractusx/demand-capacity-mgmt-frontend
- https://github.com/eclipse-tractusx/demand-capacity-mgmt-backend

I'll create the forks of these repositories not in out Catenax-NG GH Org.

**Comment by carslen** [comment]
Initialized repositories to be able to create forks of them.
