### ISSUE TITLE
Enablement of Community functionality for IRS Repo

### ISSUE THREAD

**Issue by jzbmw** [eclipse-tractusx/sig-infra#290]
**Is your support request related to a problem? Please describe.**  
I would like to use the communication functionalities for the Item Relationship Service Repo

**Describe the solution you'd like**  
enable this functionality

**Additional context**

**Comment by tomaszbarwicki** [comment]
Hi @jzbmw, just wanted to clarify your request, is that Discussion feature which you are looking for?

**Comment by jzbmw** [comment]
Yes it is.

**Comment by tomaszbarwicki** [comment]
@jzbmw functionality has been added, pls verify.

**Comment by jzbmw** [comment]
verified
