### ISSUE TITLE
Create new branch for testing helm charts

### ISSUE THREAD

**Issue by Bailonis** [eclipse-tractusx/sig-infra#292]
Hi there!

If possible could anyone open a new branch on this project https://github.com/eclipse-tractusx/demand-capacity-mgmt?

This because I want to test the deployment of the helm charts on docker.io.

I want to merge this beanch to there: https://github.com/catenax-ng/tx-demand-capacity-mgmt/tree/feat/workflows

Thanks in advance.

**Comment by tomaszbarwicki** [comment]
@Bailonis branch created: https://github.com/eclipse-tractusx/demand-capacity-mgmt/tree/feat/workflows

let me know if that helps

**Comment by Bailonis** [comment]
Thanks!

it was this I wanted!
