### ISSUE TITLE
GitHub: Remove or Archive Repositories `tx-puris-frontend` and `tx-puris-backend`

### ISSUE THREAD

**Issue by mhellmeier** [eclipse-tractusx/sig-infra#296]
Please remove or archive the following two repositories:
https://github.com/catenax-ng/tx-puris-frontend/tree/main
https://github.com/catenax-ng/tx-puris-backend/tree/main

The upstream repos are also archived, and a hint is set at the beginning of each `README.md`.

The repos should be deleted/archived because they are merged in one single repository:
https://github.com/eclipse-tractusx/puris

Validation / approved by: @tom-rm-meyer-ISST and @mhellmeier

**Comment by hzierer** [comment]
Repos have been archived.
