### ISSUE TITLE
GitHub: New repository 

### ISSUE THREAD

**Issue by adityagajbhiye9** [eclipse-tractusx/sig-infra#297]
Required information:
- Details to your GitHub repository: 
repo name : Simple-data-exchanger-backend
repo name : Simple-data-exchanger-frontend
**repo will be private and please fork repo from https://github.com/catenax-ng/tx-managed-simple-data-exchanger-backend & https://github.com/catenax-ng/tx-managed-simple-data-exchanger-frontend respectively**

- Details to GitHub team to grant access: product-dft 

validation / approved by: MehranRoshandel

Thanks in advance.

**Comment by adityagajbhiye9** [comment]
Hi @hzierer 
I am checking with team and confirm.

**Comment by adityagajbhiye9** [comment]
@hzierer  Please create empty private repos, don't need to fork from  above mention repository.

**Comment by adityagajbhiye9** [comment]
@hzierer any update on above request.

**Comment by adityagajbhiye9** [comment]
@hzierer any update on above request. Please create the above repos so that we can start pushing code.

**Comment by SebastianBezold** [comment]
Hi @adityagajbhiye9,

looking at the comment history, I'm not sure if I get your request.
What are you going to implement in this repo?
If it is related to the simple-data-exchanger, you should do that in the existing fork.
If your contributions include company IP or anything similar, that would require it to be private, you should think about doing it outside the catenax-ng organization.

Could you please clarify what this repo will be used for?

**Comment by adityagajbhiye9** [comment]
Sure, I am discussing with team.

**Comment by SebastianBezold** [comment]
Hi @adityagajbhiye9, any update on this?

**Comment by adityagajbhiye9** [comment]
Please close this issue. We have change the course of action.

**Comment by SebastianBezold** [comment]
ok thanks for the update
