### ISSUE TITLE
ArgoCD application access

### ISSUE THREAD

**Issue by adityagajbhiye9** [eclipse-tractusx/sig-infra#298]
**Is your support request related to a problem? Please describe.**  
- I don't have the application access for product essential in argo cd.

**Describe the solution you'd like**  
I would like to have access to create job and view jobs logs for trouble shooting. 
env : Int
 github user id : adityagajbhiye9

**Comment by hzierer** [comment]
@MehranRoshandel can you please approve

**Comment by MehranRoshandel** [comment]
Yes, Please enable Aditya to access.
thanks

**Comment by hzierer** [comment]
user added to appropriate groups
