### ISSUE TITLE
Document Postgres upgrade process of bitnami helm chart

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/sig-infra#302]
Need to document in the Tractus-X website and also in the mailing list how the Bitnami Postgres database can be upgraded from one major version to another without data loss. Some initial thoughts can be found [here](https://github.com/eclipse-tractusx/sig-infra/issues/271#issuecomment-1756184959), but it has been already streamlined like no kubectl access is needed, rather running the commands in the argocd pod terminal works too.

**Comment by Siegfriedk** [comment]
won't continue/done
