### ISSUE TITLE
GitHub: New fork 

### ISSUE THREAD

**Issue by Ruskyy** [eclipse-tractusx/sig-infra#31]
repository name within Tractus-X Organisation: 
tx-dcm-backend

repository name within Catena-X NG Organisation: 
tx-dcm-backend

GitHub team to grant access: 
product-cgi-dcm-foss

**Comment by carslen** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3167

**Comment by Ruskyy** [comment]
Updating this ticket with a follow up from EF Helpdesk.

Our repositories should be updated to:
tx-demand-capacity-mgmt-frontend
tx-demand-capacity-mgmt-backend

**Comment by Ruskyy** [comment]
Repositories Renamed. [EF Ticket](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3167)

**Comment by carslen** [comment]
Forks have been created:
- https://github.com/catenax-ng/tx-demand-capacity-mgmt
- https://github.com/catenax-ng/tx-demand-capacity-mgmt-frontend
- https://github.com/catenax-ng/tx-demand-capacity-mgmt-backend

Catenax-NG GH team product-cgi-dcm-foss has been granted maintainer permissions to these forks.

Closes #29
