### ISSUE TITLE
Repository : bpdm-certificate-management

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/sig-infra#310]
Repository name: bpdm-certificate-management
Purpose: implementation of the reference implementation for business partner certificates
Responsible: @SujitMBRDI , @nicoprow 

Thanks!

**Comment by danielmiehle** [comment]
👍

**Comment by SebastianBezold** [comment]
Hi @maximilianong,

should this repo first be set up in catenax-ng or directly in eclipse-tractusx?

**Comment by maximilianong** [comment]
Hi @SebastianBezold - directly in Eclipse-TractusX. Thanks.

**Comment by SebastianBezold** [comment]
PR to create the repo via otterdog created: https://github.com/eclipse-tractusx/.eclipsefdn/pull/37
Will be reviewed and merged by EF. 
@danielmiehle you might be asked for approval on the PR as Project Lead

**Comment by SebastianBezold** [comment]
Repo has been created: https://github.com/eclipse-tractusx/bpdm-certificate-management.

@nicoprow and @SujitMBRDI, can you work directly on that repo, or do you need a fork in -ng? 
You can of course also fork it somewhere else

**Comment by maximilianong** [comment]
Thanks @SebastianBezold 

Do I need special permissions to assign issues and set labels to issues? 
In other repositories Im able to do it.

**Comment by SebastianBezold** [comment]
Hi @maximilianong, I could not find any specifics so far, so from my point of view, you should be able to assign the issue as committer. I would close this issue for now, but keep the assigning topic in the back of my head.

As a reminder. Everyone involved, please keep track on the legal docs initialization of the repo.
This should not be a lot of effort, but is essential.

**Comment by maximilianong** [comment]
Hi @SebastianBezold - I don't know what happened but now it works :D Maybe it just took some time.
