### ISSUE TITLE
Create portal-iam namespace on INT cluster

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#313]
Please create portal-iam namespace on INT cluster as it's already available on the DEV cluster.
Needed for blue/green deployment.

**Comment by SebastianBezold** [comment]
The `vault-secret` was never added (via code) to the IAM namespaces. I added them via [this commit](https://github.com/catenax-ng/product-onboarding/commit/cf2455e61fcde072cc28032898e82ec56f5f5293) and synced to our clusters. 
On INT is was actually missing. On DEV for example, there where no changes on sync. I can only guess, that they might have been added manually before and are now also managed via Argo CD.
