### ISSUE TITLE
GitHub: Invite member Matthias Fischer

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-infra#314]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User:

https://github.com/dsmf

Vouching person: 
ds-mkanal

**Comment by SebastianBezold** [comment]
HI @mkanal, just a reminder, @dsmf did not yet accept the invite. As far as i remember, invitations expire after 1 week

**Comment by SebastianBezold** [comment]
Closing the issue, since invitation is accepted.
