### ISSUE TITLE
Update Kyverno to v1.10 (Helm Chart v3.0)

### ISSUE THREAD

**Issue by carslen** [eclipse-tractusx/sig-infra#315]
Kyverno needs to be upgraded to implement #105. Kyverno introduced breaking changes with version (AppVersion/Helm Chart Version) 1.10.0/3.0.0 and documentation is based on v1.10.0.

### Current deployed Kyverno Version in our envs
- Helm Chart Version: 2.6.0
- Kyverno Version: v1.8.0

### Resources
- [Release Notes Kyverno v1.10.0](https://github.com/kyverno/kyverno/releases/tag/v1.10.0)
- [Helm Chart migration guide](https://github.com/kyverno/kyverno/blob/release-1.10/charts/kyverno/README.md#migrating-from-v2-to-v3)
- [New Helm values with Chart version v3](https://github.com/kyverno/kyverno/blob/release-1.10/charts/kyverno/README.md#new-chart-values)
- [Upgrade option 1 - Uninstallation and Reinstallation](https://github.com/kyverno/kyverno/blob/release-1.10/charts/kyverno/README.md#option-1---uninstallation-and-reinstallation)
- [Upgrade option 2 - Scale to Zero](https://github.com/kyverno/kyverno/blob/release-1.10/charts/kyverno/README.md#option-2---scale-to-zero)

As we've not yet deployed any policies we'll follow the recommended upgrade option 1 (uninstall - reinstall).

**Comment by carslen** [comment]
I'll first remove and reinstall Kyverno on our devsecop-testing cluster.

**Comment by carslen** [comment]
- Deleted Kyverno ArgoCD Application on `CORE` ArgoCD
- Manually removed CRDs deployed with Kyverno Helm Chart
    - `admissionreports.kyverno.io`
    - `backgroundscanreports.kyverno.io`
    - `clusteradmissionreports.kyverno.io`
    - `clusterbackgroundscanreports.kyverno.io`
    - `clusterpolicies.kyverno.io`
    - `clusterpolicyreports.wgpolicyk8s.io`
    - `generaterequests.kyverno.io`
    - `policies.kyverno.io`
    - `policyreports.wgpolicyk8s.io`
    - `updaterequests.kyverno.io`

Next up: Update k8s-cluster-stack Helm Chart for Kyverno installation.

**Comment by carslen** [comment]
All Kyverno instances upgraded to Helm Chart v3.05

**Comment by tomaszbarwicki** [comment]
@carslen I tried to use Kyverno on the devsecops cluster but seems it's not operational. ArgoCD shows it failed to apply HA change.

**Comment by carslen** [comment]
> @carslen I tried to use Kyverno on the devsecops cluster but seems it's not operational. ArgoCD shows it failed to apply HA change.

catenax-ng/k8s-cluster-stack#431

**Comment by carslen** [comment]
HA deployment on all environments done.

**Comment by SebastianBezold** [comment]
Dashboards available. LGTM :)
