### ISSUE TITLE
Update TRG 2.5 with a new metadata option

### ISSUE THREAD

**Issue by tomaszbarwicki** [eclipse-tractusx/sig-infra#317]
Describe repoCategory metadata option

**Comment by SebastianBezold** [comment]
Hi @tomaszbarwicki,

just as hint: I started writing docs for our tractusx-quality-checks and added a specific file, just for describing the `.tractusx` file with all it's options. You can see it in this (as of now) open PR here: https://github.com/eclipse-tractusx/tractusx-quality-checks/pull/63/files#diff-1ffcab2b1cd32bf31edbb7efd71cfa8c827049809ec137d74dbc245cea6007e0

Maybe we can try to keep this docs up-to-date and reference it from the release guidelines. In my opinion, it would be easier to keep it up-to-date in the repository that introduces the changes.

**Comment by tomaszbarwicki** [comment]
@SebastianBezold I like the idea as we discussed in the call, shall I close the TRG update PR in this case?

**Comment by SebastianBezold** [comment]
I think we still need it, but could update to link to the docs

**Comment by FaGru3n** [comment]
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/470

**Comment by FaGru3n** [comment]
done
