### ISSUE TITLE
Argo CD: 'delete app' doesn't remove anything from k8s cluster

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#32]
**Is your support request related to a problem? Please describe.**  
I observed the following today on the beta cluster: When deleting the apps 'portal', 'centralidp' and 'sharedidp' in argocd, there appears to be nothing deleted from the k8s cluster. The apps even appear so be still reachable via ingress...
The only result of deleting the apps appears to be that they aren't visible anymore in argocd, no effect on the cluster.
I observed this issue on other clusters already in the aftermath of the last argocd upgrade (A1ODT-1333).
Then I figured this issue, of not deleting resources, 'only' affects the pvc, today it appears to affect every resource.

**Describe the solution you'd like** 
'delete app' does delete everything app related from k8s cluster (or at least everything with the exception of the pvc which would need to be deleted manually before deleting the app in argo).

**Comment by carslen** [comment]
Clean up in Namespace has been finished (incl. PVCs) as discussed @evegufy 

```shell
$ k -n product-portal get all
No resources found in product-portal namespace.
```
