### ISSUE TITLE
New repository for the Quality FOSS App

### ISSUE THREAD

**Issue by JulianSchererZF** [eclipse-tractusx/sig-infra#326]
Repo name: quality-foss

Purpose: FOSS app for the use case quality

Responsible: @JulianSchererZF (PO), @TobiasKampsZF (as Support)

**Comment by JulianSchererZF** [comment]
Hi @SebastianBezold,

We don't need any preparation in the catenax-ng anymore, therefore we need a eclipse-tractusx repo.
 How is the naming handeled by other FOSS implementations of use cases? Because I saw for example that the tracebility use case implementation repository is named "traceability-foss".
 Maybe we can think of quality-implementation or something like that because for now we plan to start with the Early Warning features defined in the use case but in the future we want to extend the app with for exmaple root cause analysis as well.

**Comment by SebastianBezold** [comment]
Hi @JulianSchererZF,

oh yes you are right, maybe we should have discussed that as well. But in the end, it's still all FOSS as soon as you talk about implementation in eclipse-tractusx. I guess the -foss suffix is a "relic" from consortium times, where we distinguished between FOSS and COTS.

@danielmiehle, @giterrific or @Siegfriedk , do you have a good suggestion as Tractus-X project leads? I think we do not have docs for naming conventions yet right?

**Comment by giterrific** [comment]
foss as a pre- or postfix is a relic of the past, we should use it for new repos like @SebastianBezold mentioned, since obviously everything is foss in Tx.

All our products are currently implementations, so that isnt really differentiating either.

In CX i always noticed people talking about 'quality alerts', would that be a generalizing topic name for uses looking forward?

**Comment by Siegfriedk** [comment]
Urgh good point. Lets get rid of those suffix/prefix things. We just had a similiar discussion regarding the helm chart name too

**Comment by SebastianBezold** [comment]
Hi @JulianSchererZF,

could you and your team talk about a better name already? I think only "quality" is too generic, so what about "quality-alerts" or "quality-dashboard"? I guess you will build a webapp, right?

**Comment by TobiasKampsZF** [comment]
Hi @SebastianBezold,
Julian is not available this week, but he asked me to help out if necessary.
Yes it's going to be a webapp, but also with a backend that connects with Apache Spark.
We didn't have time to discuss a name, and now its vacation week... ;-)
Julian objected to "quality-alerts", but maybe quality-dashboard could work.
I was thinking about "quality-manager", not sure which is better. What do you think?

**Comment by SebastianBezold** [comment]
Hi @TobiasKampsZF,
thanks for jumping in. In my opinion, both could work. Maybe more food for thought :)
Is it maybe about quality incidents or assurance?

I mean, we can also rename the repository if it will only get clearer in the future, but this always comes with some reviewing effort on Eclipse Foundation side, that we want to avoid if possible. 

@giterrific or @danielmiehle do you have additional suggestions?

**Comment by TobiasKampsZF** [comment]
Hello @SebastianBezold,
when we agree on a name, how long will it take until the repository is ready?
And are there more points about it that need to be clarified?

**Comment by SebastianBezold** [comment]
Hi @TobiasKampsZF,

this is usually done the same day. It takes me 5 minutes to prepare the PR and then we wait for the Eclipse Foundation Team to review the request. This was also quite fast the last times we created new repos.

We only need to find a good name for the repo and then you are good to go. 
Best is always to start with the legal docs asap

**Comment by TobiasKampsZF** [comment]
Hi @SebastianBezold,
ok thanks for the info, I believe in this case we can wait until Monday, so the absent colleagues can also vote on the name.
Currently "quality-dashboard" is popular.

**Comment by TobiasKampsZF** [comment]
Hi @SebastianBezold,
out team agreed on "quality-dashboard" for the repository, could it be set up now?
Thank you for the support!

**Comment by SebastianBezold** [comment]
HI @TobiasKampsZF,

yes that name is fine I guess. I'll prepare the PR and keep you up-to-date

**Comment by SebastianBezold** [comment]
PR for repo creation available: https://github.com/eclipse-tractusx/.eclipsefdn/pull/40

Next steps: Eclipse Foundation staff will review the request. Potential confirmation from our project leads necessary

**Comment by SebastianBezold** [comment]
Hi @TobiasKampsZF and @JulianSchererZF,

The repo creation PR got merged and the repo is present: https://github.com/eclipse-tractusx/quality-dashboard

please ensure, that you do at least the legal documentation as soon as possible.
