### ISSUE TITLE
New Tractus-X project contributor (Simone from SLDT)

### ISSUE THREAD

**Issue by bs-sili** [eclipse-tractusx/sig-infra#331]
Hi all,

I would need the project contributor role so that I an able to work with the issues mainly related to the QGs.
Many thanks in advance!

Best regards
Simone

## Neccessary Information

Email address to add: external.simone.lindner@bosch.com
Committers, that could take over: 
@tunacicek , @agg3fe 

Please make sure, that you accept the invitation you recieve from GitHub, after you have been added as project contributor.

**Comment by tomaszbarwicki** [comment]
Hi @bs-sili, you've been added.

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki,
thank you for adding me. I just received the invitation from GitHub. :-)

**Comment by bs-sili** [comment]
Hi @tomaszbarwicki,
I just tested it, it is working fine. So if you don't mind I will close this issue.
