### ISSUE TITLE
GitHub: New fork of policy-hub

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/sig-infra#335]
repository name within Tractus-X Organisation: 
[policy-hub](https://github.com/eclipse-tractusx/policy-hub)

repository name within Catena-X NG Organisation: 
tx-policy-hub

GitHub team to grant access: 
If possible exactly like [tx-portal-backend](https://github.com/catenax-ng/tx-portal-backend/settings/access) but with a new team for the policy-hub, since it's possible that portal-team will not develop it the whole time.

Thanks in advance

/cc
@evegufy

**Comment by SebastianBezold** [comment]
Hi @Phil91,

I created the fork and granted `maintain` access for the portal team.
I can also create a new team if necessary and add you as team maintainer. 
The you could add as many other colleagues as you like. Alternatively, we could also grant other existing teams maintain access to the fork. What do you think works best?

**Comment by Phil91** [comment]
> Hi @Phil91,
> 
> I created the fork and granted `maintain` access for the portal team. I can also create a new team if necessary and add you as team maintainer. The you could add as many other colleagues as you like. Alternatively, we could also grant other existing teams maintain access to the fork. What do you think works best?

Thanks @SebastianBezold

I think for now the portal team is perfect since we're developing it for now. If it changes I'll come back to you :)

**Comment by SebastianBezold** [comment]
Ah perfect, then I'll close the issue for now

**Comment by FaGru3n** [comment]
> @SebastianBezold just came to the topic that I wanted to add some secrets to the tx-policy-hub repo, but missing the permissions, same for @evegufy should I reopen the issue or create a new issue for requesting the permission?

@SebastianBezold is on leave today new issue should be fine... then we can create some more secrets on the org on your desired repo... 

best practice... hint us where to find the secrets in your vault secret engine
