### ISSUE TITLE
Philipp Leschinski - New Tractus-X project contributor

### ISSUE THREAD

**Issue by PhilippL92** [eclipse-tractusx/sig-infra#336]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://accounts.eclipse.org/users/matbmoser

## Necessary Information

Email address to add: Philipp.leschinski@bmw.de
Committers, that could take over: 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by tomaszbarwicki** [comment]
Hi @PhilippL92, I struggle to add you as contributor. Getting the following error:
![image](https://github.com/eclipse-tractusx/sig-infra/assets/7613143/8a457fad-bb52-4547-bbba-59b5a3859fd8)

Can you please confirm you have an Eclipse Foundation account and valid ECA?

**Comment by FaGru3n** [comment]
Hi @PhilippL92 any update on this?

**Comment by kelaja** [comment]
@PhilippL92 kindly check :)

**Comment by SebastianBezold** [comment]
Hi @PhilippL92,

closing this issue, since it's stale for a while. Feel free to re-open it, in case you did not receive the contributor invite
