### ISSUE TITLE
Activate GitHub Pages on managed-identity-wallet

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-tractusx/sig-infra#338]
It would be great if you could active GitHub Pages in the [managed-identity-wallet repository](https://github.com/eclipse-tractusx/managed-identity-wallet). We would like to use the pages as Helm Chart repository, as it is already done in other Tractus-X projects. The target branch would be `gh-pages`.

**Comment by almadigabor** [comment]
Hi @DominikPinsel! Changes are done, please confirm it's working. Committers in your team can also make changes to your eclipse-tractusx repositories using Otterdog like in this pull request: https://github.com/eclipse-tractusx/.eclipsefdn/pull/41

**Comment by FaGru3n** [comment]
@DominikPinsel  FYI pages are enabled and will close this issue.
