### ISSUE TITLE
Create secrets in repositories

### ISSUE THREAD

**Issue by ds-ext-kmassalski** [eclipse-tractusx/sig-infra#342]
**Is your support request related to a problem? Please describe.**  
We want to stop using 'Keycloak' name in our repositories, so we need new secrets with same values as previously.

**Describe the solution you'd like**  
Please create the following secrets in repositories https://github.com/catenax-ng/tx-item-relationship-service, https://github.com/eclipse-tractusx/item-relationship-service
OAUTH2_CLIENT_SECRET_BETA
OAUTH2_CLIENT_TOKEN_URI
OAUTH2_CLIENT_ID
OAUTH2_CLIENT_SECRET 

Values should be exactly the same as previously:
KEYCLOAK_OAUTH2_CLIENT_SECRET_BETA -> OAUTH2_CLIENT_SECRET_BETA
KEYCLOAK_OAUTH2_CLIENT_TOKEN_URI -> OAUTH2_CLIENT_TOKEN_URI
KEYCLOAK_OAUTH2_CLIENT_ID -> OAUTH2_CLIENT_ID
KEYCLOAK_OAUTH2_CLIENT_SECRET -> OAUTH2_CLIENT_SECRET 
	  
As a next step we will ask you to remove old secrets.

**Comment by almadigabor** [comment]
Hi @ds-ext-kmassalski! Where can I find the values for these secrets? After setting them there is no way to see the values on GitHub so I can't just copy paste them from the old to the new ones. 

As for the https://github.com/eclipse-tractusx/item-relationship-service repo you need to open a helpdesk ticket on Gitlab asking for setting these secrets similarly like [here](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2186).

**Comment by FaGru3n** [comment]
hi @ds-ext-kmassalski 

Secrets were created for repo https://github.com/catenax-ng/tx-item-relationship-service 
based on your [comment](https://github.com/eclipse-tractusx/sig-infra/issues/342#issuecomment-1805769753) 

![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/c4736709-d6d7-4a89-a095-f8dcc53e154e)

as @almadigabor already told for the other repo you need to raise a GitLab Issue against the Eclipse Foundation.

> As for the https://github.com/eclipse-tractusx/item-relationship-service repo you need to open a helpdesk ticket on Gitlab asking for setting these secrets similarly like [here](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2186).

Please raise a new issue if we can delete the old repository secrets when all works in your desired way.

Thanks in advance.

**Comment by FaGru3n** [comment]
If GitLab issue is done, please feel free to reopen or raise a new issue against us to clean up the secrets
