### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by PiotrStys** [eclipse-tractusx/sig-infra#343]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: piotr.stys@zf.com
Committers, that could take over: @SebastianBezold

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by almadigabor** [comment]
Hey @PiotrStys! I can't add you to the contributors list yet. I get an error: `Contributors: found no valid user with that name.` Please confirm the following based on the [Getting started](https://eclipse-tractusx.github.io/docs/oss/getting-started) guide:

- You created an Eclipse Foundation account using the same email stated above.
- You signed the Eclipse Contributor Agreement.

Please let me know after you checked these.

**Comment by PiotrStys** [comment]
Hello,

Thank you, I have checked the requirements and it should be fixed now.

Best regards / Mit freundlichen Grüßen,

Piotr Styś
IT Security Specialist
ZF - External

**Comment by almadigabor** [comment]
Right, it worked this time. I've added you as contributor. Let me know if you need any further help.

**Comment by FaGru3n** [comment]
Hi @PiotrStys, feel free to leave a comment if something doesn´t working.
https://github.com/PiotrStys

**Comment by PiotrStys** [comment]
Thank you all for your assistance!
