### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by HiHenrik** [eclipse-tractusx/sig-infra#344]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: per-henrik.addicks@sap.com This has to be the email, you use for your Eclipse Foundation account -->
Committers, that could take over: @Siegfriedk, @FaGru3n, @SebastianBezold, @bjoeroy 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by Siegfriedk** [comment]
I have added you as contributor. pls verify and reopen the ticket if its not working for you.

**Comment by HiHenrik** [comment]
@Siegfriedk Hi Siggi, did not receive an invitation and am not assigned to an organization, please check, thank you Henrik

**Comment by Siegfriedk** [comment]
@HiHenrik you are a contributor, see the overview page https://projects.eclipse.org/projects/automotive.tractusx/who

Whats your expecation what you should be able to do now and can't?

**Comment by FaGru3n** [comment]
Hi @HiHenrik guess this is the step that is missing, because you are not joined the GitHub Organisation
https://github.com/HiHenrik
 
as stated in the issue template:
> Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

will look like... 
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/9dfafe6e-d13c-4dca-924f-241c11fbfcd0)

**Comment by SebastianBezold** [comment]
Just in case it's not known yet. There is also a "Socials" section in your Eclipse account settings.
You have to add your GitHub handle there, so the Eclipse Automation knows whom to invite
