### ISSUE TITLE
Keycloak instance on PEN environment responses with  HTTP 400,

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-infra#346]
**Is your support request related to a problem? Please describe.**  

To successfully conduct the DAST tests for QG4 we need to run Invicti Tests. 
The current setup with PEN keycloak is responding with 400. 
We need to successfully auth to pen keycloak to run DAST tests against our product. 

**Describe the solution you'd like**  
- Fix the Keycloak on pen to achieve security testing for QG4

**Additional context**

**Comment by FaGru3n** [comment]
Hi @mkanal just to clarify my confusion which environment do you mean with PEN Env.? 

could you give us a hint where and how you get the response?

Thx for clarificaion.

**Comment by mkanal** [comment]
Hi @FaGru3n 
The PEN environment is this environment on which INVICTI Tools is configured, and external PEN Testers have conducted their pen tests in the past. 
 
https://irs-pen.int.demo.catena-x.net/
https://centralidp-pen.dev.demo.catena-x.net/auth/realms/CX-Central/protocol/openid-connect/token

Our developer has completely new configured the OAuth against the KeyCloak instance on pen environment, and now it seems to be working. 
So I will close this issue.
I apologize for any inconvenience
