### ISSUE TITLE
Migrate catenax-ng website to eclipse tractusx

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/sig-infra#348]
We still have our original website https://catenax-ng.github.io/ up and running. The content is outdated, the core (the support process) is migrated to eclipse tractus-x.

Its time to move it over.

AC:

- Office Hour information is transfered over (calender invite, news)
- Outdated or moved information is deleted
- We create a Catena-x System Team space inside eclipse tratcus-x for everything related to us and not part of tractusx. This page / space will than deleted when we are gone
- The landing page / left over page is a forward to eclipse tractusx page

**Comment by FaGru3n** [comment]
asked security team directly on a little discussion how to handle the content for the security team
https://github.com/eclipse-tractusx/sig-security/discussions/62

**Comment by FaGru3n** [comment]
Hi @Siegfriedk, maybe you want to  review the current status also, so just FYI
