### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by RoKrish14** [eclipse-tractusx/sig-infra#349]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: rohan.krishnamurthy@zf.com
Committers, that could take over: @borisrizov-zf 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by FaGru3n** [comment]
Hi @RoKrish14, do you know maybe a committer from ZF?

**Comment by RoKrish14** [comment]
I am only aware of @borisrizov-zf , just from the ZF Id.

**Comment by FaGru3n** [comment]
to @RoKrish14 just to inform you every committer can add new Contributors to our Eclipse Foundation project.

To @borisrizov-zf, cool then congrats  for your voting and won election to be a committer.
Question from myside could you please take over the onboarding a new Contributor into our Eclipse Project?
If help needed we are here 👍 

Thanks in advance.

**Comment by borisrizov-zf** [comment]
@FaGru3n sure. Do we have a workflow for this I can follow?

**Comment by FaGru3n** [comment]
Hi not a place where i am aware of.

but simple for Email address to add: [rohan.krishnamurthy@zf.com](mailto:rohan.krishnamurthy@zf.com)

![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/24ee21b7-0972-4610-a758-6e00933ac8d1)

**Comment by borisrizov-zf** [comment]
Thanks! It's done.
