### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#351]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User:
AnuragNagpure

Vouching person: product-portal @evegufy @jjeroch

**Comment by FaGru3n** [comment]
Hi @evegufy 

could you verify that @AnuragNagpure is part of Catena X?

Thanks in advance

**Comment by evegufy** [comment]
> Hi @evegufy
> 
> could you verify that @AnuragNagpure is part of Catena X?
> 
> Thanks in advance

Yes, he's part of CX

**Comment by FaGru3n** [comment]
invitation was sent:

![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/d0fbf27f-8396-4996-8b73-4110105b2585)

**Comment by FaGru3n** [comment]
Hi @evegufy,

Please review and close the issue.
