### ISSUE TITLE
Upgrade stable to k8s version 1.27.3 if 1.25.x will retire on 2 January 2024

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#352]
Shouldn't we also upgrade stable if 1.25.x will retire on 2 January 2024?

_Originally posted by @almadigabor in https://github.com/eclipse-tractusx/sig-infra/issues/319#issuecomment-1805438880_

**Comment by almadigabor** [comment]
So maybe here we should align with release management and find a window when stable can be upgraded. Probably before the deployment starts for release 23.12 components.

**Comment by FaGru3n** [comment]
how is in change in those meetings? guess we can assign them directly to discuss with us, when we could upgrade...

**Comment by almadigabor** [comment]
There are no meetings in this topic anymore. Maybe we can mail the release management with it.

**Comment by FaGru3n** [comment]
FYI @Siegfriedk @mabige @RolaH1t

**Comment by mabige** [comment]
IMHO it makes sense to combine this with setup of STABLE 23.12. (Timeline currently under clarification)
Is INT still on 1.25.x?

**Comment by Siegfriedk** [comment]
Int should be on 1.27 and stable should/will be upgraded to the same version before we move the apps to stable for 23.12

**Comment by FaGru3n** [comment]
> IMHO it makes sense to combine this with setup of STABLE 23.12. (Timeline currently under clarification) Is INT still on 1.25.x?

INT aka hotel-budapest is currently on 1.27.3 see #319

**Comment by almadigabor** [comment]
It the timeline for release 23.12 allow us to upgrade the stable cluster before 2nd of January 2024? That's the latest date we have to upgrade.

**Comment by Siegfriedk** [comment]
> It the timeline for release 23.12 allow us to upgrade the stable cluster before 2nd of January 2024? That's the latest date we have to upgrade.

Stable is getting less important closer it gets to the next release. I'm currently not 100% when the official release date is, but we will just do the upgrade before 2th of jan or Microsoft might do it for us. I think that overlap will be fine

**Comment by mabige** [comment]
Task was assigned today at Consortia Operative Status Sync to RM @kelaja  to define how long Consortia Stable 23.09 will be needed and at which date the set-up of Consortia Stable 23.12 can be started. 
Open: Setup of Consortia Stable 23.12 from scratch or as an upgrade of 23.09

**Comment by FaGru3n** [comment]
first update for alignment for the cluster is prepared see https://github.com/catenax-ng/cloud-infra/pull/11

**Comment by FaGru3n** [comment]
Stable cluster now on version 1.27.3

nice info from the task to verify current available version in Azure as a Calender
https://learn.microsoft.com/en-us/azure/aks/supported-kubernetes-versions?tabs=azure-cli#aks-kubernetes-release-calendar
