### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by Gitleena** [eclipse-tractusx/sig-infra#356]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: 
Committers, that could take over: 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by FaGru3n** [comment]
Hi  @Gitleena  and @klaudiaZF  do you know maybe a committer in your ZF round?

Because on boarding a new contributor could also be done by any committer

**Comment by FaGru3n** [comment]
and we need an email adress from you @Gitleena  😉

**Comment by klaudiaZF** [comment]
@FaGru3n  Hi Fabian, we followed the steps from email that we've got from Kelaja. It supposed to add Gitleena to Tractus-X Organization and not to create committer ticket...I think there was a mistake in those steps... sorry for confusion. We will delete this :)

**Comment by FaGru3n** [comment]
Hi @klaudiaZF jep your totally right here but just want to inform that more people can add @Gitleena as a Contributor into the Eclipse Tractus-X GitHub Organisation.

if you have the generated Eclipse Foundation Accounts even i can add her, but the isse templates mentioned a committer who can do that ... and it was missing. 😉 so... some information are needed an we can onboard...

**Comment by klaudiaZF** [comment]
@FaGru3n  Last time I just asked Angelika through email to add me to Tractus-X Org and that was it. The steps we've got from email was quite misleading;)  what information do you need? 
Here's an email of @Gitleena leena.gujre@zf.com

**Comment by FaGru3n** [comment]
> @FaGru3n Last time I just asked Angelika through email to add me to Tractus-X Org and that was it. The steps we've got from email was quite misleading;) what information do you need? Here's an email of @Gitleena [leena.gujre@zf.com](mailto:leena.gujre@zf.com)

you can find the real process on our web-page https://eclipse-tractusx.github.io/docs/oss/getting-started

**Comment by FaGru3n** [comment]
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/74a006b5-57e8-410a-964b-34120d8c93fc)

**Comment by FaGru3n** [comment]
So @Gitleena you will get an invite to join Eclipse Tractus-X GitHub organisation.

will look like 
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/1c3afb14-45d7-43bc-ad22-82787ad44498)

For next time please ❤️ 
> Check the committer list of our project and highlight at least one of them on this issue, since every committer
can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

Because as already stated every committer can invite new contributors.
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/9b03c06f-b123-4423-b30a-7f55280115bf)

**Comment by FaGru3n** [comment]
Please verify @Gitleena and @klaudiaZF and close the issue afterwards.

Greetings

**Comment by Gitleena** [comment]
Hello @FaGru3n , I didn't received any email regarding invitation to join Eclipse Tractus-X GitHub organisation. What to do next please let me know.

**Comment by FaGru3n** [comment]
removed and added you again, i guess the process search for leenagujre9 in github and found nothing... maybe you can check you Eclipse Account if it is linked to you GitHub account @Gitleena

> Add your GitHub ID to your Eclipse profile (Section: Social Media Links)

**Comment by Gitleena** [comment]
Hello @FaGru3n,
I signed the agreement for Eclipse Contributer Foundation. I think now you need to add me again. My username for Eclipse Foundation is leenagujre9

**Comment by FaGru3n** [comment]
Hi @Gitleena added you again.

**Comment by FaGru3n** [comment]
Hi @Gitleena 

opened an Gitlab Issue for you that Eclipse Foundation can also Check on further details.
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3994

Generall Info: If you Eclipse Account is working you can ask the eclipse foundation also on Gitlab.

Did you also checked out your Spam Mailfolder? Happen sometimes.

**Comment by Gitleena** [comment]
Hi @FaGru3n 
I checked Junk folder but there is no email for invitation. I am able to login Eclipse account.

**Comment by FaGru3n** [comment]
Info from Eclipse Foundation

> I can't find any github handles in the eclipse profile. Can you ask the contributor to add this information?

Could you please add your GitHub Handle @Gitleena  into you Eclipse Foundation account see https://github.com/eclipse-tractusx/sig-infra/issues/356#issuecomment-1818933482

> Add your GitHub ID to your Eclipse profile (Section: Social Media Links)
> https://eclipse-tractusx.github.io/docs/oss/getting-started

**Comment by Gitleena** [comment]
Hi @FaGru3n 
I have added my GitHub ID to Eclipse profile (Section: Social Media Links)

**Comment by Gitleena** [comment]
Hi @FaGru3n and @klaudiaZF 
I got the invitation email and now I am part of eclipse-tractusx organization.

Thank you
