### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by obalandi** [eclipse-tractusx/sig-infra#358]
Hey guys, 

I am a member of the Knowledge Agent team, Can you add me as a contributor to the project.

Thanks

Oz

## Necessary Information

Email address to add: oguzhan.balandi@t-systems.com
Committers, that could take over: @stephanbcbauer

**Comment by FaGru3n** [comment]
Hi @obalandi warm welcome and sure... 

@stephanbcbauer would you like to overtake? if you have time pressure i can jump in..

greets.

**Comment by FaGru3n** [comment]
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/e7b4e008-8917-46ad-be87-3d94d8808d68)

sure @obalandi, updated procject and you will get an invite to join Eclipse Tractus-X GitHub organisation.
just to remind every committer can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

will look like 
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/1c3afb14-45d7-43bc-ad22-82787ad44498)

Please verify and close the issue afterwards maybe you want to also checkout our guides... https://eclipse-tractusx.github.io/docs/dev_links#eclipse-foundation-documentation

**Comment by stephanbcbauer** [comment]
@FaGru3n @obalandi sorry didn't see this tasks :(

**Comment by FaGru3n** [comment]
> @FaGru3n @obalandi sorry didn't see this tasks :(

no problem this is the reason why i asekd... and i guess @obalandi is onboarded now and successfully joined the Eclipse Tractus-X Organisation.

**Comment by FaGru3n** [comment]
@obalandi i would close the issue for now

**Comment by obalandi** [comment]
Thanks @FaGru3n !
