### ISSUE TITLE
TRG new: Docker file notice

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/sig-infra#360]
In our TRG Walkthrough we discussed to add a new TRG which only contains the information regarding Dockerfile notice file.

AC:
- Create new TRG in Documentation which says that the Dockerfile needs its own README.md/Notice file which then needs to be used when uploading an image to dockerhub

**Comment by SebastianBezold** [comment]
Hi @Siegfriedk,

I cannot remember the discussions we had on that topic. 
We already have a dedicated "Notice for Docker image" TRG here: https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-06

Is this about mandating, that the notice has to be a separate file? Or should I improve the description, so it becomes clearer, that there are these two options?

**Comment by Siegfriedk** [comment]
@SebastianBezold mhhh no clue. Im pretty sure we want to enforce a notice file for the docker image only and that it has to be uploaded to docker hub. If it fits in 4.06, thats probably fine

**Comment by SebastianBezold** [comment]
Ah ok, so if we want to enforce the standalone file, then I'll update the description slightly. Right now both cases, README.md section and standalone file, are valid

**Comment by SebastianBezold** [comment]
I opted to first ask for feedback on the potential change [on our mailing list](https://www.eclipse.org/lists/tractusx-dev/msg00306.html). 
If positive, i'll update the TRG description
