### ISSUE TITLE
TRG 2.02: Should we get rid of it?

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/sig-infra#364]
The TRG 2.02 in itself doesn't seem to be to necessary. We have another community page which might tell you thant you can't get permissions / admin permissions on your repo.

Revisit https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-2 and check if our eclipse tractus page makes it clear enough. If yes, get rid of it / deprecate it

**Comment by FaGru3n** [comment]
here are some links to the handbook and the permission description from GitHub

E.g. for a feature:
Everyone can create a feature.
Existing features can be edited by committer or the creator of the feature
Feature contexts (e.g. Labels, Milstones, ...) can be changed by any contributor
Rules:
GitHub’s [Repository roles for an organization](https://docs.github.com/en/organizations/managing-access-to-your-organizations-repositories/repository-roles-for-an-organization)
Referenced at Eclipse Foundation Handbook, Chapter [Access to GitHub Repositories](https://www.eclipse.org/projects/handbook/#resources-github-access)

(Read: Everyone, Triage: Contributor, Write: Committer)
Repository roles for an organization - GitHub Docs
You can customize access to each repository in your organization by assigning granular roles, giving people access to the features and tasks they need.
