### ISSUE TITLE
TRG 2.03: Reword the WHY

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/sig-infra#365]
The TRG 2.03 https://eclipse-tractusx.github.io/docs/release/trg-2/trg-2-3 WHY reason is a little bit convoluted. We need to reword it.

We also need to add the word (optional) behind AUTHOR and InSTALL as they can be optional. Verify that all other files are fine

AC:
- Reword the Why to make it better
- Add (optional) behind author and install file

**Comment by hzierer** [comment]
Link to PR: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/529
