### ISSUE TITLE
TRG 4.02: Remove CAUTION

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/sig-infra#368]
TRG 4.02 https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-02

AC:
- Remove the CAUTION tag as thats done
- Add info why we use images from docker hub (they are currated / verified opensource)

**Comment by hzierer** [comment]
PR: https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/527
