### ISSUE TITLE
TRG 4.03: Align on userid

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/sig-infra#369]
The TRG 4.03 contains example regarding userids https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-03 but the userids used in the examples are different.

AC:
- align the userids in the example
- revisit everything else like t&t and see if it makes sense to suggest a userid or write / update the trg with some best practices

**Comment by almadigabor** [comment]
Hey @Siegfriedk! Should we turn this TRG into a whole `container security` topic or just keep is as non-root? I would consider adding more fields as described in the https://github.com/eclipse-tractusx/sig-infra/issues/369 to further enhance security like runAsGroup, fsGroup and also dropping capabilities. I would welcome some suggestions here.

**Comment by SSIRKC** [comment]
Hi guys,

yes are working on a new chapter. Probably chapter 8 "Security".
Checkout out our backlog:
https://github.com/orgs/eclipse-tractusx/projects/44/views/1

In general the new chapter is being followed/worked on by @szafrugr and @klaudiaZF

**Comment by SSIRKC** [comment]
> Hey @Siegfriedk! Should we turn this TRG into a whole `container/pod security` topic or just keep is as non-root? I would consider adding more fields as described in the [Kubernetes docs](https://kubernetes.io/docs/tasks/configure-pod-container/security-context/#set-the-security-context-for-a-pod) to further enhance security like runAsGroup, fsGroup and also dropping capabilities. I would welcome some suggestions here.

Also did some things in regards to read only file system as TRG. Maybe there is some intersection that might help :)
https://eclipse-tractusx.github.io/docs/release/trg-0/trg-4-07 (Need to move it though)

**Comment by almadigabor** [comment]
Hey, thanks for the info! Right, seems like you're covering most of these topics in the draft TRG4-07. This case I'm not going to duplicate these in 4-03.
