### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by alexandrudanciu** [eclipse-tractusx/sig-infra#377]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User:
hemantxpatel

Vouching person: stefan-ettl

**Comment by FaGru3n** [comment]
Invitaion done, can be closed.

@hemantxpatel If there are any problems feel free to reopen the issue.

**Comment by hemantxpatel** [comment]
Hi @FaGru3n , I got access to it, but I can't see any apps which are deployed. Is it correct behaviour?
![image](https://github.com/eclipse-tractusx/sig-infra/assets/141825885/ba1491b0-dcd6-453f-b22e-bcf5d0f62c53)

**Comment by FaGru3n** [comment]
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/00d4fb61-6a42-4ea6-89d7-f39015f96c3d)

the maintainer of the Catena-X GitHub Team have to add you in the desired GitHub Team for the Organisation, then your will get more priviledged access.

**Comment by FaGru3n** [comment]
based on the requester permission  @alexandrudanciu 

thees github teams are 
https://github.com/orgs/catenax-ng/teams/product-edc?query=role%3Amaintainer
https://github.com/orgs/catenax-ng/teams/product-standardization?query=role%3Amaintainer
