### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by arnoweiss** [eclipse-tractusx/sig-infra#378]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: arno.weiss@sap.com
Committers, that could take over: @tom-rm-meyer-ISST 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by tom-rm-meyer-ISST** [comment]
I assumed that you already signed the ECA. At least I was also able to add you as a contributor. You'll be contributor soon (There will be runs that add you respectively to the product). As you can see [here](https://projects.eclipse.org/projects/automotive.tractusx/who), you've been already added.

Now you can also be e.g. assigned as reviewer in Github but still are not eligible to merge into eclipse-tractusx github project.
