### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by MehrdadSalari** [eclipse-tractusx/sig-infra#380]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: mehrdad.salari@zf.com
Committers, that could take over: B.Rizov@cluetec.de

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by SebastianBezold** [comment]
Hi @borisrizov-zf, I guess you do not get notified with your Email mentioned instead of GitHub handle. 
Could you take over for your colleague? If you are unsure, where and how to do that, I can also guide you

**Comment by borisrizov-zf** [comment]
Hi @SebastianBezold I've done it before. The autofill is not working, I suppose the eclipse account is not mapped?

@MehrdadSalari can you please check your eclipse username <-> email mapping.

**Comment by SebastianBezold** [comment]
Yeah, autofill is buggy unfortunately. When pasting the email and saving, it usually works, even though the autocomplete did not suggest it.
But AFAIK, this only works with the email and not with the EF username. That's why we ask for the email in the issue template actually 😁

**Comment by borisrizov-zf** [comment]
Ok, last time I did it, it did bring up the username, but maybe I'm just imagining... In any case it's done now. I'll close this.
