### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by adityagajbhiye9** [eclipse-tractusx/sig-infra#381]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add:  aditya.gajbhiye@t-systems.com
Committers, that could take over: [wjost](https://github.com/wjost)

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by FaGru3n** [comment]
Info @wjost is in the meantime a historical committer

**Comment by adityagajbhiye9** [comment]
I have signed ECA.

**Comment by FaGru3n** [comment]
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/9341c9fb-4da3-47d5-bccd-fab130d7ac4b)

**Comment by adityagajbhiye9** [comment]
@FaGru3n I got Invitation and accepted it.Thanks
