### ISSUE TITLE
PolicyHub: Sonarcloud setup

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/sig-infra#382]
**Is your support request related to a problem? Please describe.**  
We are currently setting up the PolicyHub project, to check the code quality one of the tools we're using is sonarcloud therefore we have a workflow in place to run the sonarcloud checks. As of now there is no sonarcloud configuration existing for the two policy hub projects [fork](https://github.com/catenax-ng/tx-policy-hub) and [upstream](https://github.com/eclipse-tractusx/policy-hub).

**Describe the solution you'd like**  
Could you please take over the configuration for sonarcloud.
The upstream project should be configured like: https://sonarcloud.io/project/overview?id=eclipse-tractusx_portal-backend
The fork project should be configured like: https://sonarcloud.io/project/overview?id=catenax-ng_tx-portal-backend

**Additional context**  
N/A

**Comment by FaGru3n** [comment]
for [fork](https://github.com/catenax-ng/tx-policy-hub)  --> https://sonarcloud.io/project/?id=catenax-ng_tx-policy-hub
SONAR_Token was added in the repo settings under secrets

**Comment by FaGru3n** [comment]
for the upstream you have to get in contact with the Eclipse Foundation maybe over GitLab Issue or Matrix Chat.

We as System Team can not modify the Sonarcloud projects for this GitHub Organisation

**Comment by Phil91** [comment]
> for [fork](https://github.com/catenax-ng/tx-policy-hub) --> https://sonarcloud.io/project/?id=catenax-ng_tx-policy-hub SONAR_Token was added in the repo settings under secrets
> 
> think the workflow to use sonarcloud is missing like https://github.com/catenax-ng/tx-portal-backend/blob/dev/.github/workflows/sonarcloud.yml

thanks a lot. i've currently working on upstream. but once finished it should be available in the fork as well.

for upstream i'll create a github issue.

**Comment by FaGru3n** [comment]
You´re welcome. 😉 I will close issue for now feel free to repoen it, if you have further questions

**Comment by FaGru3n** [comment]
Hi @Phil91 https://eclipse-tractusx.github.io/docs/oss/issues/#eclipse-foundation-helpdesk

there is also an example on our web-page 
> [Example](https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/2843) for requesting a sonar project for a repository
