### ISSUE TITLE
Access to Veracode platform

### ISSUE THREAD

**Issue by ds-psosnowski** [eclipse-tractusx/sig-infra#383]
**Is your support request related to a problem? Please describe.**  
Cannot access Veracode platform to perform security checks.

**Describe the solution you'd like**  
Grant personal access.

**Additional context**

**Comment by FaGru3n** [comment]
Hi @ds-psosnowski guess this points directly to our sig-security team, either you create another issue there or maybe we can reference a member directly in this issue.

[sig-security issue template](https://github.com/eclipse-tractusx/sig-security/issues/new?assignees=scherersebastian&labels=security%2C+tooling&projects=&template=security-tooling-support-request.md&title=%5BSecurity+Tooling%5D+YOUR_ISSUE_TITLE_HERE)

**Comment by ds-psosnowski** [comment]
Hey, thanks for quick response, I will create ticket in valid scope.

**Comment by FaGru3n** [comment]
Great thx and now close this one.

Have a great day.
