### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by ZFLokesh** [eclipse-tractusx/sig-infra#385]
Hello Team,

Please add me to the contributor role, below is my required info.

## Necessary Information

Email address Lokesh.Gujre@zf.com
Committers, that could take over: @scherersebastian @FaGru3n @AngelikaWittek 

Thank you
Best Regards
Lokesh Gujre

**Comment by FaGru3n** [comment]
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/3b388e8f-089d-4ce2-8ded-413c3a532d65)

Invite from Eclipse to the Organisation Eclipse Tractus-X will be apprear in some time... guess ~2 hours

this will work of you have done this... 

- Sign the [Eclipse Contributor Agreement (ECA)](https://www.eclipse.org/legal/ECA.php)
- Add your GitHub ID to your Eclipse profile (Section: Social Media Links)

Ideas for research as a contributor:
- Subscribe to the [Eclipse Tractus-X Developer Mailinglist](https://accounts.eclipse.org/mailing-list/tractusx-dev)
- Get familiar with the [Eclipse Foundation Project Handbook](https://www.eclipse.org/projects/handbook/), we will reference the dedicated chapters for the different topics.
- See the [documentation](https://eclipse-tractusx.github.io/docs/dev_links#eclipse-foundation-documentation)
- https://eclipse-tractusx.github.io/docs/dev_links/
- https://eclipse-tractusx.github.io/docs/dev_faq

**Comment by ZFLokesh** [comment]
Thank You @FaGru3n
