### ISSUE TITLE
Deployment automation and helm test concept after the end of the consortia 

### ISSUE THREAD

**Issue by ds-mmaul** [eclipse-tractusx/sig-infra#386]
**Is your support request related to a problem? Please describe.**  

With the end of the consortia we currently have no clear concept on how to automize deployment and use helm testing on tractus-x.

**Describe the solution you'd like**  

It would be great to have a guidelline/concept on how to realize this after the consortia phase. To be more precise, answers to the following question would give a clear understanding:
* How to deploy trace-X in tractus-X environments (is there a infrastructure we could prepare?)
* How to automatically test trace-x in tractus-x 
* How to execute helm tests on tractus-X   

Thank you very much.

**Comment by hzierer** [comment]
Hi @ds-mmaul,
to be honest the post consortia phase is still heavy in development.

For sure I can only answer your third question: The GH action workflow described in [TRG 5.09](https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-09) is and will be available in Tractus-X

Regarding your other two questions, I would raise them in the [sig-release](https://github.com/eclipse-tractusx/sig-release) repo, as they are preparing also for release management after the end of consortia.

**Comment by hzierer** [comment]
...and of course any other "sane" workflows of your repo with be there in the future too
