### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by bajaioana** [eclipse-tractusx/sig-infra#389]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: ioana.baja@msg.group
Committers, that could take over: @stephanbcbauer 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by tomaszbarwicki** [comment]
Hi @bajaioana, I've added you to project contributors.

**Comment by FaGru3n** [comment]
@bajaioana feel free to reopen the issue. For now we would close the issue
