### ISSUE TITLE
New Environment 

### ISSUE THREAD

**Issue by Ruskyy** [eclipse-tractusx/sig-infra#39]
Purpose: Demo and Internal Testing
Requested by: jschu1 - 112865179
End date of demonstration: 31.12.2023
Teams participating: product-cgi-dcm-foss

**Comment by FaGru3n** [comment]
Hi @Ruskyy, 

thanks for the Request but for Demo and internal Testing we already have some environments.

> BEWARE: 
> We do not provide dedicated environments for single teams. We will provide a DEV, INT, and 
PRE-PROD environment and teams will collectively use these environments together. A list of available environments can be found in the [Confluence](https://confluence.catena-x.net/pages/viewpage.action?pageId=25228715#InternalCatenaXinformationforsharingthroughLanding/Supportpage-Kubernetesenvironments).

Hope you understand, and if there more questions feel free to ask.
