### ISSUE TITLE
We need to have the secret available in the GH action env

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#390]
thanks for replying! We need to have the secret available in the GH action env, so the most forward way is to use secrets at repo level, like we're already doing it in the e2e-testing workflow in the portal-backend.
If some more context is needed, we're glad to explain in a quick call.

_Originally posted by @evegufy in https://github.com/eclipse-tractusx/sig-infra/issues/335#issuecomment-1847344350_

**Comment by FaGru3n** [comment]
guess we should have a little chat on monday... 😉

**Comment by FaGru3n** [comment]
https://github.com/catenax-ng/tx-policy-hub/

modified permission rules for  @evegufy and @Phil91 so should be fine for now.

Please review and and close the issue depending on your feedback 😉 

Thx and a good day...

**Comment by Phil91** [comment]
Works like a charm. Thanks a lot :)
