### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by PatStra** [eclipse-tractusx/sig-infra#394]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: Pedde.Strauss@gmail.com
Committers, that could take over: Malte Hellmeier, Markus Keidl

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by almadigabor** [comment]
Hey @PatStra! Did you follow the getting started section [here](https://eclipse-tractusx.github.io/docs/oss/getting-started/)? If you've created an Eclipse account, subscribed to the mailing list and signed the ECA, I can add you to the project as contributor. Make sure to create the Eclipse account with the mail address you use in your GitHub account!

**Comment by FaGru3n** [comment]
HI @PatStra any updates on this?

**Comment by FaGru3n** [comment]
> HI [@PatStra](https://github.com/PatStra) any updates on this?

Guess your not available or on vacation, feel free to reopen the issue if your back.

Thanks in advance.
