### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by ajithsimons** [eclipse-tractusx/sig-infra#395]
## Issue Detail

I'm an active contributor to eclipse already. For some reasons our devsecops team can't able add contributor role to my account. 
I have already signed ECA. Both GitHub and Eclipse account have the same email address as primary. 

Here is my project/contribution - [managed-simple-data-exchanger-frontend](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend/graphs/contributors)

## Necessary Information

Email address to add: ajithkumar.s@t-systems.com 
GitHub user id: ajithsimons
Committers, that could take over: @FaGru3n @almadigabor

**Comment by tomaszbarwicki** [comment]
hi @ajithsimons, I've added you to project contributors, pls check and confirm.
