### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by szymonkowalczykzf** [eclipse-tractusx/sig-infra#398]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: szymon.kowalczyk@zf.com 
Committers, that could take over: @FaGru3n 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by FaGru3n** [comment]
Hi @szymonkowalczykzf  could someone aprove that your working within and for Catena-X, maybe someone form ZF?

Thanks in advance.

**Comment by klaudiaZF** [comment]
Hi @FaGru3n  I confirm that @szymonkowalczykzf  is working with me for Catena-X

**Comment by FaGru3n** [comment]
added you as contributor within our eclipse project:
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/0d58a243-8342-477c-b556-6ea72c65d10c)

Please verify and accept the GitHub Organsiation invite.
> Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

If you are part of the GitHub Organisation you can close the issue. 😉
