### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/sig-infra#399]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: Herciu, Ciprian <Ciprian.Herciu@t-systems.com> 
Committers, that could take over: @FaGru3n @mabige @MehranRoshandel @sachinargade123 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by FaGru3n** [comment]
> could take over: @FaGru3n @mabige @MehranRoshandel @sachinargade123

Hi all, could someone please verify that @ciprianherciu is part of us as Catena-X / Tractus-X?

Thanks in advance.

**Comment by mabige** [comment]
Yes, I can confirm. He is part of Consortia (PO at CX ART)

**Comment by FaGru3n** [comment]
@ciprianherciu you were added as contributor to our Eclipse project invitation to the GitHub organisation will follow by the Organisation admins.
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/e3cc02a1-d23e-4bae-80d3-e752335a89be)

>Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

After that issue can be closed after your feedback. Thanks in advance.

**Comment by MehranRoshandel** [comment]
Yes,
He is the new PO for GDS and IDS team. He has take over of my role in Catena.
Dr. Mehran Roshandel

Am 08.01.2024 um 15:43 schrieb Fabian Grün ***@***.***>:

﻿

could take over: @FaGru3n<https://github.com/FaGru3n> @mabige<https://github.com/mabige> @MehranRoshandel<https://github.com/MehranRoshandel> @sachinargade123<https://github.com/sachinargade123>

Hi all, could someone please verify that @ciprianherciu<https://github.com/ciprianherciu> is part of us as Catena-X / Tractus-X?

Thanks in advance.

**Comment by FaGru3n** [comment]
Hi @ciprianherciu or @MehranRoshandel @mabige any update on this?

**Comment by MehranRoshandel** [comment]
Markus and I have approved that Ciprian is part of the Catena-X / Tractus-X. Would you happen to need something more?
If not, then you can close.

**Comment by FaGru3n** [comment]
@ciprianherciu is now part of the Eclipse Tractus-X GitHub organisation and shown as contributor in our Eclipse project side. 

so will close this issue.
