### ISSUE TITLE
Invite/Give access to SonarCloud org.

### ISSUE THREAD

**Issue by Ruskyy** [eclipse-tractusx/sig-infra#40]
**Reason**
As a a requirement from our PO, my team needs to use SonarCloud, as a code review solution.
We were instructed to request this access to Catena.

**AC**
- Give access to members of the product-cgi-dcm-foss team to SonarCloud Org.

**Additional information / links**
Reference to: https://github.com/eclipse-tractusx/sig-infra/issues/36
Let me know if more information is required.

**Comment by FaGru3n** [comment]
Hi @Ruskyy  thanks for the task.

This issue type should only used by the system team itself 😉 but we have to make it clearer that this one is only for the System Team. This one seems ok [Support: other topics](https://github.com/eclipse-tractusx/sig-infra/issues/new?assignees=&labels=support&projects=&template=support-general-requirement.md&title=)

Could you create annother one as a support request with the same information?

I will close this one, sorry for missunderstanding.
