### ISSUE TITLE
New Tractus-X project contributor for @ds-lcapellino

### ISSUE THREAD

**Issue by ds-lcapellino** [eclipse-tractusx/sig-infra#400]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: lucas.capellino@doubleslash.de
Committers, that could take over: @mkanal @ds-mwesener

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by SebastianBezold** [comment]
Hi @mkanal and @ds-mwesener,

do you know how to add a project contributor to the EF project?

**Comment by SebastianBezold** [comment]
Hi @ds-lcapellino,

I added you to the contributors section in our Eclipse Foundation project. You should receive an invitation to the GitHub org today I think. 
If you do not receive an email for that, make sure you correctly added your GitHub handle to the socials section in your EF profile, or check the GitHub org directly. Sometimes you'll see the invite on GitHub in your browser, but the mail got lost.
