### ISSUE TITLE
GitHub: Invite member @ds-crehm

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-infra#402]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User:
@ds-crehm

Vouching person: @mkanal

**Comment by FaGru3n** [comment]
Hi @mkanal could you please verify that @ds-crehm is working for Catena-X

**Comment by FaGru3n** [comment]
Hi @mkanal any update on this?

**Comment by mkanal** [comment]
> Hi @mkanal could you please verify that @ds-crehm is working for Catena-X?

Hi @FaGru3n I confirm that  @ds-crehm is working for Catena-X. Thank you very much.

**Comment by FaGru3n** [comment]
Hi @mkanal thanks for the input.

@ds-crehm you were invited:
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/e4704e40-33a7-4129-8e9c-7bcbb432a15d)

After 7 days the invitation expires and the maintainer of the gh-team can now invite you.

Please review and close the issue if you are a part of the [Catena-X ng](https://github.com/catenax-ng)

**Comment by ds-crehm** [comment]
Hi @FaGru3n, thank you. I'm a member of the organization now.

**Comment by FaGru3n** [comment]
> Hi @FaGru3n, thank you. I'm a member of the organization now.

Great and a warm welcome will close the issue 😉 

Happy Coding!
