### ISSUE TITLE
GitHub: Invite members to ng for product-puris

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/sig-infra#403]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub Users:

- [f-zimmer](https://github.com/f-zimmer)
- [MercedesG-8020](https://github.com/MercedesG-8020)
- [ReneSchroederLJ](https://github.com/ReneSchroederLJ)
- [denis8020](https://github.com/denis8020)

Vouching person: Me and @mhellmeier. I guess me requesting this is sufficient.

target team: [product-puris](https://github.com/orgs/catenax-ng/teams/product-puris)

**Comment by hzierer** [comment]
Cheers, invitations have been sent.

**Comment by hzierer** [comment]
Since all 4 have accepted their invitations I will close the ticket.
