### ISSUE TITLE
New Tractus-X project contributor for @ds-crehm

### ISSUE THREAD

**Issue by ds-crehm** [eclipse-tractusx/sig-infra#404]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: christian.rehm@doubleslash.de
Committers, that could take over: @mkanal @ds-mwesener 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by FaGru3n** [comment]
Hi @mkanal and @ds-mwesener,

could you overtake this invitation?

Thanks in advance

**Comment by ds-mwesener** [comment]
Hi @FaGru3n currently I cannot see him within the organisation. As far as I know you added them to the organization and we add the users to the project, correct?

**Comment by FaGru3n** [comment]
Hi @ds-mwesener  

this issue https://github.com/eclipse-tractusx/sig-infra/issues/402 was for the invite to Catena-X ng but with this new issue it is regarding to [ETX](https://github.com/eclipse-tractusx)

**Comment by ds-mwesener** [comment]
HI @FaGru3n could you please explain how to add a user to the tractus-x organization? In the past the system team did that part for us. Afterwards we were able to add the user to the eclipse contributor group.

**Comment by FaGru3n** [comment]
> HI @FaGru3n could you please explain how to add a user to the tractus-x organization? In the past the system team did that part for us. Afterwards we were able to add the user to the eclipse contributor group.

simply speaking for catena-x ng the system-team can invite people into the organisation.

The Eclipse Tractus-X GitHub Org is manged by Eclipse Foundation to we as committer can add new contributor on the eclipse project site and in the background an eclipse bot will invite new contributors into the GitHub organisation.

So if you can add @ds-crehm as contributor, he will get an invite to the [eclipse-tractusx GitHub](https://github.com/eclipse-tractusx) organisation.

**Comment by FaGru3n** [comment]
Hi @ds-mwesener added him as contributor into our eclipse project, so he will get an invite to join the eclipse tractus-x organisation.

![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/e39439e7-49d3-44a0-b593-88fe14903c57)

process is also described on the [website ](https://eclipse-tractusx.github.io/docs/oss/getting-started )and on the [handbook](https://www.eclipse.org/projects/handbook/).

Info:
Every committer can add new contributors to the the eclipse project and then the new contributor will be invited to the GitHub organisaion.

Please review and after successful invitation, issue can be closed.

**Comment by ds-mwesener** [comment]
Successfully done.
