### ISSUE TITLE
New Tractus-X project contributor ds-crehm

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-infra#406]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: christian.rehm@doubleslash.de
Committers, that could take over: @mkanal 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by FaGru3n** [comment]
related to https://github.com/eclipse-tractusx/sig-infra/issues/404

**Comment by FaGru3n** [comment]
Hi @mkanal added him as contributor into our eclipse project, so he will get an invite to join the eclipse tractus-x organisation.

![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/e39439e7-49d3-44a0-b593-88fe14903c57)

process is also described on the [website ](https://eclipse-tractusx.github.io/docs/oss/getting-started )and on the [handbook](https://www.eclipse.org/projects/handbook/).

Info:
Every committer can add new contributors to the the eclipse project and then the new contributor will be invited to the GitHub organisaion.

Please review and after successful invitation, issue can be closed.

**Comment by ds-mwesener** [comment]
Hi @FaGru3n thanks for information. Everything should be done now.
