### ISSUE TITLE
Adapt the about section for Tractus-X traceability-foss project

### ISSUE THREAD

**Issue by ds-mwesener** [eclipse-tractusx/sig-infra#407]
**Is your support request related to a problem? Please describe.**  

Currently within the[ catena github repository](https://github.com/catenax-ng/tx-traceability-foss) in the about section there is
a link which tells the user where to find our documentation.

In [Tractus-X Repository](https://github.com/eclipse-tractusx/traceability-foss) we would like to have the same, with the correct link:
https://eclipse-tractusx.github.io/traceability-foss/docs/

**Describe the solution you'd like**  

Add the link: https://eclipse-tractusx.github.io/traceability-foss/docs/ to the about section of: https://github.com/eclipse-tractusx/traceability-foss

@jzbmw FYI

**Comment by FaGru3n** [comment]
https://github.com/eclipse-tractusx/traceability-foss was updated via otterdog config, adde homepage for the repo instead of description, but looks like the same on the repo side.

FYI @ds-mwesener @jzbmw 

Please verify and close the issue, if your approve the changes.

**Comment by ds-mwesener** [comment]
Hi @jzbmw for me this works perfectly. Please close if okay for you.
