### ISSUE TITLE
[CX]DevSecOps Office Hours

### ISSUE THREAD

**Issue by ds-lcapellino** [eclipse-tractusx/sig-infra#408]
**Is your support request related to a problem? Please describe.**  

I want to receive an invitation for the [CX]DevSecOps Office Hours meeting on Friday. 

**Describe the solution you'd like**  
Please add me to the mailing list to receive updates for that meeting. 
lucas.capellino@doubleslash.de

**Additional context**

**Comment by almadigabor** [comment]
Hey @ds-lcapellino! I've forwarded the calendar event series to you. Let me know if you've received it.

**Comment by FaGru3n** [comment]
Hi @ds-lcapellino did you get the invitation? 

Just want to ask friendly if we can close this issue.

**Comment by FaGru3n** [comment]
Hi @ds-lcapellino i would close the issue if your have further questions feel free to repoen the issue. 

Thanks in advance.
