### ISSUE TITLE
Add Discussion section to github tractus-x traceability-foss project

### ISSUE THREAD

**Issue by ds-mwesener** [eclipse-tractusx/sig-infra#409]
**Describe the solution you'd like**  

We would like to use the discussions tab within the repository: https://github.com/eclipse-tractusx/traceability-foss

Could you please add that? 

Thanks in advance.

**Comment by almadigabor** [comment]
Hey @ds-mwesener! I've created the PR, let's wait for it to be merged.

**Comment by almadigabor** [comment]
Hey @ds-mwesener! Discussions are live now. Can I close the issue?

**Comment by ds-mwesener** [comment]
Thank you!
