### ISSUE TITLE
Add documentation url to about section of  repos item-relationship-service

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-infra#410]
**Is your support request related to a problem? Please describe.**  

**Describe the solution you'd like**  
Please add url 'https://eclipse-tractusx.github.io/item-relationship-service/docs/' to About section or repos https://github.com/eclipse-tractusx/item-relationship-service

![image](https://github.com/eclipse-tractusx/sig-infra/assets/100209308/ad259c35-8c5f-40c6-9d57-1fe77e27a195)

**Additional context**

**Comment by almadigabor** [comment]
Hey @mkanal! Do you mean add the url `https://eclipse-tractusx.github.io/item-relationship-service/docs/` to the about section (description) of the repository?

**Comment by mkanal** [comment]
Hey @almadigabor yes please

**Comment by almadigabor** [comment]
Thanks @FaGru3n for pointing this out! I've created the PR, let's wait for it to be merged.

**Comment by almadigabor** [comment]
Hey @mkanal! Changes have been made, I'm closing the issue. Please reopen is any problem comes up.
