### ISSUE TITLE
GitHub: New forks for ssi-credential-issuer & ssi-authority-schema-registry

### ISSUE THREAD

**Issue by Phil91** [eclipse-tractusx/sig-infra#413]
repository name within Tractus-X Organisation: 
[ssi-credential-issuer](https://github.com/eclipse-tractusx/ssi-credential-issuer)
[ssi-authority-schema-registry](https://github.com/eclipse-tractusx/ssi-authority-schema-registry))

repository name within Catena-X NG Organisation: 
ssi-credential-issuer -> tx-ssi-credential-issuer
ssi-authority-schema-registry -> tx-ssi-authority-schema-registry

GitHub team to grant access: 
for both repositories please use the same as for [tx-portal-backend](https://github.com/catenax-ng/tx-portal-backend).
If possible please make @evegufy @ntruchsess and myself admins of the repos.

**Comment by FaGru3n** [comment]
https://github.com/eclipse-tractusx/.eclipsefdn/pull/52#event-11628184695

**Comment by FaGru3n** [comment]
Hi @Phil91,

Forks are created:
- https://github.com/catenax-ng/tx-ssi-authority-schema-registry
- https://github.com/catenax-ng/tx-ssi-credential-issuer

Please verify, thanks in advance.

Just a general question why to you need admin permission on the forks?

**Comment by Phil91** [comment]
thanks , looks good.

mainly to add secrets and variables for our workflows. I think we have admin permission for the portal-backend repo as well

**Comment by Phil91** [comment]
@FaGru3n thank you for the setup
