### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by SujitMBRDI** [eclipse-tractusx/sig-infra#415]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: capgemini.f.sharma@mercedes-benz.com
Committers, that could take over: @FaGru3n @SujitMBRDI 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by almadigabor** [comment]
Hey @SujitMBRDI, I've added capgemini.f.sharma@mercedes-benz.com to the contributor's list. Please check if everything works as intended and let me know if the issue can be closed.

**Comment by SujitMBRDI** [comment]
> Hey @SujitMBRDI, I've added [capgemini.f.sharma@mercedes-benz.com](mailto:capgemini.f.sharma@mercedes-benz.com) to the contributor's list. Please check if everything works as intended and let me know if the issue can be closed.

Thanks for help :) You can close the ticket.
