### ISSUE TITLE
GitHub: Invite members for ng for product-puris

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/sig-infra#417]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User:

- [BenjaminKotnik](https://github.com/search?q=BenjaminKotnik&type=users)
- [MaticTuma](https://github.com/MaticTuma)

Vouching person: Me and @mhellmeier. I guess me requesting this is sufficient.

target team: [product-puris](https://github.com/orgs/catenax-ng/teams/product-puris)

**Comment by FaGru3n** [comment]
Hi @tom-rm-meyer-ISST or @mhellmeier could you verify that @MaticTuma and @BenjaminKotnik are working for Catena-X ? 

Thanks in advance.

**Comment by tom-rm-meyer-ISST** [comment]
@FaGru3n, yes they do :)

Thanks in advance!

**Comment by FaGru3n** [comment]
Hi @tom-rm-meyer-ISST,

invitation was sent:

![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/df37936b-389f-4481-8df1-7b47ae4ce097)

for onboarding to the [gh-team](https://github.com/orgs/catenax-ng/teams/product-puris?query=role%3Amaintainer) you can invite them into the team by yourself after the invitation is succeeded. (7 Days)

Please verify after wards and close the issue.

**Comment by FaGru3n** [comment]
Hi @tom-rm-meyer-ISST ,

see that the invite was successful so would close the issue. 

If further help is need, feel free to reopen the issue.
