### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/sig-infra#418]
## Necessary Information

Email address to add: leon.schandelmeyer@cgi.com
github user: leonschand
github profile: [leonschand (github.com)](https://github.com/leonschand)
Committers, that could take over:  @SujitMBRDI 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by FaGru3n** [comment]
HI @SujitMBRDI could you take over to onboard @leonschand as a new contributor to Eclipse Tractus-X?

If you need guidance feel free to contact us.

**Comment by FaGru3n** [comment]
Hi @fabiodmota,

FYI @SujitMBRDI 

@leonschand was invited as contributor, to the Eclipse Tractus-X project.

![Image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/5ef30400-497e-4b9c-ad2a-b1a0605f0c58)

Please make sure, that @leonschand accept the invitation you receive from GitHub, after you have been added as project contributor.

Afterwards please review and close the issue.

**Comment by FaGru3n** [comment]
Hi @fabiodmota  ,

see that the invite was successful so would close the issue. 

If further help is need, feel free to reopen the issue.
