### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by BANANAS1337** [eclipse-tractusx/sig-infra#419]
## Necessary Information

Email address to add: tim.herres@mercedes-benz.com
Committers, that could take over: @AngelikaWittek , @SebastianBezold 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by tomaszbarwicki** [comment]
hi @BANANAS1337, can you please confirm on following https://eclipse-tractusx.github.io/docs/oss/getting-started/? I can't find your email address to be added to contributors list.

**Comment by BANANAS1337** [comment]
hi @tomaszbarwicki can you check again?

**Comment by FaGru3n** [comment]
Hi @BANANAS1337 invitation was done,

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

If you are part of the https://github.com/eclipse-tractusx Organisation, please verify and close the issue.

**Comment by FaGru3n** [comment]
Hi @BANANAS1337 ,

see that the invite was successful so would close the issue. 

If further help is needed, feel free to reopen the issue.
