### ISSUE TITLE
DirkBTSINew Tractus-X project contributor

### ISSUE THREAD

**Issue by DirkBTSI** [eclipse-tractusx/sig-infra#420]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: 
Committers, that could take over: 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by tomaszbarwicki** [comment]
Hi @DirkBTSI, no emails have been provided for necessary information, please fill.

**Comment by FaGru3n** [comment]
Hi @DirkBTSI 

following information are needed, please inform us who should be added and who can verify you as person:

## Necessary Information

Email address to add: 
Committers, that could take over:

**Comment by almadigabor** [comment]
Hey @DirkBTSI! Is this issue still relevant? If not, I would just close it.

**Comment by DirkBTSI** [comment]
Email address to add: dirk.brueckner@t-systems.com
Committers, that could take over: %

**Comment by almadigabor** [comment]
Hey @DirkBTSI, I've added you as a project contributor [here](https://projects.eclipse.org/projects/automotive.tractusx/who). If you signed the Eclipse Contributor Agreement you should be able to make contributions to the project now. Let me know if it works then I'll close this issue.

**Comment by DirkBTSI** [comment]
I signed the Eclipse Contributor Agreement
