### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by mm73628486283** [eclipse-tractusx/sig-infra#421]
## Necessary Information

Email address to add: daniel.dilger@mercedes-benz.com
Committers, that could take over: @AngelikaWittek @scherersebastian @SebastianBezold 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by tomaszbarwicki** [comment]
@mm73628486283 you've been added.
