### ISSUE TITLE
Issue with Deploying Second Instance of Application in Argo CD Hotel Budpest

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/sig-infra#423]
## Introduction to problem

We are having problems with deploying one Pod because it says that it arrives the maximum number of pods:
![image](https://github.com/eclipse-tractusx/sig-infra/assets/71728767/da0f8c15-16e5-42d3-ae31-6506458a7ead)

Two weeks ago we had already the second instance up and running and now we tried again to make it work but one of the pods wouldnt start.

**Describe the solution you'd like**  
We want to deploy a second instance from our application for running security tests and testing the application with another url and portal IAM app id.

**Additional context**  

Charts: https://github.com/eclipse-tractusx/digital-product-pass/blob/main/charts/digital-product-pass/values.yaml
Hotel Budapest Catena-X INT environment
Link: ArgoUrl: https://argo.int.demo.catena-x.net/applications/argocd/digital-product-pass-bmw

**Comment by matbmoser** [comment]
Thank you @FaGru3n  for increasing one node in our cluster.
The second problem was solved by configuring the names in another branch: https://github.com/catenax-ng/tx-digital-product-pass/tree/v2.1.1-materialpass 
We found a solution to the problem:
![image](https://github.com/eclipse-tractusx/sig-infra/assets/71728767/dbe81ddc-4be7-42ed-8bc1-688b5847b2c4)

**Comment by FaGru3n** [comment]
Thx for feedback
