### ISSUE TITLE
Clarify and potentially implement auto release generation for tractus-x-release

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/sig-infra#429]
We currently do manual tractus-x releases through tractus-x-release.

With the tickets in sig-release we have in theory all required information from all products etc. This could be a good way to stabilize the release process overall.

AC:
- Discuss with Stephan/Hanno if they like the idea, the implication is that the tickets have to be labled correctly
- If yes, implement it together with them (get feedback from them)

**Comment by FaGru3n** [comment]
Already discussed and will be overtaken by Tractus-X Organisation
