### ISSUE TITLE
Set up test environment STABLE 

### ISSUE THREAD

**Issue by urademac** [eclipse-tractusx/sig-infra#43]
The earlier test environment PRE-PROD is to be used in the future as a test environment for the current release (STABLE)
Thefore the test environment PREP-PROD is to be renamed to STABLE.

The following products with software versions Release 3.1 shall be installed on STABLE:
o	Autosetup Service
o	Digital Product Pass
o	Country Risk
o	Golden Record Business Partner Number (BPN) Service
o	Portal
o	Dynamic Attribute Provisioning Service (DAPS)
o	DAPS Registration Service
o	Digital Twin Registry
o	Eclipse Data Space Connector (EDC)
o	Item Relationship Service (IRS)
o	Manage Identity Wallet (MIW)
o	Simple Data Exchanger (SDE)
o	Self Description (SD) Factory
o	Semantic Hub
o	Trace-X Traceability Application

In addition an extra instance “Generic Data Provider” should be set up with the following products with software versions for Release 3.1:
o	EDC
o	IRS

**Comment by carslen** [comment]
The former PRE-PROD environment will be renamed by System Team in a timely manner. Who will be responsible for the applications on STABLE environment is still in clarification.

**Comment by carslen** [comment]
An additional hint:

As your completely new to GH (Welcome!) and your profile doesn't provide no information about how you are, I was first in doubt about your issue, especially in regards of renaming a environment. So please either identify yourself in a ticket or add some information to your GH profile.

**Comment by carslen** [comment]
Since Ulrike left Test Mgmt team, I'll close this ticket.
