### ISSUE TITLE
Shut down azure clusters

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/sig-infra#431]
If nothing changes and no one is telling us otherwise, shut down all Azure k8s cluster we operate and all VMs (pause them if possible).

AC:
- Shutdown / Pause all Clusters (dev, test, staging, int, core, ...)
- Check all other resources, make sure that all costintensive resources are paused

**Comment by FaGru3n** [comment]
will be done by T-System itself.

FYI @almadigabor @tomaszbarwicki
