### ISSUE TITLE
Send a good bye email

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/sig-infra#432]
Lets leave with style.

Who ever shuts off the lights, please send an email on the mailing list.

AC:
- Send email
- Say good bye from System Team
- Perhaps request Quotes from all of us

**Comment by FaGru3n** [comment]
Good Bye to the Tractus-X Community, 

The last day of the consortia phase of Catena-X has finally come. 

For most of us from the System Team, that means we have to say good-bye. But we want to thank you all for being a part in our community.

It was a pleasure working with you all and supporting you in providing the testing and development infrastructure. For us it was also a really insightful journey and we learned a lot. Providing you with environments, supporting you with new tooling and guiding you on your way to open-source contributions was also new territory for us.

We hope you had fun doing open source and wish you all the best on your continuous efforts.

Sincerely Your System Team & FOSS Team 
 
Sigi, 
Sebastian, 
Angelika, 
Gabor, 
Fabian, 
Harry, 
Carsten, 
Tomasz
