### ISSUE TITLE
Hand over catenax-ng github org

### ISSUE THREAD

**Issue by Siegfriedk** [eclipse-tractusx/sig-infra#434]
We will not need access to that org anymore.

AC:
- Remove all System Team Owners
- Remove them also from catenax
- Make sure known people from Catenax e.v. are owners

**Comment by SebastianBezold** [comment]
Instead of handing over, the org will be deleted

**Comment by FaGru3n** [comment]
Organistation was deleted

> This email is to confirm that the catenax-ng organization has been deleted from GitHub by SebastianBezold.
