### ISSUE TITLE
Tractus-X Release Guidelines  Check for Product IRS 

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-infra#437]
**Is your support request related to a problem? Please describe.**  
- Checks if [Tractus-X Release Guidelines](https://eclipse-tractusx.github.io/docs/release) are fulfilled for product IRS and release [4.5.0](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.5.0)

## Due Date 
- 16.02.2024

## Link 
* Please approve the TRGs here https://github.com/eclipse-tractusx/sig-release/issues/494 

**Describe the solution you'd like**  
- TRG Check is done for product IRS and release [4.5.0](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.5.0)

**Additional context**

**Comment by almadigabor** [comment]
Hey @mkanal! I'm closing this issue and we'll create the QG check issue and link it to the [Release Checks issue](https://github.com/eclipse-tractusx/sig-release/issues/494) soon.
