### ISSUE TITLE
Tractus-X Release Guidelines  Check for Product Trace-X

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-infra#438]
**Is your support request related to a problem? Please describe.**  
- Please check if [Tractus-X Release Guidelines](https://eclipse-tractusx.github.io/docs/release) are fulfilled for  product Trace-X and release [10.3.0](https://github.com/eclipse-tractusx/traceability-foss/releases/tag/10.3.0)

## Due Date 
- 16.02.2024

## Link 
* Please approve the TRGs here https://github.com/eclipse-tractusx/sig-release/issues/506

**Describe the solution you'd like**  
- TRG Check is done for product Trace-X and release [10.3.0](https://github.com/eclipse-tractusx/traceability-foss/releases/tag/10.3.0)

**Additional context**

**Comment by almadigabor** [comment]
Hey @mkanal! I'm closing this issue and we'll create the QG check issue and link it to the [Release Checks issue](https://github.com/eclipse-tractusx/sig-release/issues/506) soon.
