### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by BeFranke** [eclipse-tractusx/sig-infra#439]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub Users:
    Nsonyar
    Moritz72
    mbkma

Vouching person: BeFranke

These are my new colleagues, I can therefore verify that they are members of Catena-X (working @ DLR).

**Comment by FaGru3n** [comment]
Hi @BeFranke could you please verify that the new members are working for Catena-X?

**Comment by BeFranke** [comment]
As written in the OP, I can verify that they are working in Catena-X

**Comment by FaGru3n** [comment]
Hi @BeFranke,

just for verification reasons. And would be great if the real names would be also present on the GitHub profiles. 

@Nsonyar
@Moritz72
@mbkma

were invited. Invitation exists for 7 days and the new users have to be added to a gh-team as well by the maintainer of the gh-team.

Please verify and close the issue afterwards.

**Comment by FaGru3n** [comment]
Hi @BeFranke,

seems for now  all new users have joined the [Catena-X ng](https://github.com/catenax-ng) Org.

Could you please verify and close the issue? 

Thanks in advance.

**Comment by BeFranke** [comment]
I'm sorry for the late reply. All requested user have joined, thank you.
