### ISSUE TITLE
Create sonarcloud project for new team.

### ISSUE THREAD

**Issue by Ruskyy** [eclipse-tractusx/sig-infra#44]
**Is your support request related to a problem? Please describe.**  
As a a requirement from our PO, my team needs to use SonarCloud, as a code review solution.
We were instructed to request this access to Catena.

**Describe the solution you'd like**  
Create pro tx-demand-capacity-mgmt repos. Give access to members of the _product-cgi-dcm-foss_ team.

**Additional context**  
Reference to: https://github.com/eclipse-tractusx/sig-infra/issues/36
Let me know if more information is required.

**Comment by carslen** [comment]
Following repositories have been added to sonarcloud:
- demand-capacity-mgmt
- demand-capacity-mgmt-frontend
- demand-capacity-mgmt-backend

In each repository there is now a Secret available called `SONAR_TOKEN` to use with GH Action/workflow.

To get access to sonarcloud, you've to login to sonarcloud using your GH Account: https://sonarcloud.io/login

**Comment by carslen** [comment]
@Ruskyy please review and close issue.

**Comment by Ruskyy** [comment]
I can confirm its working
