### ISSUE TITLE
R24.03 Digital Product Pass Tractus-X Release Guideline Check

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/sig-infra#440]
## Introduction

I need someone to review the TRG compliance of the Digital Product Pass application:
https://github.com/eclipse-tractusx/digital-product-pass 

Please note that we already created a Ticket, checking and addressing all TRGs:
https://github.com/eclipse-tractusx/digital-product-pass/issues/180 

Release Management Ticket: https://github.com/eclipse-tractusx/sig-release/issues/511

**Comment by SebastianBezold** [comment]
HI @matbmoser,

I'll close this issue, since it is only referencing an already existing issue, that we will work on.
All documentation regarding review is done in eclipse-tractusx/sig-release#511

**Comment by matbmoser** [comment]
@SebastianBezold ok! 

I wanted to make sure we had a ticket like the other teams, to comply with the process :)

Thank you very much
