### ISSUE TITLE
GitHub: New Team for DCMFOSS

### ISSUE THREAD

**Issue by ClosedSourcerer** [eclipse-tractusx/sig-infra#442]
Product GitHub team name: 
DCMFOSS

GitHub users to invite:
jschu1
ClosedSourcerer

Maintainer of the new GitHub Team:
ClosedSourcerer

validation / approved by: jschu1

New Team required because the old Team name has a company name within it. 
Old Team needs to be disbanded at some point.

New Team responsible for the following REPOs: 
https://github.com/eclipse-tractusx/demand-capacity-mgmt
https://github.com/catenax-ng/tx-demand-capacity-mgmt

**Comment by jschu1** [comment]
Approved @ClosedSourcerer 
Danke!

**Comment by carslen** [comment]
This ticket needs some internal clarification (System Team + FOSS), as to my knowledge the code will be made Eclipse-Tractus-X compliant (TRGs, legal stuff, etc.) and afterwards the repo is going to be archived as there will be no further development effort. Maybe there has been things changed, since I was a couple of days off.

If a new team will be created, the name will be _product-dcm-foss_. Maybe it's worth renaming the existing team instead of creating a new one, but that's not a final desicion yet.

**Comment by AngelikaWittek** [comment]
@carslen This is exactly what I know. We need clarification. Also about the status on this  [branch](https://github.com/eclipse-tractusx/demand-capacity-mgmt/tree/consortia-cleanup).

**Comment by ClosedSourcerer** [comment]
> If a new team will be created, the name will be _product-dcm-foss_. Maybe it's worth renaming the existing team instead of creating a new one, but that's not a final desicion yet.

I am fine with renaming the existing team. However the current team owner told me he could not change the name.

**Comment by SebastianBezold** [comment]
> > If a new team will be created, the name will be _product-dcm-foss_. Maybe it's worth renaming the existing team instead of creating a new one, but that's not a final desicion yet.
> 
> I am fine with renaming the existing team. However the current team owner told me he could not change the name.

Hi @ClosedSourcerer,

we can take over renaming for you. Then we also do not have to maintain the ownership of repos. 
Will you be continuing the DCM efforts in Tractus-X?

**Comment by ClosedSourcerer** [comment]
> we can take over renaming for you. Then we also do not have to maintain the ownership of repos. Will you be continuing the DCM efforts in Tractus-X?

@SebastianBezold 
Effort is a high an mighty word considering the circumstances, but yes I will attempt to prevent this from drowning and having wasted a 6 figure investment...

Considering that everyone who is currently part of that team will be off-boarding on friday.
Yeah that is the plan, for now.

However the Ownership of the Depo needs to changed as well, because the current owner will off-board on friday.

**Comment by SebastianBezold** [comment]
Ok understood. So my suggestion would be the following. 
I will rename the existing team to get rid of company names. This was anyway never intended.
Second, I will add you to the team and grant you the team maintainer role. 
This way you can on- and offboard members to the team.
Repo ownership (or better permissions) are always granted to teams and not individuals, so I don't see an issue there.

Would that work for you @ClosedSourcerer

**Comment by ClosedSourcerer** [comment]
@SebastianBezold 
That should work nicely. Thank you.

**Comment by SebastianBezold** [comment]
Hi @ClosedSourcerer,

finally found the time to actually do that.
You are now maintainer of the renamed team [product-dcm](https://github.com/orgs/catenax-ng/teams/product-dcm)
Please check, if you now have access to all the repos you need and close the issue if nothing is missing

**Comment by SebastianBezold** [comment]
Closing for now. Feel free to re-open, if there are additional topics, that we missed
