### ISSUE TITLE
GitGuardian Test Creadentials

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/sig-infra#443]
**Is your support request related to a problem? Please describe.**  
GitGuardian reports secrets in a PR https://github.com/eclipse-tractusx/item-relationship-service/pull/427
These secrets are created for Tests and only used there.

**Describe the solution you'd like**  
Please mark these secrets as test credentials.

**Additional context**

**Comment by FaGru3n** [comment]
Hi @ds-jhartmann is it ok for you to raise a request for the security team within [sig-security](https://github.com/eclipse-tractusx/sig-security)?
