### ISSUE TITLE
Create a repository (ontology models) for the reference implementation of the CX-0067 standard

### ISSUE THREAD

**Issue by obalandi** [eclipse-tractusx/sig-infra#446]
Repo name: ontology-models 

Purpose: The reference implementation of the CX-0067 standard (ontology models for realising federated queries in Catena-X) is currently in the Catena-X NG repository (https://github.com/catenax-ng/product-ontology). We need to move it to tractusx. It is also part of CX-0084 (https://github.com/eclipse-tractusx/knowledge-agents). The repository contains ontologies and taxonomies as TTL files, as well as some python scripts for automated documentation and visualisation generation and ontology merging.

Responsible: @obalandi @bosserf @drcgjung

**Comment by almadigabor** [comment]
Hey @obalandi @maximilianong, the repo is created and you can start your contributions there. https://github.com/eclipse-tractusx/knowledge-agents-ontology
