### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#447]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User:
@msinamci

Vouching person: 

@evegufy @jjeroch

**Comment by FaGru3n** [comment]
Hi @evegufy and @jjeroch ,

could you validate that @msinamci will be part of Catena-X?

Thanks in advance.

**Comment by evegufy** [comment]
Hi @FaGru3n yes, she's part of CX

**Comment by FaGru3n** [comment]
Hi all,

invite was sent:
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/9959e404-6fce-4afb-abea-e406650a13f5)

and a warm welcom to @msinamci 👋🏼 

Please make sure, that you accept the invitation you receive from GitHub, after you can be added in the desired [github-team](https://github.com/orgs/catenax-ng/teams) for access.

**Comment by FaGru3n** [comment]
Hi @evegufy i think @msinamci joined the github organisation, would you be so kind and invite her to the desired gh-team for catena-x then i would close the issue if your fine with it.

Thanks in advance.
