### ISSUE TITLE
Archive repository "managed-identity-wallets-archived"

### ISSUE THREAD

**Issue by AngelikaWittek** [eclipse-tractusx/sig-infra#450]
Repo name: 

[managed-identity-wallets-archived](https://github.com/eclipse-tractusx/managed-identity-wallets-archived)

Purpose:

This repo is not active any more, please archive.
The announcement was on the [mailing list](https://www.eclipse.org/lists/tractusx-dev/msg00347.html), no veto was spoken.

Responsible: 
@OSchlienz  @AngelikaWittek

**Comment by FaGru3n** [comment]
Hi @AngelikaWittek 

should we update the repos `README.md` with the currenct proposal text? 

> "This repository is currently not under active maintenance and therefore archived. If you plan on picking up this product again, feel free to reach out ot the Eclipse Tractus-X projects leads via mailing list"

**Comment by FaGru3n** [comment]
Hi @AngelikaWittek and @OSchlienz created a little PR to approve the changes on the readme for this repo.

https://github.com/eclipse-tractusx/managed-identity-wallets-archived/pull/48

**Comment by FaGru3n** [comment]
Repo was updated and archived, please review and reopen the issue if further infos are needed. 

FYI @AngelikaWittek @OSchlienz
