### ISSUE TITLE
Cannot create more than 3 APIs on SwaggerHub

### ISSUE THREAD

**Issue by ds-lcapellino** [eclipse-tractusx/sig-infra#455]
**Is your support request related to a problem? Please describe.**  

We from Trace-X want to publish our Swagger on SwaggerHub like other projects: https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot
But when trying to publish it with a GitHub Action, we receive the following error message: 

![313699479-cb061638-d76a-43ae-a11f-c20367be1e5e](https://github.com/eclipse-tractusx/sig-infra/assets/137265091/ac1fe795-6469-48f0-9fcd-5283ed765c2b)

**Describe the solution you'd like**  

We want to provide our OpenApi/Swagger specification on https://app.swaggerhub.com/search?owner=eclipse-tractusx-bot

**Additional context**

**Comment by SebastianBezold** [comment]
Hey @ds-lcapellino,

could you please provide us with links to the failing worklfow run?
I am currently guessing, you mean this one here https://github.com/eclipse-tractusx/traceability-foss/actions/workflows/publish-swagger-hub.yml, but I cannot see any run there

**Comment by tomaszbarwicki** [comment]
Hi @Siegfriedk, looks like we have a 3 APIs limitation on the swaggerhub within existing plan and @ds-lcapellino is unable to publish their cause it's been already reached. Can you please advise?

**Comment by Siegfriedk** [comment]
@tomaszbarwicki pls create a ef ticket / talk to Fred gurr.

**Comment by tomaszbarwicki** [comment]
EF issue created: https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4443

**Comment by tomaszbarwicki** [comment]
Hi @ds-lcapellino, EF referred me to a simillar issue from our organisation https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4197
Seems there is not much that can be done...

**Comment by FaGru3n** [comment]
FYI:

> Inofo from SmartBear: they are unable to increase our API limit, and are otherwise unable to help. They did suggest we get a paid subscription, which would run us just above 1kEUR/year. We will discuss this further among the committers

so we are working on an other solution within issue https://github.com/eclipse-tractusx/sig-infra/issues/376

With that i would close this issue here for now... if we have further updates we would inform the committer round within our open meetings.

@ds-lcapellino feel free to get in contact with all of our committers for an update or feedback.

Thanks in advance.
