### ISSUE TITLE
Having NVD API Key for eclipse-tractusx organization within the secrets

### ISSUE THREAD

**Issue by ds-mwesener** [eclipse-tractusx/sig-infra#459]
**Is your support request related to a problem? Please describe.**  

Dependency check takes very long without api key.
![image](https://github.com/eclipse-tractusx/sig-infra/assets/124587888/7da5b032-ea81-46d3-bd7e-a1151be11c87)

**Describe the solution you'd like**  

Adding an api key either for the project repository or the organization into the secrets.
https://nvd.nist.gov/general/news/API-Key-Announcement

**Additional context**  

Please find an example run: https://github.com/eclipse-tractusx/traceability-foss/actions/runs/8353452321/job/22865193054

**Comment by tomaszbarwicki** [comment]
Hi @ds-mwesener , I think EF can help with that, suggest to create an EF gitlab issue to request API key..

**Comment by ds-mwesener** [comment]
https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4457

**Comment by ds-mwesener** [comment]
Would it be possible to also add a secret to the catena project: https://github.com/catenax-ng/tx-traceability-foss

I know we soon want to fully migrate but as long as this process is not completed it would be a big benefit for us. I already have an API key which could be set at least for tx-traceability-foss.

Thanks in advance: @tomaszbarwicki

**Comment by tomaszbarwicki** [comment]
@ds-mwesener sure thing can add, is it in vault? what is the key and how do you prefer to name the secret in repo?

**Comment by FaGru3n** [comment]
Hi @ds-mwesener any update on this, i guess @netomi gave you a little update on https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/4457
