### ISSUE TITLE
New Tractus-X project contributor @rogocof

### ISSUE THREAD

**Issue by rogocof** [eclipse-tractusx/sig-infra#460]
## Necessary Information

Email address to add: robin.gottschalk@cofinity-x.com
Committers, that could take over: @jzbmw @mkanal 
Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

I was already added to contributor's list but my membership was revoked:

![image](https://github.com/eclipse-tractusx/sig-infra/assets/158559825/07817ffb-7bee-41d2-88de-1eb72ae0ebdf)

**Comment by FaGru3n** [comment]
Invite was sent again, please checkout if permissions are back again and close the issue.

Thanks in advance.

**Comment by FaGru3n** [comment]
will close the issue,  feel free to contact us again if you have still no access or not the needed permission.
