### ISSUE TITLE
Contributor role has been removed

### ISSUE THREAD

**Issue by dvasunin** [eclipse-tractusx/sig-infra#462]
### Necessary Information
Email address to add: dmitrii.vasiunin@t-systems.com
Committers, that could take over: @almadigabor @FaGru3n
GitHub username: dvasunin

I was a contributor already but my role was revoked just now. I've got email:

You’ve been removed from the "automotive-tractusx-contributors" team on the "Eclipse Tractus-X" organization.

Cheers & Octocats,
GitHub Support

**Comment by FaGru3n** [comment]
Invite was sent again
