### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by Grand-Thibault** [eclipse-tractusx/sig-infra#463]
## Necessary Information

Email address to add: thibault.grandemenge@catena-x.net
Committers, that could take over: @stephanbcbauer

**Comment by SebastianBezold** [comment]
Hi @Grand-Thibault,

I added you to the list of contributors. If you singed your ECA and linked your GitHub profile in the socials section of your Eclipse Foundation profile, you should receive an invitation to the eclipse-tractusx org soon.

Feel free to close this issue as soon as you got the invite

**Comment by FaGru3n** [comment]
Hi @Grand-Thibault,

did the process worked and we can close the issue?

**Comment by Grand-Thibault** [comment]
Process worked, Ticket closed
