### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by stanfaldin** [eclipse-tractusx/sig-infra#464]
## Necessary Information

Email address to add: Stan.faldin@catena-x.net
Committers, that could take over: @stephanbcbauer 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by FaGru3n** [comment]
Hi @stanfaldin,

did you already created an Eclipse Account with the same emailadress because with mailadress we got the following error trying to add you as contributor.

> Contributors: found no valid user with that name.

**Comment by stanfaldin** [comment]
Hi @FaGru3n, 
thanks for the advise, now the eclipse account ist created too. 

Many thanks.

**Comment by FaGru3n** [comment]
Added you as contributor within the Eclipse Tractus-X project.

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

Afterwards please review this issue and close it. Thanks in advance.

**Comment by FaGru3n** [comment]
Hi @stanfaldin  does the process worked?

**Comment by FaGru3n** [comment]
Hi @stanfaldin,

will close the issue if you have further questions feel free to reopen the issue.
