### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by MWADCM** [eclipse-tractusx/sig-infra#468]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: Markus.WE.Wagner@bmw.de
Committers, that could take over: @grand-Thibault

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by FaGru3n** [comment]
Hi @MWADCM, 

@Grand-Thibault have not the committer permissions to our project, so i will overtake here.

I added you with [Markus.WE.Wagner@bmw.de](mailto:Markus.WE.Wagner@bmw.de) to our project.

> Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

If you can see the GitHub Tractus-X Organisation Logo under you personal GitHub profile the process should be successful.

Please verify and close the issue afterwards.

**Comment by MWADCM** [comment]
done
