### ISSUE TITLE
New Tractus-X project contributor Lukas Schmetz

### ISSUE THREAD

**Issue by LukasSchmetz** [eclipse-tractusx/sig-infra#469]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add:  lukas.schmetz@henkel.com
Committers, that could take over:  @Grand-Thibault 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by FaGru3n** [comment]
Hi @LukasSchmetz,

unfortunatly @Grand-Thibault can not add you as a contributor, because of missing committer permiossions to our Eclipse project.

Should i overtake? But @Grand-Thibault could verify that you will be a member of the organisation.

Thanks in advance.

**Comment by FaGru3n** [comment]
Hi @LukasSchmetz 

added you into our project. 

> Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

Please review and close the issue afterwards.

Thanks in advance.

**Comment by FaGru3n** [comment]
Hi @LukasSchmetz i think it worked so will close the issue.

**Comment by LukasSchmetz** [comment]
Thank you for your help @FaGru3n . Works fine for me.
