### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by galyshann** [eclipse-tractusx/sig-infra#470]
Dear commiters, could you please invite me to CX members as a member of IDS&GDS teams (SDF/SDE/MSO)

Eclipse user: anna.galysheva@t-systems.com

GitHub User: @galyshann

Commiters:@almadigabor @FaGru3n

@ciprianherciu please verify that I am part of the team

**Comment by ciprianherciu** [comment]
I can confirm @galyshann is part of the team

**Comment by galyshann** [comment]
Hi @tomaszbarwicki,  thank you, I was added to **Catena-X (ng)** organization. 
Could you please add me also to **Eclipse Tractus-X**  for being able to create **Projects** for our products

**Comment by FaGru3n** [comment]
Hi @galyshann also added you into our Eclipse Tractus-X project.

![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/4cf1a0dc-566d-4e3a-afc1-caf18288a690)

> Please make sure, that you accept the invitation you receive from GitHub for Eclipse Tractus-X, after you have been added as project contributor.

If you can see the logo for the org under you personal profile should be successful.

Please review and close the issue afterwards.

**Comment by galyshann** [comment]
Hi @FaGru3n thank you! 
I can see the logo and created the [Project](https://github.com/orgs/eclipse-tractusx/projects/59), but still can`t Link it to our repositories. What should be done for that?

**Comment by FaGru3n** [comment]
Your welcome...

Hmm did not get your point what you try to achive with linking a GitHub project and  an repository?

If you want to have more issues from the repo on your project then only some more issue could be assigned to the GitHub Project... so created a little [demo issue](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend/issues/132) for that in the repo itself.

**Comment by FaGru3n** [comment]
Ah thanks for clarification... 😉  one point i also did not know thanks but guess some more permissions are needed to modify the projects within repositories. your current permission is the triage permission like described in [contributor permissions](https://eclipse-tractusx.github.io/docs/oss/contributor-committer#official-project-contributor)

So for now, i linked the organisation project directly into your repository as repository project.

![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/c7b37277-5ed8-418e-84b7-d81f605ff278)

Please verify and close the issue, thanks in advance.

**Comment by galyshann** [comment]
Exactly! Thank you, @FaGru3n!
May I ask you to do the same for 
Project: [SD-Factory](https://github.com/orgs/eclipse-tractusx/projects/60) link to Repo: https://github.com/eclipse-tractusx/sd-factory

and MSO:

Project: https://github.com/orgs/eclipse-tractusx/projects/63 and Repo: https://github.com/eclipse-tractusx/managed-service-orchestrator

**Comment by FaGru3n** [comment]
Hi @galyshann also done.

Please review and close the issue afterwards.
