### ISSUE TITLE
Repository for CSV upload tool / app for business partner data

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/sig-infra#475]
Repo name: bpdm-upload-tool

Purpose: This repository is for a reference implementation that will enable users to upload business partner data via .CSV file to the data space in an easy way.

Responsible: @SujitMBRDI / @nicoprow / + Florian K. from ZF

**Comment by maximilianong** [comment]
@jjeroch / @wernerroman FYI

**Comment by stephanbcbauer** [comment]
@maximilianong  Sounds good. I am not sure what is expected right now. Do you create the PR for creating the repository? https://eclipse-tractusx.github.io/docs/oss/issues/#create-manage-a-repository-in-eclipse-tractusx

**Comment by maximilianong** [comment]
@stephanbcbauer For creating a repository one project lead needs to give a 👍 

But I hope someone from system team will take the part of creation :D maybe @Siegfriedk or @SebastianBezold

**Comment by almadigabor** [comment]
Hi @maximilianong! I'll take over the creation of the repo. Do you need github pages enabled for hosting a static site or do you plan releasing a helm chart for this product?

**Comment by maximilianong** [comment]
@almadigabor first of all, thanks for taking this task. Helm charts yes, GitHub pages no :)

**Comment by almadigabor** [comment]
I'll enable github pages then, we use that feature to host the repo's own helm repository for the released charts via a chart-releaser workflow.

**Comment by almadigabor** [comment]
[Here](https://github.com/eclipse-tractusx/.eclipsefdn/pull/72) it the PR that will create the repo. An approval from a project lead is needed.

**Comment by maximilianong** [comment]
> [Here](https://github.com/eclipse-tractusx/.eclipsefdn/pull/72) it the PR that will create the repo. An approval from a project lead is needed.

@stephanbcbauer is also project lead and approved this issue already but maybe he can give a thumbs up again on the PR :D

**Comment by almadigabor** [comment]
Hey @maximilianong! The PR is merged, the repo should appear in an hour or so. Let me know if we can close this issue.

**Comment by maximilianong** [comment]
@almadigabor thank you very much! Its already there.
