### ISSUE TITLE
Create repo emergingtechnologies

### ISSUE THREAD

**Issue by felixatdlr** [eclipse-tractusx/sig-infra#486]
Repo name: emergingtechnologies   (Link needs to be **https://github.com/eclipse-tractusx/emergingtechnologies**)

Purpose: Publication of emerging technologies for the Tractus-X project

Responsible: Felix Hanke, @felixatdlr

**Comment by FaGru3n** [comment]
Hi @felixatdlr added the PR but think need an approval from out project leads.

**Comment by felixatdlr** [comment]
Push

**Comment by FaGru3n** [comment]
Rerequested the approval at least we have one 👍🏼  for creating this new repo... will keep you up to date.

**Comment by FaGru3n** [comment]
repo was created: https://github.com/eclipse-tractusx/emergingtechnologies please have a look into the legal docs within our repos https://eclipse-tractusx.github.io/docs/release/trg-7/trg-7-01
