### ISSUE TITLE
GitHub: New fork 

### ISSUE THREAD

**Issue by adkumar1** [eclipse-tractusx/sig-infra#49]
1. repository name within Tractus-X Organisation: 
[managed-simple-data-exchanger](https://github.com/eclipse-tractusx/managed-simple-data-exchanger)

repository name within Catena-X NG Organisation: 
tx-managed-simple-data-exchanger

2. repository name within Tractus-X Organisation: 
[managed-service-orchestrator](https://github.com/eclipse-tractusx/managed-service-orchestrator )

repository name within Catena-X NG Organisation: 
tx-managed-service-orchestrator

3. repository name within Tractus-X Organisation: 
[managed-simple-data-exchanger-backend](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-backend)

repository name within Catena-X NG Organisation: 
tx-managed-simple-data-exchanger-backend

4. repository name within Tractus-X Organisation: 
[managed-simple-data-exchanger-frontend](https://github.com/eclipse-tractusx/managed-simple-data-exchanger-frontend)

repository name within Catena-X NG Organisation: 
tx-managed-simple-data-exchanger-frontend

GitHub team to grant access: 
product-essential-services

**Comment by hzierer** [comment]
Hi @adkumar1,

1. created a new fork: https://github.com/catenax-ng/tx-managed-simple-data-exchanger
2. renamed existing fork from "catenax-ng/tx-autosetup-backend" -> https://github.com/catenax-ng/tx-managed-service-orchestrator
3. renamed existing fork from "catenax-ng/tx-dft-backend" -> https://github.com/catenax-ng/tx-managed-simple-data-exchanger-backend
4. renamed existing fork from "catenax-ng/tx-dft-frontend" -> https://github.com/catenax-ng/tx-managed-simple-data-exchanger-frontend

Cheers Harry
