### ISSUE TITLE
Vault not accessible (network issues)

### ISSUE THREAD

**Issue by ds-mwesener** [eclipse-tractusx/sig-infra#495]
**Is your support request related to a problem? Please describe.**  

**Describe the solution you'd like**  

Today I was logged out of the vault, when trying to log in the error from the screenshot appears and login is not possible.
Our application can also not consume any secret from the vault.

![image](https://github.com/eclipse-tractusx/sig-infra/assets/124587888/52b2a9cf-db0b-4199-bbf0-371be356c9ae)

**Additional context**

**Comment by carslen** [comment]
Vault is back in business. Please check.

**Comment by evegufy** [comment]
Works again, thank you!

**Comment by carslen** [comment]
@ds-mwesener ok2close for you as well?
