### ISSUE TITLE
[14.06.2024 (EOB)] Set catenax-ng tx-item-relationship-service to read-only 

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-infra#496]
**Is your support request related to a problem? Please describe.**  
- with the end of the consortium, we will delete the [Catena-X NG GitHub](https://github.com/catenax-ng) organization

**Describe the solution you'd like**  
- Set https://github.com/catenax-ng/tx-item-relationship-service as read-only

**Additional context**  
- Set  read-only 14.06.2024 (EOB) not earlier,

**Comment by FaGru3n** [comment]
Hi @mkanal thanks for the hint, but we do not need separate issues for the Catena-X NG deletion or read-only schedule, so will close the issue.  😉
