### ISSUE TITLE
[26.07.2024 (EOB)] Delete catenax-ng tx-traceability-foss  repos

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-infra#498]
**Is your support request related to a problem? Please describe.**  
- with the end of the consortium, we will delete the [Catena-X NG GitHub](https://github.com/catenax-ng) organization

**Describe the solution you'd like**  
- Delete https://github.com/catenax-ng/tx-traceability-foss/

**Additional context**  
- Delete repos on 26.07.2024 (EOB)

**Comment by FaGru3n** [comment]
Hi @mkanal thanks for the hint, but we do not need separate issues for the Catena-X NG deletion or read-only schedule, so will close the issue.  😉
