### ISSUE TITLE
Docker Hub Authentication Issue: Unable to Push Images Due to Missing Username and Password

### ISSUE THREAD

**Issue by fabiodmota** [eclipse-tractusx/sig-infra#50]
Please report **undisclosed** or **confidential** vulnerabilities here: https://www.eclipse.org/security/

**Topics (Please mark an [x] to your Topic):**
- [ ] KICS
- [ ] Invicti
- [ ] GitGuardian
- [ ] Pentesting
- [ ] Security assessment (threat modeling, code reviews)
- [ ] Trivy
- [ ] Veracode (initial setup, GitHub integration)
- [x ] Other

I am currently facing an issue with Docker Hub where I am unable to push images due to missing username and password. This problem is occurring in the GitHub actions workflow of my project, specifically in the job with ID 9216657510. 
The error details can be found at the following URL: https://github.com/catenax-ng/tx-bpdm/actions/runs/5124606692/jobs/9216657510

The error message indicates that the Docker push command is not receiving the necessary authentication credentials. As a result, the push operation to Docker Hub fails. I would appreciate any assistance in resolving this issue.

project repo: https://github.com/catenax-ng/tx-bpdm

**Comment by carslen** [comment]
Please use appropriate issue templete for your topic, this one was the wrong one ;)

All information you need to know are documented in [TRG 4.04](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-04) and [4.05](https://eclipse-tractusx.github.io/docs/release/trg-4/trg-4-05). And keep in mind, that the required secrets to use Docker Hub are only available in Eclipse-Tractusx repositories, not in Catenax-NG. You need to build your Docker images in Eclipse-TractusX to push them to Docker Hub.

**Comment by FaGru3n** [comment]
Hint @fabiodmota Maybe this [issue template](https://github.com/eclipse-tractusx/sig-infra/issues/new?assignees=&labels=support&projects=&template=support-general-requirement.md&title=) would fit for any support related problem for the next time, but thanks for using it 😉

**Comment by fabiodmota** [comment]
Hi @carslen  @FaGru3n  yes I didn't know which template to use, so I tried to fill out the template in question as best I could, however, it's about the problem, could you help me?
at this link https://github.com/eclipse-tractusx/bpdm/actions/runs/5133610306/jobs/9236432965
I now have the pipeline in eclipse and it gives me a username and password error.

**Comment by fabiodmota** [comment]
Any updates on this ?

**Comment by carslen** [comment]
Today's image builds did run. But: You are not publishing your images to `hub.docker.com` but to `ghcr.io`. Don't know if you used "Docker Hub" as a synonym for the GH container registry (ghcr.io)?

If you want to publish the images to Docker Hub you can find all releated informations in the above linked TRGs.

**Comment by fabiodmota** [comment]
@carslen  Where did you see that? I'm using a branch that I left in the error link that publishes to both places and fails on docker login, so I'm not understanding what I have to do

**Comment by carslen** [comment]
You have to run the workflow in the upstream repository, not in the fork. The fork hasno access to secrets available in the upstream due to security reasons, as the fork and the upstream are in different GH organizations.

To be clear: The workflow to publish images on Docker Hub must be executed in the upstream repository (https://github.com/eclipse-tractusx/bpdm), not in the fork. In the fork you can only publish to ghcr.io (or any other container registry you have credentials for). 

https://github.com/catenax-ng/tx-bpdm/blob/c785c73dea347e3b038867d7530bbde29edda859/.github/workflows/build-docker.yaml#L91-L92

These two secrets are not available in GH org catenax-ng (this is where your fork lives) but in the upstream repository.

**Comment by carslen** [comment]
> Do I need to get this branch merged into the main branch at Eclipse before the workflow can run successfully? 

Exactly. In addition, ensure that your toplevel `README.md` file contains a valid _Notice for Docker images_ (TRG 4.06).

**Comment by fabiodmota** [comment]
So on this case is it good to run it like this 
https://github.com/eclipse-tractusx/bpdm/actions/runs/5153783220 ?

**Comment by carslen** [comment]
Is there a reason for this additional env settings in your workflow file?

<img width="480" alt="grafik" src="https://github.com/eclipse-tractusx/sig-infra/assets/28647218/1cea5a54-2868-4d73-b794-c6b546ead9d1">

These should not be required in none of the steps.

You're missing the `DOCKER_NOTICE-md` file in that branch, too:

<img width="735" alt="grafik" src="https://github.com/eclipse-tractusx/sig-infra/assets/28647218/36152a20-386d-4eeb-95f1-385a9d2c8a1a">

Please follow the recommended settings provided in TRG 4.05 for pushing images to Docker Hub.

**Comment by fabiodmota** [comment]
Hello, yes, we have already received feedback and were asked to change the way secrets are invoked. You can check here the ticket that was opened https://gitlab.eclipse.org/eclipsefdn/helpdesk/-/issues/3247. The changes are already made but they are still on the Catena-X fork because I cannot yet pull them to the Eclipse side until the committer does it

**Comment by carslen** [comment]
OK. I wasn't aware of the fact, that the secrets aren't inherited to all workflows when using reusable workflows.

**Comment by fabiodmota** [comment]
I will keep you updated on this

**Comment by carslen** [comment]
Any updates? I'd like to get this issue to an end if it works as expected.

**Comment by fabiodmota** [comment]
Yes sorry for the late notice , we can already see the images there https://hub.docker.com/r/tractusx/bpdm-pool
