### ISSUE TITLE
New Tractus-X project contributor - Dhirender Singh 

### ISSUE THREAD

**Issue by dhiren-singh-007** [eclipse-tractusx/sig-infra#501]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: dhirender.singh@cofinity-x.com
Committers, that could take over: @evegufy @FaGru3n 

I will be working as Portal backend developer from Cofinity-X GMBH

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by FaGru3n** [comment]
Hi @dhiren-singh-007 

just invited you as contributor to our project.

![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/d9d7fe6a-bb5b-460a-a6cc-1e2c1d393727)

> Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by FaGru3n** [comment]
Afterwards, please review this issue and close it by yourself, when access is given.

**Comment by dhiren-singh-007** [comment]
Thank you @FaGru3n
