### ISSUE TITLE
Add GH Secret

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/sig-infra#503]
Please add the following secret to the GitHub secrets for the project https://github.com/catenax-ng/tx-item-relationship-service

secret name: IRS_CUCUMBER_PUBLISH_TOKEN
secret value: please take the value from https://vault.demo.catena-x.net/ui/vault/secrets/traceability-irs/show/IRS_CUCUMBER_PUBLISH_TOKEN#token

**Comment by FaGru3n** [comment]
Hi @ds-jhartmann 

added it to https://github.com/catenax-ng/tx-item-relationship-service as repo secret

![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/08076380-a9d1-4274-abad-21dd17ab0315)

**Comment by FaGru3n** [comment]
Please review and close the issue afterwards.

**Comment by ds-jhartmann** [comment]
@FaGru3n thanks, but I just noticed I did a copy-paste mistake. 
The repository should be the upstream https://github.com/eclipse-tractusx/item-relationship-service. 
Could you please add it there and remove it from catenax-ng

**Comment by SebastianBezold** [comment]
Hi @ds-jhartmann,

like mentioned in #505, we do not have admin privileges in eclipse-tractusx and you need to get in contact with the Eclipse Foundation

**Comment by FaGru3n** [comment]
Hi @ds-jhartmann should we then close this issue, because of the fact the we can not enable secrets within eclipse-tractusx GitHub Org as @SebastianBezold mentioned?
