### ISSUE TITLE
Add GH secrets

### ISSUE THREAD

**Issue by ds-jhartmann** [eclipse-tractusx/sig-infra#505]
Please add the following secrets to the GitHub secrets for the project https://github.com/eclipse-tractusx/item-relationship-service

secret name: DEV_REGULAR_USER_API_KEY
secret value: please take the value from https://vault.demo.catena-x.net/ui/vault/secrets/traceability-irs/show/dev/irs#apiKeyRegular

secret name: DEV_ADMIN_USER_API_KEY
secret value: please take the value from https://vault.demo.catena-x.net/ui/vault/secrets/traceability-irs/show/dev/irs#apiKeyAdmin

Thank you

**Comment by SebastianBezold** [comment]
Hi @ds-jhartmann,

we cannot create secrets in eclipse-tractusx. You would need to open an Eclipse Foundation help desk ticket.
I think you can discuss with them, how to share the values secretly
