### ISSUE TITLE
INT and DEV cluster | node(s) exceed max volume count

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#506]
**Is your support request related to a problem? Please describe.**  

The following error is observed on the INT and Cluster, AFAIK since a couple of hours:
0/8 nodes are available: 1 node(s) exceed max volume count, 1 node(s) had volume node affinity conflict, 6 Insufficient cpu. preemption: 0/8 nodes are available: 1 Preemption is not helpful for scheduling, 7 No preemption victims found for incoming pod..

Affected applications on INT which I'm aware of: BDRS, centralidp (v2), bpndiscovery service

**Describe the solution you'd like**  

 
Please adjust resources

**Comment by carslen** [comment]
Hey Evelyn, 
we've increased the recourses on INT and the pods has been scheduled successfully, although the cluster should have had enough resources to schedule new recources. Maybe it's because of 81 Postgres pods on INT uses the same `podAntiAffinity` setup (except of `app.kubernetes.io/instance`)

![Image](https://github.com/eclipse-tractusx/sig-infra/assets/28647218/3402d72e-e76d-4b77-96a6-9a3ee61556c6)

On DEV we couldn't find any progressing pods, does the error still persist on DEV?

**Comment by evegufy** [comment]
> Hey Evelyn, we've increased the recourses on INT and the pods has been scheduled successfully, although the cluster should have had enough resources to schedule new recources. Maybe it's because of 81 Postgres pods on INT uses the same `podAntiAffinity` setup (except of `app.kubernetes.io/instance`)
> 
> ![Image](https://private-user-images.githubusercontent.com/28647218/338878435-3402d72e-e76d-4b77-96a6-9a3ee61556c6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxODQxNTQsIm5iZiI6MTcxODE4Mzg1NCwicGF0aCI6Ii8yODY0NzIxOC8zMzg4Nzg0MzUtMzQwMmQ3MmUtZTc2ZC00Yjc3LTk2YTYtOWEzZWU2MTU1NmM2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDA5MTczNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTNkNDcyZWRkNmVhNWFjZmExMTcxOTc5Y2UxNWQzYTc4YWY2N2ZlMzE5YmNkZTAyZjgzNjAyNDEwNWY5M2VhYzUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.MQ7P3VhbS3b--GGibJjoGfKx4Tm0adl6O-07v4jsQFA)
> 
> On DEV we couldn't find any progressing pods, does the error still persist on DEV?

@carslen Thank you! INT seems healthy again.

I might have judged too early that exactly the same error caused the issue also on DEV. I just checked again, and on DEV some applications went into an CrashLookBackOffConfigError due to suddenly missing secrets:

![image](https://github.com/eclipse-tractusx/sig-infra/assets/46191613/6c8f41bb-0190-4992-8e27-9ce9cc6c82fc)

I manually synced the the secrets just now, and the apps are up again.

**Comment by evegufy** [comment]
issue resolved
