### ISSUE TITLE
New Product Digital Product Pass in Argo CD Association

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/sig-infra#507]
Product name: product-digital-product-pass
GitHub users to invite: @matbmoser (already in Catena-X eV) @saudkhan116 @jocbra
Validation / approved by: @matbmoser 

including new GitHub-team, ArgoCD and Vault

All members are from CGI actual member of association and co-lead of DPP expert group.
If further members are needed it will be further requested

Repository is not needed, work will be done with Tractus-X: https://github.com/eclipse-tractusx/digital-product-pass/ 

We need to test our functionalities to be release in the v24.08.

**Comment by stephanbcbauer** [comment]
@matbmoser [product-digital-product-pass](https://github.com/orgs/catenax-eV/teams/product-digital-product-pass) was created

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/cf62d89c-de96-4298-a316-0d1a6ef2855d)

One pending member

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/6123642a-fc76-455a-ae1a-cfee716f2153)

**Comment by matbmoser** [comment]
Thank you very much!

**Comment by matbmoser** [comment]
Pending Vault configuration for KV:
![image](https://github.com/eclipse-tractusx/sig-infra/assets/71728767/61697c98-11d7-4ec7-996c-2e5889c0b2aa)

**Comment by ds-asmierzchalski** [comment]
Access to ArgoCD and Vault is now granted.

**Comment by matbmoser** [comment]
![image](https://github.com/eclipse-tractusx/sig-infra/assets/71728767/737a338e-6057-4759-a672-8df1ed2c7bf8)
The certificates are not working for us:

![image](https://github.com/eclipse-tractusx/sig-infra/assets/71728767/ce338a26-fc02-45e3-98da-f5adf9262fb3)

**Comment by ds-lcapellino** [comment]
Hello @matbmoser,
maybe the communication was a bit misleading here. Every ingress needs a unique secretName. In your case, you would need for e.g.
secretName: tls-secret-digital-product-pass-backend for dpp-backend ingress
and 
secretName: tls-secret-digital-product-pass-frontend for dpp-frontend ingress.

Sorry for the confusion.
