### ISSUE TITLE
New Product Digital Twin Registry

### ISSUE THREAD

**Issue by agg3fe** [eclipse-tractusx/sig-infra#509]
Product name: Digital Twin Registry
GitHub users to invite: @agg3fe @tunacicek @thomas-henn 
Validation / approved by: @thomas-henn 

including new GitHub-team, ArgoCD and Vault

Repository is not needed, work will be done with Tractus-X: https://github.com/eclipse-tractusx/sldt-digital-twin-registry
We need to test our functionalities to be release in the v24.08.

If possible, also please copy the Vault values from https://vault.demo.catena-x.net/ui/vault/secrets/semantics

**Comment by stephanbcbauer** [comment]
@agg3fe [product-digital-twin-registry](https://github.com/orgs/catenax-eV/teams/product-digital-twin-registry) was created

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/894f0dca-05ff-4974-9101-38b165b09e40)

Pending member

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/797f9d33-efa9-4d6e-aa10-92bda1ad3bde)
