### ISSUE TITLE
GitHub: New fork SSI Library

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-tractusx/sig-infra#51]
**repository name within Tractus-X Organisation:** 
`https://github.com/eclipse-tractusx/SSI-agent-lib`

**repository name within Catena-X NG Organisation:** 
same name as in tractus-x. So: `SSI-agent-lib`

**GitHub team to grant access:** 
`https://github.com/orgs/catenax-ng/teams/product-managed-identity-wallets`

Thanks in advance! :)

**Comment by carslen** [comment]
Do not provide email addresses in GH issues due to privacy reasons. Our GH issues are public accessible and SPAM bots love to crawl public resources for email addresses. Please remove the email address added to this issues description.

**Comment by DominikPinsel** [comment]
> Since all our tractusx forks are prefixed with "tx-" your new fork is available here: https://github.com/catenax-ng/tx-SSI-agent-lib
> 
> have fun Harry

Thanks a lot! :)
