### ISSUE TITLE
New Product BPN Discovery

### ISSUE THREAD

**Issue by agg3fe** [eclipse-tractusx/sig-infra#510]
Product name: BPN Discovery 
GitHub users to invite: @agg3fe @tunacicek @thomas-henn
Validation / approved by: @thomas-henn

including new GitHub-team, ArgoCD and Vault

Repository is not needed, work will be done with Tractus-X: https://github.com/eclipse-tractusx/sldt-bpn-discovery
We need to test our functionalities to be release in the v24.08.

If possible, also please copy the Vault values from https://vault.demo.catena-x.net/ui/vault/secrets/semantics

**Comment by stephanbcbauer** [comment]
@agg3fe [product-bpn-discovery](https://github.com/orgs/catenax-eV/teams/product-bpn-discovery) was created.

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/28d4117b-9d63-472d-bb78-7474623ac026)

Pending member

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/1dd8ca3d-e78c-4c18-8376-41da42e49b27)
