### ISSUE TITLE
New Product Discovery Finder

### ISSUE THREAD

**Issue by agg3fe** [eclipse-tractusx/sig-infra#511]
Product name: Discovery Finder
GitHub users to invite: @agg3fe @tunacicek @thomas-henn
Validation / approved by: @thomas-henn

including new GitHub-team, ArgoCD and Vault

Repository is not needed, work will be done with Tractus-X: https://github.com/eclipse-tractusx/sldt-discovery-finder
We need to test our functionalities to be release in the v24.08.

If possible, also please copy the Vault values from https://vault.demo.catena-x.net/ui/vault/secrets/semantics

**Comment by stephanbcbauer** [comment]
@agg3fe [product-discovery-finder](https://github.com/orgs/catenax-eV/teams/product-discovery-finder) was created.

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/fcb13d4a-a91b-4c61-85fc-56650bc3c62b)

Pending member

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/482e96a5-b4ee-416b-850d-b9147ac3e9e0)
