### ISSUE TITLE
New Product Semantic Hub

### ISSUE THREAD

**Issue by agg3fe** [eclipse-tractusx/sig-infra#512]
Product name: Semantic Hub
GitHub users to invite: @agg3fe @tunacicek @thomas-henn
Validation / approved by: @thomas-henn

including new GitHub-team, ArgoCD and Vault

Repository is not needed, work will be done with Tractus-X: https://github.com/eclipse-tractusx/sldt-semantic-hub
We need to test our functionalities to be release in the v24.08.

If possible, also please copy the Vault values from https://vault.demo.catena-x.net/ui/vault/secrets/semantics

**Comment by stephanbcbauer** [comment]
@agg3fe [product-semantic-hub](https://github.com/orgs/catenax-eV/teams/product-semantic-hub) was created.

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/35aee341-4629-4ed7-addd-1dd4110e4bbf)

Pending member 

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/f39ba439-7feb-4838-ad5d-6f8b318afd3b)
