### ISSUE TITLE
New Product PURIS

### ISSUE THREAD

**Issue by ReneSchroederLJ** [eclipse-tractusx/sig-infra#514]
Product name: PURIS
GitHub users to invite: @ReneSchroederLJ @tom-rm-meyer-ISST 
Validation / approved by: @tom-rm-meyer-ISST 

including new GitHub-team, ArgoCD and Vault

Repository is not needed, work will be done with Tractus-X: https://github.com/eclipse-tractusx/puris
We need to test our functionalities to be release in the v24.08.

If possible, also please copy the Vault values from https://vault.demo.catena-x.net/ui/vault/secrets/puris

**Comment by tom-rm-meyer-ISST** [comment]
@ReneSchroederLJ if they offer a private repository we should take it to feed configuration from file

**Comment by stephanbcbauer** [comment]
@ReneSchroederLJ [product-puris](https://github.com/orgs/catenax-eV/teams/product-puris) was created

<img width="1246" alt="image" src="https://github.com/eclipse-tractusx/sig-infra/assets/84396022/795515f3-ff7f-41f3-814f-849058a5084e">

**Comment by ds-asmierzchalski** [comment]
Access to ArgoCD and Vault was granted.
Regarding the copying values for vault. We dont have any permission so we are not able to do it.
@SebastianBezold do you see a way how this could be handled?

**Comment by SebastianBezold** [comment]
> Access to ArgoCD and Vault was granted. Regarding the copying values for vault. We dont have any permission so we are not able to do it. @SebastianBezold do you see a way how this could be handled?

The teams could use the [Vault CLI](https://developer.hashicorp.com/vault/docs/commands) to export their secrets from the consortia instance and import them to any other instance
