### ISSUE TITLE
New Product : item-relationship-service

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-infra#515]
Product name: item-relationship-service

GitHub users to invite: 
- @ds-crehm 
- @ds-mmaul 
- @ds-mwesener 
- @ds-kgassner 
- @dsmf 
- @ds-lcapellino 
- @mkanal 
- @ds-jhartmann 

Validation / approved by: @mkanal

**Comment by stephanbcbauer** [comment]
@mkanal [product-item-relationship-service](https://github.com/orgs/catenax-eV/teams/product-item-relationship-service) was created

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/de7db198-8d09-4b8f-8899-ca954e2c2a79)

Pending member

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/79636268-f813-4052-aef7-8f759412f928)

**Comment by ds-asmierzchalski** [comment]
Access to ArgoCD and Vault was granted.
