### ISSUE TITLE
New Product : traceability-foss

### ISSUE THREAD

**Issue by mkanal** [eclipse-tractusx/sig-infra#516]
Product name: traceability-foss

GitHub users to invite: 
- @ds-crehm 
- @ds-mmaul 
- @ds-mwesener 
- @ds-kgassner 
- @dsmf 
- @ds-lcapellino 
- @mkanal 
- @ds-jhartmann 

Validation / approved by: @mkanal

**Comment by stephanbcbauer** [comment]
@mkanal [product-traceability-foss](https://github.com/orgs/catenax-eV/teams/product-traceability-foss) was created

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/36903641-7e45-4eae-aeb3-7439ebaf5e8d)

Pending member

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/b7641885-33e7-47f1-894f-485c3f3d1240)

**Comment by ds-asmierzchalski** [comment]
Access to ArgoCD and Vault was granted.
