### ISSUE TITLE
Create product-semantic team

### ISSUE THREAD

**Issue by stephanbcbauer** [eclipse-tractusx/sig-infra#517]
This issue is the parent issue. As discussed with @tunacicek only one team is needed. [product-semantics](https://github.com/orgs/catenax-eV/teams/product-semantics) was created.

Teams/issues

- #509 
- #510 
- #511 
- #512 

can be closed.

@agg3fe FYI

**Comment by ds-asmierzchalski** [comment]
Access to ArgoCD and Vault was granted.
Regarding the copying values for vault. We dont have any permission so we are not able to do it.
@SebastianBezold do you see a way how this could be handled?

**Comment by ds-asmierzchalski** [comment]
Regarding Vault:
The teams could use the [Vault CLI](https://developer.hashicorp.com/vault/docs/commands) to export their secrets from the consortia instance and import them to any other instance
