### ISSUE TITLE
New Product: BPDM

### ISSUE THREAD

**Issue by maximilianong** [eclipse-tractusx/sig-infra#518]
Product name: bpdm

GitHub users to invite:
@nicoprow 
@SujitMBRDI 

Validation / approved by: @maximilianong

**Comment by stephanbcbauer** [comment]
@maximilianong [product-bpdm](https://github.com/orgs/catenax-eV/teams/product-bpdm) was created

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/3a4d6338-89b3-4508-abf8-fa01ab0f2369)

**Comment by maximilianong** [comment]
@stephanbcbauer where do we get the relevant information, URLs .. ?

We just created this issue but we are not sure what this is really for.

**Comment by ds-meberle** [comment]
@maximilianong these are the URLs to use:
ArgoCD: https://argocd.int.catena-x.net 
Vault: https://vault.core.catena-x.net/

Goal is to setup the BPDM application in the new environment.

**Comment by ds-lcapellino** [comment]
Access for ArgoCD and Vault is granted. In case of any questions or errors, please reach out to us.
