### ISSUE TITLE
SD Factory New Product 

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/sig-infra#519]
Product name: product- SD Factory
GitHub users to invite: 

- sachinargade123 (sachin.argade@t-systems.com)
- amoldashwant (amol.dashwant@t-systems.com)
- ChetanT-System (chetan.parate@t-systems.com)
- ajithsimons (ajithkumar.s@t-systems.com)
- adityagajbhiye9 (aditya.gajbhiye@t-systems.com)
- AjayRaturi123 (ajay.raturi@t-systems.com)
- sharathshivprasad (sharath.shivprasad@t-systems.com)
- ciprianherciu (ciprian.herciu@t-systems.com)

 Validation / approved by: ciprianherciu (ciprian.herciu@t-systems.com)
(including new GitHub-team, new GitHub-repository, ArgoCD and Vault)

**Comment by stephanbcbauer** [comment]
@ciprianherciu [product-sd-factory](https://github.com/orgs/catenax-eV/teams/product-sd-factory) was created

Pending member

<img width="440" alt="image" src="https://github.com/eclipse-tractusx/sig-infra/assets/84396022/2be3d449-ce39-4afc-8a48-c77265f182da">

**Comment by ds-lcapellino** [comment]
Access for ArgoCD and Vault is granted. In case of any questions or errors, please reach out to us.
