### ISSUE TITLE
GitHub: Invite member Simone Lindner - bs-sili

### ISSUE THREAD

**Issue by bs-sili** [eclipse-tractusx/sig-infra#52]
Hi together, 

I work as developer in the sldt-team and need access to the product-semantics repository: https://github.com/catenax-ng/product-semantics. 

GitHub User: bs-sili

Vouching person:
@LuLeRoemer , @bs-jokri , @tunacicek and the Product Owner is Thomas Henn can verify, that I am member of Catena-X NG Github Organisation.

Best regards
Simone

**Comment by carslen** [comment]
Do not provide email addresses in GH issues due to privacy reasons. Our GH issues are public accessible and SPAM bots love to crawl public resources for email addresses. Please remove the email address added to this issues description.

**Comment by hzierer** [comment]
Hey @LuLeRoemer, @bs-jokri + @tunacicek can you please give us a short thumps up?

**Comment by FaGru3n** [comment]
> Hey @LuLeRoemer, @bs-jokri + @tunacicek can you please give us a short thumps up?

Do we have your approval to invite https://github.com/bs-sili ?

**Comment by tunacicek** [comment]
@FaGru3n yes, please invite Simone to the project. She is working in the sldt-team.
Thank you for your support.

**Comment by FaGru3n** [comment]
Hi @tunacicek,

thanks for feedback:
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/401ee117-1a51-4106-8d69-2d74769c6c57)

invitation was sended, now @bs-sili has 7 days to accept the invite and the maintainer of the desired gh-team can invite the user.

Please review it, and close issue if your finde with the result.

**Comment by FaGru3n** [comment]
@bs-sili has successfully joined the https://github.com/catenax-ng
