### ISSUE TITLE
SDE New Product 

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/sig-infra#520]
Product name: product- SDE
GitHub users to invite: 

- sachinargade123 (sachin.argade@t-systems.com)
- amoldashwant (amol.dashwant@t-systems.com)
- ChetanT-System (chetan.parate@t-systems.com)
- ajithsimons (ajithkumar.s@t-systems.com)
- adityagajbhiye9 (aditya.gajbhiye@t-systems.com)
- AjayRaturi123 (ajay.raturi@t-systems.com)
- sharathshivprasad (sharath.shivprasad@t-systems.com)
- ciprianherciu (ciprian.herciu@t-systems.com)

 Validation / approved by: ciprianherciu (ciprian.herciu@t-systems.com)
(including new GitHub-team, new GitHub-repository, ArgoCD and Vault)

**Comment by stephanbcbauer** [comment]
@ciprianherciu [product-sde](https://github.com/orgs/catenax-eV/teams/product-sde) was created

<img width="1237" alt="image" src="https://github.com/eclipse-tractusx/sig-infra/assets/84396022/c6162857-3183-4aac-a0fb-b31053ac33b2">

Pending member

<img width="444" alt="image" src="https://github.com/eclipse-tractusx/sig-infra/assets/84396022/902defee-ef6a-401c-93e1-fdf75a91deaf">

**Comment by ds-lcapellino** [comment]
Access for ArgoCD and Vault is granted. In case of any questions or errors, please reach out to us.
