### ISSUE TITLE
MSO New Product 

### ISSUE THREAD

**Issue by ciprianherciu** [eclipse-tractusx/sig-infra#521]
Product name: product- Managed Service Orchestrator
GitHub users to invite: 

- sachinargade123 (sachin.argade@t-systems.com)
- amoldashwant (amol.dashwant@t-systems.com)
- ChetanT-System (chetan.parate@t-systems.com)
- ajithsimons (ajithkumar.s@t-systems.com)
- adityagajbhiye9 (aditya.gajbhiye@t-systems.com)
- AjayRaturi123 (ajay.raturi@t-systems.com)
- sharathshivprasad (sharath.shivprasad@t-systems.com)
- ciprianherciu (ciprian.herciu@t-systems.com)

 Validation / approved by: ciprianherciu (ciprian.herciu@t-systems.com)
(including new GitHub-team, new GitHub-repository, ArgoCD and Vault)

**Comment by stephanbcbauer** [comment]
@ciprianherciu you already created an issue for sd-factory? Is this a duplicate?

**Comment by ciprianherciu** [comment]
@stephanbcbauer sorry, it was created for MSO

**Comment by stephanbcbauer** [comment]
@ciprianherciu [product-managed-service-orchestrator](https://github.com/orgs/catenax-eV/teams/product-managed-service-orchestrator) was created

![Image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/b8698a79-241e-4738-9bb8-85bac86ada57)

Pending member

![Image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/0dd4e4fb-2ee9-4e30-a017-92a4ee0ccf0f)

**Comment by ds-lcapellino** [comment]
Access for ArgoCD and Vault is granted. In case of any questions or errors, please reach out to us.
