### ISSUE TITLE
New Product Portal

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#523]
Product name: Portal
GitHub users to invite: @oyo @Phil91 @ntruchsess @evegufy 
Validation / approved by: @jjeroch 

including new GitHub-team, ArgoCD and Vault

Repository is not needed, work will be done with Tractus-X: https://github.com/eclipse-tractusx/portal

**Comment by stephanbcbauer** [comment]
@evegufy [product-portal](https://github.com/orgs/catenax-eV/teams/product-portal) was created

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/b99c7ac1-ee8e-4097-b56e-0b48765cd87f)

Pending member

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/f1c14ea5-0365-4b5e-93d4-583776818c99)

**Comment by ds-lcapellino** [comment]
Access to ArgoCD and Vault is granted. In case of any questions or errors, please reach out to us.
