### ISSUE TITLE
New Product Policy Hub

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#524]
Product name: Policy Hub
GitHub users to invite: @Phil91 @ntruchsess @evegufy 
Validation / approved by: @jjeroch 

including new GitHub-team, ArgoCD and Vault

Repository is not needed, work will be done with Tractus-X: https://github.com/eclipse-tractusx/policy-hub

**Comment by stephanbcbauer** [comment]
@evegufy [product-policy-hub](https://github.com/orgs/catenax-eV/teams/product-policy-hub) was created

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/c93cf16b-995e-440d-9b8a-56e2f4daaa0b)

Pending member

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/73a2ecce-d1e4-4a2b-bd3d-a3e909bead37)

**Comment by ds-lcapellino** [comment]
Access to ArgoCD and Vault is granted. In case of any questions or errors, please reach out to us.
