### ISSUE TITLE
New Product SSI Credential Issuer

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#525]
Product name: SSI Credential Issuer
GitHub users to invite: @Phil91 @ntruchsess @evegufy 
Validation / approved by: @jjeroch 

including new GitHub-team, ArgoCD and Vault

Repository is not needed, work will be done with Tractus-X: https://github.com/eclipse-tractusx/ssi-credential-issuer

**Comment by stephanbcbauer** [comment]
@evegufy [product-ssi-credential-issuer](https://github.com/orgs/catenax-eV/teams/product-ssi-credential-issuer) was created

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/84d75efd-3691-461f-aea9-065180014b85)

Pending member

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/54686d8d-2e51-430e-9e6c-815b212cb3d1)

**Comment by ds-lcapellino** [comment]
Access to ArgoCD and Vault is granted. In case of any questions or errors, please reach out to us.
