### ISSUE TITLE
New Product SSI Authority & Schema Registry

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#526]
Product name: SSI Authority & Schema Registryr
GitHub users to invite: @Phil91 @ntruchsess @evegufy 
Validation / approved by: @jjeroch 

including new GitHub-team, ArgoCD and Vault

Repository is not needed, work will be done with Tractus-X: https://github.com/eclipse-tractusx/ssi-authority-schema-registry

**Comment by stephanbcbauer** [comment]
@evegufy the product-ssi-credential-issuer team was already created via a different issue #525 . Is the product name here wrong?

**Comment by evegufy** [comment]
Hi @stephanbcbauer, the SSI Credential Issuer and SSI Authority & Schema Registry are two different products, so the product name is correct.

**Comment by evegufy** [comment]
Hi @stephanbcbauer I updated the product name in the issue description

**Comment by stephanbcbauer** [comment]
@evegufy [product-ssi-authority-schema-registry](https://github.com/orgs/catenax-eV/teams/product-ssi-authority-schema-registry) was created

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/5dc8222a-b753-4031-bc6c-1ea3e0209528)

Pending member

![image](https://github.com/eclipse-tractusx/sig-infra/assets/84396022/62fb1502-a763-420c-b573-72a2aef3d77d)

**Comment by ds-lcapellino** [comment]
Access to ArgoCD and Vault is granted. In case of any questions or errors, please reach out to us.
