### ISSUE TITLE
Onboarding Product EDC

### ISSUE THREAD

**Issue by lgblaumeiser** [eclipse-tractusx/sig-infra#527]
Product name: EDC
GitHub users to invite:   [paullatzelsperger](https://github.com/paullatzelsperger), [wolf4ood](https://github.com/wolf4ood), [ndr-brt](https://github.com/ndr-brt), [jimmarino](https://github.com/jimmarino), [lgblaumeiser](https://github.com/lgblaumeiser)
Validation / approved by: [lgblaumeiser](https://github.com/lgblaumeiser)

**Comment by stephanbcbauer** [comment]
@lgblaumeiser [product-edc](https://github.com/orgs/catenax-eV/teams/product-edc) was created

<img width="1237" alt="image" src="https://github.com/eclipse-tractusx/sig-infra/assets/84396022/1787f9bb-3530-43d9-b3a5-db6bf8be7d54">

Pending member

<img width="435" alt="image" src="https://github.com/eclipse-tractusx/sig-infra/assets/84396022/d6107532-9819-451e-bad9-56b1bea29c27">

**Comment by ds-lcapellino** [comment]
Access to ArgoCD and Vault is granted. In case of any questions or errors, please reach out to us.
