### ISSUE TITLE
BDRS token not valid anymore after vault outage

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#529]
**Is your support request related to a problem? Please describe.**  

**Describe the solution you'd like**  

After the vault outage from https://github.com/eclipse-tractusx/sig-infra/issues/528, the bdrs token provided as part of https://github.com/eclipse-tractusx/sig-infra/issues/500 and https://github.com/catenax-ng/product-onboarding/pull/63 isn't valid anymore:
https://github.com/catenax-ng/product-onboarding/blob/main/vault/main.tf#L224

Could you please check?

**Additional context**  

Maybe the token rotation didn't work properly after the outage... but that's just guess

**Comment by SebastianBezold** [comment]
Hi @evegufy,

i re-ran the tf setup and it generated a new secret. Available as before. Can you please check if that solved the issue?

**Comment by evegufy** [comment]
Hi @SebastianBezold thank you! it works again
