### ISSUE TITLE
GitHub: Transfer NG repository ownership

### ISSUE THREAD

**Issue by DominikPinsel** [eclipse-tractusx/sig-infra#53]
Assign miw team as owner of the ssi-lab-repository.

**repository:**
https://github.com/catenax-ng/product-lab-ssi

**miw team:**
https://github.com/orgs/catenax-ng/teams/product-managed-identity-wallets

**Comment by carslen** [comment]
Do not provide email addresses in GH issues due to privacy reasons. Our GH issues are public accessible and SPAM bots love to crawl public resources for email addresses. Please remove the email address added to this issues description.

**Comment by DominikPinsel** [comment]
> @DominikPinsel shall the product-edc team keep it's maintainer rights?

@hzierer Not necessary :) You can transfer all rights to the miw team.

**Comment by hzierer** [comment]
done.

**Comment by DominikPinsel** [comment]
> done.

Perfect, thanks :)
