### ISSUE TITLE
New Product 

### ISSUE THREAD

**Issue by obalandi** [eclipse-tractusx/sig-infra#530]
Product name: product-knowledge-agents  
GitHub users to invite: @drcgjung , @TomBuchertTSystems , @bosserf , @almadigabor 
Validation / approved by: @obalandi 

- new GitHub-team
- ArgoCD 
- Vault
- Use the existing repositories: 
https://github.com/eclipse-tractusx/knowledge-agents
https://github.com/eclipse-tractusx/knowledge-agents-edc
https://github.com/eclipse-tractusx/sldt-ontology-model

**Comment by stephanbcbauer** [comment]
@obalandi [product-knowledge-agents](https://github.com/orgs/catenax-eV/teams/product-knowledge-agents) was created

<img width="1238" alt="image" src="https://github.com/eclipse-tractusx/sig-infra/assets/84396022/f7946295-ee2c-4e94-8b89-f54f1b2474b2">

Pending member

<img width="436" alt="image" src="https://github.com/eclipse-tractusx/sig-infra/assets/84396022/b0b0bd15-970b-41d8-9d44-5dbbace706f5">

**Comment by obalandi** [comment]
Hi @ds-lcapellino & @stephanbcbauer, https://github.com/eclipse-tractusx/knowledge-agents-aas-bridge is also a part of product-knowledge-agents.

**Comment by ds-lcapellino** [comment]
Hi @obalandi, 
do you want to create an extra namespace for this product? 
You can create several apps in ArgoCD to deploy your applications.

**Comment by drcgjung** [comment]
no, a single namespace for the product is enough. We just have these four repos belonging to it just in case some rule (where to get charts or images from) would be implemented.
