### ISSUE TITLE
Vault (consortia) down and generate vault token

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#533]
**Is your support request related to a problem? Please describe.**  

The consortia vault (https://vault.demo.catena-x.net) is down again.

Could you please check?

Could you please also regenerate the bdrs token once it's back, see https://github.com/eclipse-tractusx/sig-infra/issues/529

Please also reg

**Describe the solution you'd like**  

Vault is available.

**Comment by FaGru3n** [comment]
Hi @evegufy currently we are checking...

**Comment by FaGru3n** [comment]
Hi @evegufy 

vault-cluster is back again. 

little question: Did you increased your requests against the vault clusters or was modified, that the cluster have maybe a higher load (ressource impact ) against vault with your bdrs_token?

After checking, seems the load or mem limits are not enough, towards the current load.

**Comment by FaGru3n** [comment]
Please recheck or verfiy and close the issue. Thx in advance.

**Comment by kbData** [comment]
![image](https://github.com/user-attachments/assets/e004c4f8-d476-4113-8f84-f2e1ce4ac87d)

the bdrs server seems to be still unavailable

**Comment by evegufy** [comment]
@FaGru3n the vault is up again in general, thank you! but the vault token for the bdrs has not been regenerated, could you please still do that?

**Comment by evegufy** [comment]
> Hi @evegufy
> 
> vault-cluster is back again.
> 
> little question: Did you increased your requests against the vault clusters or was modified, that the cluster have maybe a higher load (ressource impact ) against vault with your bdrs_token?
> 
> After checking, seems the load or mem limits are not enough, towards the current load.

Hi @FaGru3n are you asking if the bdrs is causing a higher load at the vault? it that the question?

**Comment by SebastianBezold** [comment]
Hi @evegufy, I re-created the token

**Comment by evegufy** [comment]
> Hi @evegufy, I re-created the token

@SebastianBezold thank you! bdrs is up again.

**Comment by kbData** [comment]
Many thanks.
