### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by ybidois** [eclipse-tractusx/sig-infra#534]
## Necessary Information

Email address to add: yannick@bidois.fr
Committers, that could take over: @nitin-vavdiya @evegufy 
Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by evegufy** [comment]
Hi @ybidois :) just to be sure, is that the mail you have connected to your eclipse.org account? yannick@bidois.fr
If not, could you please provide your username for the eclipse.org account?

**Comment by ybidois** [comment]
@evegufy, yes, I've connected this email address! My eclipse.org username is ybidois, just in case.

**Comment by evegufy** [comment]
Hi @ybidois I invited you to the GitHub Org, you should get a notification soon

**Comment by FaGru3n** [comment]
Hi @ybidois i see you joined the GitHub Org so would close this issue. If you need further help, please contact us again.

Thanks in advance.
