### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by shubhamv-ss** [eclipse-tractusx/sig-infra#536]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add:  shubham.vaidya@smartsensesolutions.com
Committers, that could take over:  @nitin-vavdiya @evegufy 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by evegufy** [comment]
done :)
you should get an invite soon

**Comment by FaGru3n** [comment]
I would close this issue, thx for your work @evegufy
