### ISSUE TITLE
New Tractus-X project contributor - Boomadevi Madhanagopal

### ISSUE THREAD

**Issue by gitbooma** [eclipse-tractusx/sig-infra#537]
> __Before requesting the project contributor role, please make sure, that you:__
>
> - Make yourself familiar with the Eclipse Foundation project roles: https://eclipse-tractusx.github.io/docs/oss/contributor-committer
> - Make ourselves familiar with prerequisites, like a signed ECA: https://eclipse-tractusx.github.io/docs/oss/getting-started
> - Check the committer list of our project and highlight at least one of them on this issue, since every committer
> can add project contributors: https://projects.eclipse.org/projects/automotive.tractusx/who

## Necessary Information

Email address to add: boomadevi.madhanagopal@cofinity-x.com
Committers, that could take over: @evegufy @FaGru3n

I will be working as Portal DevOps Engineer from Cofinity-X GmbH

**Comment by evegufy** [comment]
done :)
you should get an invite soon

**Comment by FaGru3n** [comment]
I would close this issue. 😉
