### ISSUE TITLE
Re-adjust and preserve branch protection rules for tx-forks

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#54]
**Is your support request related to a problem? Please describe.**  
I have the impression that the change to the branch protection rules of below tx-portal repositories on May 15, 2023 (A1ODT-1385) have been overwritten by your GH-repositories-terraform-script, because the changes appear to gone since approximately yesterday (May 31, 2023) afternoon. As a result we aren't able to sync our forks with tractusx and **our work is significantly disrupted**.

The change from May 15, 2023 essentially did the following:

Please edit the branch protection rules for main and dev in our below tx-forks in the following way:
Disable 'Require a pull request before merging' and **enable 'Lock branch' with 'Allow fork syncing'**.

[tx-portal-cd](https://github.com/catenax-ng/tx-portal-cd)

[tx-portal-frontend-registration](https://github.com/catenax-ng/tx-portal-frontend-registration)

[tx-portal-frontend](https://github.com/catenax-ng/tx-portal-frontend)

[tx-portal-backend](https://github.com/catenax-ng/tx-portal-backend)

[tx-portal-assets ](https://github.com/catenax-ng/tx-portal-assets) (* only main branch, there is no dev branch)

**Describe the solution you'd like**  
Re-adjust branch protection rules and preserve them for terraform.

**Comment by hzierer** [comment]
workaround (deleted old branch protections + created new BETA rules/rulesets) applies to all repos

**Comment by evegufy** [comment]
@hzierer thanks!
