### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by ss-nikunj** [eclipse-tractusx/sig-infra#542]
## Necessary Information

Email address to add: nikunj.maniya@smartsensesolutions.com
Committers, that could take over: @nitin-vavdiya & @evegufy 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by evegufy** [comment]
Hi @ss-nikunj :) before I add you as a contributor, you should sign the [ECA](https://github.com/eclipse-tractusx/portal-frontend/blob/main/CONTRIBUTING.md#eclipse-contributor-agreement), I noticed on this [pr](https://github.com/eclipse-tractusx/portal-frontend/pull/996) that the agreement isn't signed yet.

**Comment by ss-nikunj** [comment]
Hi @evegufy, Can you please tell me where should i sign the ECA??


I sing it here
![image](https://github.com/user-attachments/assets/f56fa1d0-0a2b-4bb5-9979-1f7db389806e)

**Comment by ss-nikunj** [comment]
Yes, My eclipse.org account doesn't match with my commit email. I have closed my old PR and Created a new PR with the correct email address.

PR: https://github.com/eclipse-tractusx/portal-frontend/pull/1001

Thank you

**Comment by evegufy** [comment]
@ss-nikunj I added you as a contributor to the Eclipse Tractus-X Github org, you should get an invite soon.
