### ISSUE TITLE
New Tractus-X project contributor

### ISSUE THREAD

**Issue by saadanzari** [eclipse-tractusx/sig-infra#543]
## Necessary Information

Email address to add: saad.rafiq@cofinity-x.com
Committers, that could take over: @evegufy @oyo @stephanbcbauer @matbmoser 

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by saadanzari** [comment]
@Siegfriedk can you please help me with this too? thanks

**Comment by saadanzari** [comment]
@Siegfriedk I already have eclipse account https://accounts.eclipse.org/users/isaadansari signed Eclipse Contributor Agreement as well.

**Comment by Siegfriedk** [comment]
@saadanzari done. sync might take a little bit of time. Pls verify

**Comment by saadanzari** [comment]
thanks a lot @Siegfriedk
