### ISSUE TITLE
New: Tractus-X project contributor

### ISSUE THREAD

**Issue by Usmanfee** [eclipse-tractusx/sig-infra#547]
## Necessary Information

Email address to add: [muhammad.usman@cofinity-x.com](mailto:muhammad.usman@cofinity-x.com)
Committers, that could take over: @evegufy @oyo @stephanbcbauer @matbmoser

Please make sure, that you accept the invitation you receive from GitHub, after you have been added as project contributor.

**Comment by matbmoser** [comment]
Hi @Usmanfee, thank you for creating this ticket!

You were added to the list of contributors 👍🏻 Once the invitation comes from Github side, accept it and you will be officially a project contributor ;)

Have a nice day
