### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by Martin-Aulich** [eclipse-tractusx/sig-infra#55]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User:
Martin-Aulich

Vouching person: OSchlienz

Info: Who can verify that the new user is a Member of Catena-X:

- koptan
- DominikPinsel
- OSchlienz

**Comment by hzierer** [comment]
Hey @koptan or @DominikPinsel can you please give short thumbs up/down?

(omitting @OSchlienz since he is not member of catenax-ng himself)

**Comment by Martin-Aulich** [comment]
@hzierer:   @koptan has given thumbs up above

**Comment by hzierer** [comment]
invitation sent
