### ISSUE TITLE
Exposed password to repository

### ISSUE THREAD

**Issue by ds-ext-sceronik** [eclipse-tractusx/sig-infra#58]
Hello there ! 

We exposed one of our environment test user password to our repository with exported insomnia collection 
https://github.com/catenax-ng/tx-traceability-foss

it is already in one of the past commits, neverthen less we should change password for exposed user. 
exposed password is for following client id - "sa-cl6-cx-10".
What is the process in that situation. is reseting password for that user enough ? 

Best regards

**Comment by hzierer** [comment]
@the-tatanka @Essenbreis can you please take a look?

**Comment by the-tatanka** [comment]
**The Secret must be revoked!**

Additionally, the secret can be removed from the commit history. A rebase is necessary for this. From my point of view this is a clear recommendation, but not a must.

**Comment by the-tatanka** [comment]
Depending on how critical the secret is and how long it was published, you should also check your access logs. An attacker could have accessed your systems.

**Comment by ds-ext-sceronik** [comment]
We did not notice any suspicious activity in our test environments. neverthen less we need this password to be changed so we could update it in our vault so our integration tests and other related processes are working with new secure password.

**Comment by the-tatanka** [comment]
secret revoked

**Comment by evegufy** [comment]
> secret revoked

@the-tatanka we found this issue last week and, as a result, a new client secret for the client 'sa-cl6-cx-10' was generated in Keycloak (TRACEFOSS-1524).
As you aren't a Keycloak admin, what did you mean here when stating 'secret revoked'?

**Comment by the-tatanka** [comment]
I assumed that the honorable colleague @ds-ext-sceronik  had taken care of that or set that in motion. 
Apparently not.
The "secret revoked" was noted for me as a reminder, as I thought the issue was settled.

Thanks for pointing this out, please revoke secret.

**Comment by evegufy** [comment]
> I assumed that the honorable colleague @ds-ext-sceronik had taken care of that or set that in motion. Apparently not. The "secret revoked" was noted for me as a reminder, as I thought the issue was settled.
> 
> Thanks for pointing this out, please revoke secret.

The secret has been regenerated and, as a result, revoked last.
Thanks for clarifying! I just wanted to make sure, that there is awareness about the necessity to revoke it in Keycloak.
