### ISSUE TITLE
Onboarding to Catena-X environments

### ISSUE THREAD

**Issue by Ruskyy** [eclipse-tractusx/sig-infra#59]
**Describe the solution you'd like**  
Id like to schedule a meeting, to onboard my team onto the Catena-X demonstrator environments.

**Additional context**  
https://catenax-ng.github.io/docs/resources

**Comment by hzierer** [comment]
Hi @Ruskyy,

what do you mean by onboard? Does your team just need access to argocd, grafana, etc? Or have you got already a software release that has to be deployed?

**Comment by Ruskyy** [comment]
As stated on : https://catenax-ng.github.io/docs/resources
Me or my team are not yet familiar with the setup of our demonstrator environments or the tools running on it.
As such, we're requesting this meeting.

**Comment by Ruskyy** [comment]
Hi @Siegfriedk, can we allign for monday 14:00 GMT ?

**Comment by Siegfriedk** [comment]
Yes absolutly @Ruskyy . Please send an invite.
