### ISSUE TITLE
Request solution for Fork Sync - Trace-X

### ISSUE THREAD

**Issue by ds-mwesener** [eclipse-tractusx/sig-infra#60]
**Is your support request related to a problem? Please describe.**  

FORK Sync between catena: https://github.com/catenax-ng/tx-traceability-foss
and tractus-x repository: https://github.com/eclipse-tractusx/traceability-foss

**Describe the solution you'd like**  

Hello, I would like to request the workaround solution provided for the SYNC option for catena repository.

**Additional context**  

Workaround solution mentioned in CX - CoP DevSecOps chat.

Requester: Maximilian Wesener, Trace-X

**Comment by hzierer** [comment]
Hi @ds-mwesener,
it seems the settings in question are not set for your repo. Can you describe your issue a bit more detailed / Provide a screenshot?

**Comment by ds-mwesener** [comment]
Hi @hzierer after clicking on Sync (within catena repository) it shows the following error:

![image](https://github.com/eclipse-tractusx/sig-infra/assets/124587888/7dad314a-7238-4031-8eae-ab90197c5a7e)

As you have mentioned in the DevOps Chat there is now a workaround existing?

Thanks in advance.
