### ISSUE TITLE
Catena-X Teams application

### ISSUE THREAD

**Issue by ds-ext-sceronik** [eclipse-tractusx/sig-infra#62]
Hello there ! I am having problems with logging into catena-x teams tenant. 
after I log on doubleslash email I have option to switch tenant on teams application . when I click to switch to catena-x I am greeted with information " You have been invited to catena-x tenant" when I click on accept invitation it loops back to the same greeting as seconds before. so I am stuck with endless loop. 

I have contacted DoubleSlash support . they noticed some problems with my account on their side and they changed 
some type on my license from O365 to M365. 

other than that they are not able to support me further with that problem and they asked to ask You to check the sign-in logs on Your azure tenant.

**Comment by carslen** [comment]
Hi, 
System-Team is not responsible for Catena-X MS Teams Tenant. The only suggestion could be to use the web client for first time login/join to Catena-X tenant: https://teams.microsoft.com

Other advice is to contact the person/s who onboarded you to Catena-X consortia (in your company, the PO, ...) and ask for Catena-X onboarding support. System-Team unfortunately can't provide any contacts here, sorry.
