### ISSUE TITLE
New Project - ArgoCD

### ISSUE THREAD

**Issue by Ruskyy** [eclipse-tractusx/sig-infra#64]
Product name: product-cgi-dcm-foss
Team to invite: product-demand-capacity-mgmt
Vouching person: @Siegfriedk 

We had a meeting with @Siegfriedk, and noticed we do not have a project on ArgoCD.

**Comment by carslen** [comment]
GH Team: product-cgi-dcm-foss

Vault is also missing, will be created within this ticket.

**Comment by carslen** [comment]
Vault onboarding done. As of know all team members of GH Team product-cgi-dcm-foss can loging using GitHub authentication to our vault. For details, please refer to https://catenax-ng.github.io/docs/guides/how-to-use-vault.

**Comment by carslen** [comment]
ArgoCD onboarding done. As of now all team members of GH team _product-cgi-dcm-foss_ cann login using GitHub authentication to ArgoCD instances on [DEV](https://argo.dev.demo.catena-x.net) and [INT](https://argo.int.demo.catena-x.net) environments.

**Comment by Ruskyy** [comment]
Its working!
Ill mark this one as closed
