### ISSUE TITLE
Github action env secrets mapping for tx-traceability-foss

### ISSUE THREAD

**Issue by ds-ext-sceronik** [eclipse-tractusx/sig-infra#66]
Hello there !

We have created cucumber tests for our projects that are started with the following github action
.github/workflows/xray-cucumber.yaml

inside https://github.com/catenax-ng/tx-traceability-foss repository

For it to work correctly we need the following mapping of secrets from the vault.

traceability-foss/e2e/cucumber/keycloak/KEYCLOAK_HOST -> ${{ secrets.KEYCLOAK_HOST }}

traceability-foss/e2e/cucumber/keycloak/SUPERVISOR_CLIENT_ID -> ${{ secrets.SUPERVISOR_CLIENT_ID }}

traceability-foss/e2e/cucumber/keycloak/SUPERVISOR_PASSWORD -> ${{ secrets.SUPERVISOR_PASSWORD }}

traceability-foss/e2e/cucumber/e2e-a/E2E_TXA_HOST -> ${{ secrets.E2E_TXA_HOST }}

traceability-foss/e2e/cucumber/e2e-b/E2E_TXB_HOST -> ${{ secrets.E2E_TXB_HOST }}

Thank You for Your support :)

**Comment by almadigabor** [comment]
Hey @ds-ext-sceronik! I've added the secrets to the repository. Please confirm it's working.

**Comment by ds-ext-sceronik** [comment]
@almadigabor cucumber tests are now getting passed variables thank You !! :)

**Comment by FaGru3n** [comment]
> @almadigabor cucumber tests are now getting passed variables thank You !! :)

Thanks @ds-ext-sceronik  we will close the issue with your approval.
