### ISSUE TITLE
GitHub: Invite members

### ISSUE THREAD

**Issue by tom-rm-meyer-ISST** [eclipse-tractusx/sig-infra#67]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub Users:
- [eschrewe](https://github.com/eschrewe)
- [PaMarzec](https://github.com/PaMarzec)

Vouching person: 
- Maintainer of GitHub Team "product-puris": [tom-rm-meyer-ISST](https://github.com/tom-rm-meyer-ISST)
- Product Owner (in case maintainer is not sufficient):  [Mail Ute Burkhardt](ute.burkhardt@volkswagen.de)

Please Note: Future development will not be done on ng BUT ArgoCD still relies on membership. They're part (or will be part) of the team "product-puris".

**Comment by FaGru3n** [comment]
Hi @tom-rm-meyer-ISST,

invitation was sent to the 2 new users.

![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/86f2e7b2-7318-4613-a1c4-a35fd1cee12e)

after successful invitation you as maintainer for the gh-team can invite them to the team.

@tom-rm-meyer-ISST  Please verfiy and close the issue if your fine with the result. Thanks in advance.

FYI: Please update the profile information with clear names that we can verfiy that they are real users and we can be sure that they are a part of the as stated in the Office Hour 😉 
[Blog Post Office Hour](https://catenax-ng.github.io/blog/Office%20Hours%202023-05-26#devsecops)


> New GH Support Process is used, but we have a couple of hints:
Please identify yourself, either on your GH profile page or in the issue itself. In general everyone with a GH account is able to create a support issue and in some cases we've to validate if the request itself is valid. It helps a lot to know who is opening the request to verify.
Be careful with sensitive data, like email addresses, provided in issues. When you request to onboard a new developer to our Catenax-ng organization. It's sufficient to provide the GH account name, there is no need for any email-address. Keep in mind, that these issues are public and can be read from everyone, even spam-bots.

**Comment by FaGru3n** [comment]
Friendly reminder: The invitation will remain for 5 days.

**Comment by tom-rm-meyer-ISST** [comment]
Thanks for beeing that fast! Everything is alright. I'll ensure that the users add their names to their accounts. Thanks for pointing out! :)
