### ISSUE TITLE
Question. Acess to Keycloak console ?

### ISSUE THREAD

**Issue by Ruskyy** [eclipse-tractusx/sig-infra#68]
**Is your support request related to a problem? Please describe.**  
According to a contact on BMW, we already have a DAPS certificate on the EDC.
He redirected us to a [link ](https://portal.dev.demo.catena-x.net/documentation/?path=docs%2F02.+Technical+Integration%2F01.+Connector+Registration%2F02.+Connector+Registration.md) 
We however do not seem to have access to these consoles, and we require this certificate to setup EDC locally as a part of our development.

This contact also said we need to request access to this portal, under a member organization.
We've been fowarded from person to person, and running out of time..
Hopefully you can point us in the right direction?

**Comment by COROANN** [comment]
Hey Sebastian, can you help out?

**Comment by the-tatanka** [comment]
Unfortunately not :( . 
@evegufy do you know what is needed?

**Comment by the-tatanka** [comment]
@Ruskyy you can ask your question in DevSecOps hour today.

**Comment by the-tatanka** [comment]
@Ruskyy are you part of the consortia, like for real?

**Comment by Ruskyy** [comment]
@the-tatanka Terribly sorry for the delay on this reply.
I work for CGI, we're an application provider, working for BMW.
Our PO is Phillip Mai ([confluence](https://confluence.catena-x.net/users/viewfollow.action?username=philipp.ra.mai@bmw.de))

**Comment by Ruskyy** [comment]
I will be on leave until the 21th.
A colleague from my team should be able to pick up on this issue.

**Comment by viniciusvieirah** [comment]
.

**Comment by Bailonis** [comment]
Any news on this @the-tatanka ? We are getting out of time and still no access to this: 
![daps](https://github.com/eclipse-tractusx/sig-infra/assets/72702458/2d47ccc8-1963-4f26-8e77-42473fafd6aa)

**Comment by the-tatanka** [comment]
Unfortunately, I am not responsible.
The Portal team takes care of Keycloak, please help if possible @jjeroch @evegufy . 
Could also imagine that they are "reluctant" to give access to the Keycloak console, as not uncritical. You need a good reason.

**Comment by jjeroch** [comment]
> link

Hi - I contacted Juergen. He needs to take the role to manage the access. He will get the needed account/tenant and can take further action to invite the relevant developers/team members. Since he is the product/solution owner he can better manage the relevant access rights. We (portal) can not be responsible for every user since we dont know the relation of each person to the consortia. @Ruskyy can this wait till Monday?

@the-tatanka if we receive those requests ideally we ask the respective developers to connect to their POs/BOs which should contact the portal PO to retrieve an access to the core component portal to be able to connect to the INT dataspace.

**Comment by Bailonis** [comment]
Thanks @jjeroch, yes, this can wait until Monday

**Comment by jschu1** [comment]
Hi, 
can you @jjeroch give me the rights to grant access to the cgi-guys?

**Comment by the-tatanka** [comment]
@Ruskyy @jjeroch 
I was assigned here just to make contact between you, please don't wait for me.
Can we close the issue?

**Comment by Bailonis** [comment]
Hi there @the-tatanka, 
@jschu1 is our PO

**Comment by Bailonis** [comment]
@the-tatanka you can close the issue.

Thanks!
