### ISSUE TITLE
Adjust terraform state to the actual AKS kubernetes versions

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/sig-infra#70]
Based on the [readme](https://github.com/catenax-ng/cloud-infra/blob/main/README.md). All clusters were upgraded to 1.25.6 on Azure Portal and terraform state does not reflect that currently.

**Comment by FaGru3n** [comment]
adapt the existing clusters for our terraform config.
https://github.com/catenax-ng/cloud-infra/pull/5

**Comment by FaGru3n** [comment]
merged into our stack on repo `cloud-infra`

**Comment by FaGru3n** [comment]
@almadigabor some updates for the INT State ?

**Comment by almadigabor** [comment]
Int is currently not tracked by terraform. It needs to be decided how to import it or change it's setup so it can be imported as the other clusters are.

**Comment by FaGru3n** [comment]
only INT is missing terraform state and open disscussion how to do this one.

**Comment by FaGru3n** [comment]
🚧 https://github.com/catenax-ng/cloud-infra/pull/7
