### ISSUE TITLE
Onboarding Tomasz Barwicki

### ISSUE THREAD

**Issue by almadigabor** [eclipse-tractusx/sig-infra#73]
Things to do:

- [ ] Github catenax-ng organization
- [ ] argocdadmins team
- [ ] teams Catena-X
- [ ] Eclipse Foundation contributor agreement
- [ ] Azure Portal

Accomplish onboarding tasks:

understand DevSecOps role responsibility
get familiar with available documentation
create required accounts
obtain necessary access

**Comment by almadigabor** [comment]
- Eclipse contributor agreement already signed
- Invitation sent to Github cantenax-ng as owner + argocdadmins team member
- Check portal AD access for catena-x
- Check teams access for Catena-X

**Comment by FaGru3n** [comment]
Info from @tomaszbarwicki 

- Got access to Jira& Confluence
- Updated GitHub account with company email address as secondary
- Created Eclipse foundation account
- Subscribed to tractusx mailing list
- had onboarding related meeting with Gabor 
- prepared working environment
  - installation of git, GitHub keys, terraform, az, visual studio
- Got access to :
  - azure portal
  - catenax & tractusx github
  - ArgoCD & Grafana

**Comment by almadigabor** [comment]
Closing this issue as all access have been configured.
