### ISSUE TITLE
GitHub: New fork 

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#74]
repository name within Tractus-X Organisation: 
[portal-shared-components](https://github.com/eclipse-tractusx/portal-shared-components)

repository name within Catena-X NG Organisation: 
`tx-portal-shared-components`

GitHub team to grant access: 
[product-portal](https://github.com/orgs/catenax-ng/teams/product-portal)

Please also a set branch protection rule for main, locking the branch and only allowing fork syncing over the new BETA rules/rulesets, see https://github.com/eclipse-tractusx/sig-infra/issues/54#issuecomment-1571811135 for more context.

**Comment by FaGru3n** [comment]
Hi @evegufy,

created new fork: [tx-portal-shared-components](https://github.com/catenax-ng/tx-portal-shared-components)

FYI for next forks:
[Examplpe Rulesets for tx-portal-frontend-registration](https://github.com/catenax-ng/tx-portal-frontend-registration/settings/rules/27725)

![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/e4337c13-da3b-4cf6-a13d-42bd8b655e5d)
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/65e6521d-4743-4e74-9f0c-81a7a6fd655c)

**Comment by FaGru3n** [comment]
@evegufy  Please review and close if your fine with the result. 😉

**Comment by evegufy** [comment]
@FaGru3n Looks very good, thank you!
