### ISSUE TITLE
GitHub: New Team 

### ISSUE THREAD

**Issue by zfdevzfdev** [eclipse-tractusx/sig-infra#75]
Product GitHub team name: 
quality-foss-app-team

GitHub users to invite:
zfdevzfdev

Maintainer of the new GitHub Team:
zfdevzfdev
@Siegfriedk

**Comment by FaGru3n** [comment]
Hi @zfdevzfdev  could your PO could validate your request and leave a comment here in the issue?

**Comment by FaGru3n** [comment]
Hi @zfdevzfdev  any update on the approval?

**Comment by JulianSchererZF** [comment]
Hi @FaGru3n, as the PO of the Quality FOSS App I can approve the request

**Comment by FaGru3n** [comment]
Team is already available:
https://github.com/orgs/catenax-ng/teams/product-quality-foss-app-team

invitation was send to @zfdevzfdev  to be maintainer of the GitHub Team

**Comment by FaGru3n** [comment]
@zfdevzfdev @JulianSchererZF  will this be a hole new product?

so do need also Vault / Argo Cd Project?

**Comment by FaGru3n** [comment]
Vault was created: quality-foss-app

**Comment by FaGru3n** [comment]
@zfdevzfdev @JulianSchererZF 

Are there any updates or are you ok with the repository and we can close the issue? Thanks in advance.

**Comment by FaGru3n** [comment]
@zfdevzfdev @JulianSchererZF

Are there any updates or are you ok with the repository and we can close the issue? Thanks in advance.

**Comment by zfdevzfdev** [comment]
It would be nice to have a short call just to clarify all the things. Is it possible?

**Comment by FaGru3n** [comment]
> It would be nice to have a short call just to clarify all the things. Is it possible?
Sure no problem, how i can reach you? your email-adress is not know by me... 😃

**Comment by zfdevzfdev** [comment]
Ok, then it is easier to discuss it here.
So, earlier you sent me an invitation to be a maintainer, but I can't seem to find it. Could you please resend it?

> so do need also Argo Cd Project?  -> We don't know it yet

**Comment by FaGru3n** [comment]
Could you maybe login to the MS Teams form Catena-X then we can also communicate..

or you tell me your mail adress and the i will send you an invite... for a meeting.
