### ISSUE TITLE
GitHub: New repository 

### ISSUE THREAD

**Issue by zfdevzfdev** [eclipse-tractusx/sig-infra#76]
Required information:
- Details to your GitHub repository: product-quality-foss-app
- Details to GitHub team to grant access: quality-foss-app-team
@Siegfriedk

**Comment by FaGru3n** [comment]
Hi @zfdevzfdev  any update on the approval?

**Comment by JulianSchererZF** [comment]
Hi @FaGru3n, as the PO of the Quality FOSS App I can approve the request

**Comment by FaGru3n** [comment]
Repo: https://github.com/catenax-ng/product-quality-foss-app is now available.
dedicated gh-team was also generated: https://github.com/orgs/catenax-ng/teams/product-quality-foss-app-team

@zfdevzfdev  Who should be the maintainer of the GitHub Team?

FYI: @JulianSchererZF

**Comment by zfdevzfdev** [comment]
I can take care of the maintenance.
Thank you!

**Comment by FaGru3n** [comment]
@zfdevzfdev 

Invitation to the gh-team was renewed because it was not acepted during 7 days.

![Image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/d578a7aa-e31d-4cef-ac06-8e3cf0758a2f)

Please review and close the issue.

**Comment by FaGru3n** [comment]
Are there any updates?

**Comment by FaGru3n** [comment]
> I get a "Page not found" for the team page.

![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/e4383a63-54ad-4e85-8d08-825db007627b)
First you have to join the GitHub Organisation

**Comment by FaGru3n** [comment]
Invitation to GitHub Org and Maintainer permissions for the gh-team `quality-foss-app-team`

![Image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/f150689e-90a6-4725-b9f0-f88cca518eef)

was successfull

**Comment by zfdevzfdev** [comment]
Everything works, thanks for the support, @FaGru3n !

**Comment by TobiasKampsZF** [comment]
> > I get a "Page not found" for the team page.
> 
> ![image](https://user-images.githubusercontent.com/121097161/252585749-e4383a63-54ad-4e85-8d08-825db007627b.png) First you have to join the GitHub Organisation

Probably I also need an invite to the team page?

**Comment by FaGru3n** [comment]
Hi @TobiasKampsZF, yes if you want to become also a member of the team the maintainer @zfdevzfdev have to invite you into it, so you can also see either the team page or the related repositories.

But first of all you need to beome a member of the catenax ng organisation. Please checkout our Issue templates here
https://github.com/eclipse-tractusx/sig-infra/issues/new/choose

**Comment by FaGru3n** [comment]
Hi @TobiasKampsZF,

yes. 😉 
![image](https://github.com/eclipse-tractusx/sig-infra/assets/121097161/54598772-9ef7-4b2f-abd4-6c1a7ffbbf40)
