### ISSUE TITLE
Change branch protection rules for tx-portal-iam

### ISSUE THREAD

**Issue by evegufy** [eclipse-tractusx/sig-infra#77]
Regarding the repo [tx-portal-iam](https://github.com/catenax-ng/tx-portal-iam):

1. Please remove the branch protections rule for the helm-environments branch
2. Please also change branch protection rule for main, locking the branch and only allowing fork syncing over the new BETA rules/rulesets, see https://github.com/eclipse-tractusx/sig-infra/issues/54#issuecomment-1571811135 or https://github.com/eclipse-tractusx/sig-infra/issues/74#issuecomment-1591066455 for more context

**Comment by FaGru3n** [comment]
Hi @evegufy,

- [x] 1. Please remove the branch protections rule for the helm-environments branch
- [x] 2. Please also change branch protection rule for main

sure thanks for raising the issue.
implemeted the same ruleset except the `dev` branch as in the new fork form #74.

**Comment by FaGru3n** [comment]
@evegufy  Please verify the changes and close the issue 😉 

Thx in advanse.

**Comment by evegufy** [comment]
Works, thx!
