### ISSUE TITLE
GitHub: Invite member 

### ISSUE THREAD

**Issue by matbmoser** [eclipse-tractusx/sig-infra#85]
Who should be invited to [Catena-X ng](https://github.com/catenax-ng)

GitHub User:
@dsrparracho

Vouching person: @jocbra -> Jochen Braun

@thorstendikmann -> Thorsten Dikmann

**Comment by carslen** [comment]
dsrparracho has been invited to GH org catenax-ng. Keep in mind that the invitation is valid for 7 days starting today and that the GH org is requiring [GH 2fa authentication](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa) for login.

After dsrparracho has accepted the invite, a GH team maintainer can add him to his GH team.

**Comment by matbmoser** [comment]
> dsrparracho has been invited to GH org catenax-ng. Keep in mind that the invitation is valid for 7 days starting today and that the GH org is requiring [GH 2fa authentication](https://docs.github.com/en/authentication/securing-your-account-with-two-factor-authentication-2fa) for login.
> 
> After dsrparracho has accepted the invite, a GH team maintainer can add him to his GH team.

Perfect I will check if Diogo and then with Jochen the responsible for the GH team. Once everything is done I will inform here in and then we can close this issue. 


Thank you very much @carslen  👍🏻

**Comment by FaGru3n** [comment]
Hi @matbmoser all done from your side?

**Comment by matbmoser** [comment]
Yes, I am sorry I forgot to check this issue and close it :) @dsrparracho is now contributor in Tractus-X
