### ISSUE TITLE
Align diagram drawing into a TRG

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#87]
ETX / Catena-x has a lot of documentation which is primarily / will be only in markdown and open source.

What has not been aligned is a open source way of drawing diagrams of different types across all components and teams.

We will be moderating, collecting and manifesting a open source solution for drawing diagrams in ETX.

There are two main approchas possible:

- [x] Diagram as code
Open Source tool drawing a diagram which than is exported and used while the original file is present next to it
- [x] Preview Option in GitHub itself
 
Hints:

- [x] Ask the tractusx-dev mailing list for suggestions
- [x] Suggestions was added to the disscussion https://github.com/eclipse-tractusx/sig-infra/discussions/19
- [x] Use the Office Hour to present options
- [x] Create a benchmark diagram set (type a, b, c, d, e, f)
- [x] Implement them in proposed / found libraries #186 
- [x] Get Feedback from people
- [x] Create a TRG Draft https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/401
- [x] Sigi will show it in PO sync

**Comment by FaGru3n** [comment]
add 2 reusable workflows wich can be used as example for others to generate the static files in their repositories whithin Eclipse Tractus-X

PR: 
https://github.com/eclipse-tractusx/sig-infra/pull/163

**Comment by FaGru3n** [comment]
updated the open disscussion on our sig-infra repo
https://github.com/eclipse-tractusx/sig-infra/discussions/19#discussioncomment-7010714

**Comment by FaGru3n** [comment]
PR merged, @Siegfriedk do you need something to show?

**Comment by COROANN** [comment]
Hey Fabi, I wasn't joning the PO Syncs lately because I don't have the time. Lets talk later

**Comment by FaGru3n** [comment]
Dev Mailings List Info was sent.

**Comment by FaGru3n** [comment]
first aditions were made after feedback from stephan bauer some 
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/429
https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/issues/427

**Comment by FaGru3n** [comment]
updated

**Comment by FaGru3n** [comment]
Guess the only thing is needed is a mandatory date... unless i guess the most people had enough time to discuss and validate... their diagrams...

@Siegfriedk do you think we could update this after current release?

**Comment by FaGru3n** [comment]
for now i would close it...

**Comment by Siegfriedk** [comment]
> Guess the only thing is needed is a mandatory date... unless i guess the most people had enough time to discuss and validate... their diagrams...
> 
> @Siegfriedk do you think we could update this after current release?

Yes, should be done/mandatory by march
