### ISSUE TITLE
Make our gh checks dashboard 'product' focused

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#88]
**AC**
- It doesn't render repository by repository but product by product
  - Implies retrieving all .tractusx files, grouping repositories
-  Also show all repositories which are not a. product in a visual different way (perhaps at the bottom of the table, a second table or with a filter?

**Comment by SebastianBezold** [comment]
I guess this can be seen as done. Available here: https://eclipse-tractusx.github.io/sig-release/
there will be a lot of incremental improvements of course

**Comment by FaGru3n** [comment]
> I guess this can be seen as done. Available here: https://eclipse-tractusx.github.io/sig-release/ there will be a lot of incremental improvements of course

nice look and feel for the dashboard
