### ISSUE TITLE
Create action to check on PR basis, if existing DEPENDENCIES are up to date

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#89]
Create composite action + workflow example.

- Input:  Language/build tool specific Dependencies list

Steps:

1. download Dash
2. install Java
3. Create DEPENDENCIES from input
4. compare with existing DEPENDENCIES
5. if they are not identical, fail the check

**Comment by SebastianBezold** [comment]
superseded by #168. Closing this one here
