### ISSUE TITLE
Create ghc TRG4.03 non-root container

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#91]
Read helm chart, check for pod spec without securityContext

**AC**
Difficulty: It could make totally sense to add kicks or could be easier to only require helm and do helm template and parse it as yaml

**Additional information / links**
We might want to discuss this in the team

**Comment by carslen** [comment]
Please review eclipse-tractusx/tractusx-quality-checks#39

**Comment by carslen** [comment]
Did rework the code according to the pkg changes in the repo. I've closed eclipse-tractusx/tractusx-quality-checks#39 due to the mess up with rebase. Created a new PR: eclipse-tractusx/tractusx-quality-checks#55 

Please review.

**Comment by carslen** [comment]
approved by @tomaszbarwicki
