### ISSUE TITLE
Tomasz: Commiter

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#93]
**PR** 
- https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/268

**Comment by tomaszbarwicki** [comment]
https://github.com/eclipse-tractusx/tractusx-quality-checks/pull/19

**Comment by tomaszbarwicki** [comment]
updates eclipse-tractusx/sig-infra#19

**Comment by tomaszbarwicki** [comment]
Reviewed:
https://github.com/eclipse-tractusx/tractusx-quality-checks/pull/39
https://github.com/eclipse-tractusx/sig-release/pull/37

**Comment by tomaszbarwicki** [comment]
In order to see my PRs you need to open this issue in a separate tab.

**Comment by tomaszbarwicki** [comment]
### QG4:

Discovery Finder:
https://github.com/eclipse-tractusx/sldt-discovery-finder/issues/29

Portal:
https://github.com/eclipse-tractusx/portal-cd/issues/66
https://github.com/eclipse-tractusx/portal-frontend/issues/215
https://github.com/eclipse-tractusx/portal-frontend-registration/issues/51
https://github.com/eclipse-tractusx/portal-assets/issues/131
https://github.com/eclipse-tractusx/portal-backend/issues/207
https://github.com/eclipse-tractusx/portal-shared-components/issues/36

**Comment by florianrusch-zf** [comment]
Firstly, thank you for compiling the list of contributions! Looks promising 🙂

But in general I have a questions regarding this approach: @Siegfriedk, @FaGru3n, and @theOtherCommitters, does this seem like an overly spammy way to list contributions? Each linked issue now contains the following line. So far the list has been perfectly adequate for the election, in my opinion. What are your thoughts on this?

![image](https://github.com/eclipse-tractusx/sig-infra/assets/97295414/28b4d8c7-fb5b-44ed-b90c-d1e9d92b3d6d)

Of course this approach may suffice, however, consider a scenario where 20 or more contributors wish to become committers and generate a GitHub issue linking multiple issues and PRs. Is this really beneficial? Of course, there is nothing inherently wrong with this approach. In my opinion, the list of contributions serves only a temporary purpose for the election only (please correct me if I'm wrong!). Afterwards, the list is entirely outdated and there is no reason to preserve it anywhere (certainly not in the form of a GitHub issue).

However, this is solely my personal opinion. I am eager to hear your thoughts on this.

**Comment by FaGru3n** [comment]
Hi @florianrusch-zf i agree that the menitioning withing the related issue looks not ideal, because it will suggest the person is only doing it to become a committer. 

In Fact is is just a list to get all the contributions and commits, for maybe upcomming proposal to become a committer and makes the life of the proposing person a bit easier, because he/she can just visit this issue collections with all contributions he/she did... 

Other idea would be the listing in everyones personal profile to get an overview from the contributions to eclipse tractus-x e.g.  [my profile listing](https://github.com/FaGru3n?tab=overview&from=2023-08-01&to=2023-08-31&org=eclipse-tractusx) but then everyone have to agree this to share it also with the world, which contributions he/she has made.

Or how do you would save a list of contributions to become a committer?

**Comment by Siegfriedk** [comment]
@FaGru3n election is done but PMC approval is sitill missing

**Comment by FaGru3n** [comment]
> @FaGru3n election is done but PMC approval is sitill missing

this is what i try to mention 😉
