### ISSUE TITLE
Redefine TRG 5.05 Chart Values

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#95]
**Reason**

**AC**

- create sane default suggestion for registry, repository, tag, pullPolicy and others which might make sense as an new update to this trg
- Checkout helm init as sane default suggestion
- Discuss in the team and office hour
- Create new ticket to add it as ghc

**Additional information / links**

**Comment by carslen** [comment]
What is meant with _helm init_, @Siegfriedk? With Helm v3 there is no `helm init` available anymore.

In addition, can you elaborate a bit what's not clear or no sane default in existing 5.05? The only thing which comes to my mind would be to remove the bitnami image in the example and pick a random Tractus-X Docker image instead to clarify it's meant for our images and not Helm dependencies (although it should be clear, as dependencies are defined differently though).

**Comment by FaGru3n** [comment]
will close this issue.
