### ISSUE TITLE
Extract dependency versions from TRG 5.07 into new TRG

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#96]
**Reason**

**AC**

- We need a new TRG to align all postgresql versions to at least major and define a minimum postgresql version (in case of features people are depending on)

**Additional information / links**
https://eclipse-tractusx.github.io/docs/release/trg-5/trg-5-07/

**Comment by Siegfriedk** [comment]
Might be obsolete https://github.com/eclipse-tractusx/eclipse-tractusx.github.io/pull/400 please revisit perhaps you have another better idea in regard of.

Also minimum version is not included in my pr

**Comment by FaGru3n** [comment]
in my opinion obsolete, and already merged IMHO would close this issue.
