### ISSUE TITLE
Introduce kubeapps

### ISSUE THREAD

**Issue by FaGru3n** [eclipse-tractusx/sig-infra#99]
**Reason**
To provide our release managment and testing team the chance to do the Ops Readiness by themselfs and for teams to see how a helm chart might be used in public, we will setup a basic kubeapps instance.

**AC**

- Kubeapps is installed on preprod and beta cluster
  - Can be installed on all others without much work, if its easier to install it on all, we will just do that
- subdomain is app.<env>.demo...
- Configure our Helm chart repository as default chart source
  - dev helm repository (stable will be used later for official eclipse releases)
- Login through github team
  - For now one team which has full access

**Additional information / links**
https://kubeapps.dev/

**Comment by almadigabor** [comment]
Draft PR for tackling this issue: https://github.com/catenax-ng/k8s-cluster-stack/pull/404

**Comment by almadigabor** [comment]
Our clusters trusts Azure Active Directory as the OAuth2 provider. The AKS cluster strategy for authentication and authorization currently is Azure AD + Kubernetes RBAC. Therefore the following options would work:

- Create the Users/Applications with the proper rights in Azure AD (IAM)
- Create ServiceAccounts with proper Roles in k8s
- Introduce a new tool like [Pinniped](https://pinniped.dev/) to dynamically grant access to different resources in the cluster

**Comment by almadigabor** [comment]
Another PR for kubeapps cluster resources (namespace, vault-secret) https://github.com/catenax-ng/product-onboarding/pull/54

**Comment by almadigabor** [comment]
This PR is ready for review: https://github.com/catenax-ng/k8s-cluster-stack/pull/404

Next up is writing the installation/config guide.

**Comment by almadigabor** [comment]
Opened an issue in the Bitnami repo as it is not compatible with the argocd-vault-plugin reference format. https://github.com/bitnami/charts/issues/20679

**Comment by almadigabor** [comment]
Opened an issue to track the progress of the problem https://github.com/catenax-ng/k8s-cluster-stack/issues/441

**Comment by almadigabor** [comment]
Closing this issue as Kubeapps is not the priority anymore as consortia phase is coming to an end soon.
